### ISSUE TITLE
Problem with game

### ISSUE THREAD

**Issue by satsis** [lightspark/lightspark#1005]
INFO: AUDIO DEC: Audio sample rate 22050
INFO: AUDIO DEC: Audio channels 1
INFO: NET: STANDALONE: DownloadManager::download 'http://agi.armorgames.com/assets/agi/AGI2.swf'
INFO: NET: STANDALONE: DownloadManager: remote file
INFO: NET: CurlDownloader::execute: reading remote file: http://agi.armorgames.com/assets/agi/AGI2.swf
INFO: throwing exception:0x366d250 id:1034 Error #1034: Type Coercion failed: cannot convert Object to Function.
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1034: Error #1034: Type Coercion failed: cannot convert Object to Function.
INFO: dynamic cast:TypeError
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1034: Error #1034: Type Coercion failed: cannot convert Object to Function.
    at *::FSMState/()
    at _-Xh::FSM/addState()
    at Main/init()
    at Main/handleAddedToStage()
    at Preloader/startup()
    at Preloader/loadingFinished()
    at Preloader/checkFrame()

INFO: FPS: 54 7

**Comment by dbluelle** [comment]
Can you upload the swf file that causes this issue or provide a link to download the game?

**Comment by satsis** [comment]
[https://f.vpbot.ru/2022/11/crush-the-castle-adventures.swf](url)

**Comment by satsis** [comment]
[https://f.vpbot.ru/2022/11/castle.swf](url)

**Comment by dbluelle** [comment]
This seems to have been fixed by one of the revent commits.
It doesn't crash anymore but still has several graphical glitches
