### ISSUE TITLE
Add artifacts to actions.

### ISSUE THREAD

**Issue by Fancy2209** [lightspark/lightspark#1032]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [X] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [X] Other subject matter not listed

---

### Description of your issue

*Explanation of your issue in arbitrary form goes here.*
Currently the github actions only provides a check for if the project builds after a pr, what I suggest is for it to also generate downloadable "artifacts", so we can submit issues with the latest development version of lightspark (building software on windows is pain).

**Comment by dbluelle** [comment]
I think the normal project builds after pushing to the repository already create the windows installers, so IMHO we "only" have to modify the  .github/workflows/build.yml file to create a "nightly" or "development" release.
I'm not very familiar with the whole github actions stuff, so maybe someone else can come up with a PR that enables this.

**Comment by Fancy2209** [comment]
https://github.com/Fancy2209/lightspark/actions/runs/3961219073/workflow
I was trying to discover how to do it but it made a valid line unvalid

**Comment by huwdp** [comment]
@Fancy2209 On line 192, replace 
```
      - name: Upload a Build Artifact
```
with 
```
    - name: Upload a Build Artifact
```

I run the code under https://jsonformatter.org/yaml-validator.

**Comment by Fancy2209** [comment]
Now the issue is that the repo key for MXE Broke.
Wonder if it's because I'm using a fork

**Comment by Fancy2209** [comment]
> I think the normal project builds after pushing to the repository already create the windows installers, so IMHO we "only" have to modify the .github/workflows/build.yml file to create a "nightly" or "development" release. I'm not very familiar with the whole github actions stuff, so maybe someone else can come up with a PR that enables this.

Artifacts was easier to figure out than a release, so I went that route.

**Comment by huwdp** [comment]
@dblue, don't mind if I create a new branch on this repo and give my changes [here](https://github.com/huwdp/lightspark) a go? I get "Resource not accessible by integration" when trying to create a release so I think I can only try the changes on this repo

**Comment by dblue** [comment]
> @dblue, don't mind if I create a new branch on this repo and give my changes [here](https://github.com/huwdp/lightspark) a go? I get "Resource not accessible by integration" when trying to create a release so I think I can only try the changes on this repo

@dbluelle

**Comment by dbluelle** [comment]
IMHO the first lines of the buld.yml file state that the actions should take place whenever commits are pushed to the _master_ branch, so I don't think this will work in a separate branch.
However I think we can just commit this to the master branch and see if it works.
Just make a PR.

**Comment by dbluelle** [comment]
OK, creating a pre-release version now works, see https://github.com/lightspark/lightspark/releases/tag/refs%2Fheads%2Fmaster 
I still have to edit the description and publish the release manually, it would be nice if that was also done automatically.

**Comment by huwdp** [comment]
Had a look, it looks like the description can be added in easily by adding 'body' to [actions/create-release](https://github.com/actions/create-release) in build.yml.

I think for the publishing issue, we could set draft to false [here](https://github.com/lightspark/lightspark/blob/master/.github/workflows/build.yml#L30) to fix that issue.

**Comment by huwdp** [comment]
Do releases get published automatically? I ask as draft [here](https://github.com/lightspark/lightspark/blob/master/.github/workflows/build.yml#L31) is set to true.

**Comment by dbluelle** [comment]
I've not activated the automatic publishing as there are still two problems with the development releases:
1) the previous "Development release" doesn't get deleted when creating a new one, so I have to login and do that.
2) github requires a tag associated with a release, but doesn't automatically create one (I would prefer the "latest" tag to be always set to the latest commit, but currently I have to delete the old "latest" tag and create a new one manually)
