### ISSUE TITLE
I don't know how can i compile lightspark in ubuntu 22.10

### ISSUE THREAD

**Issue by Dans009** [lightspark/lightspark#1044]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [x] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [x] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

My question is, i don't know what to do after installing the development packages and the needed tools.
i know that it's just compile but in don't know how to do this, i'm new to ubuntu, and the guide didn't said
what to do with the commands to compile lightspark, and if i try to do manually, when i use "cd lightspark"
the terminal just tells me that this directory does not exists. Can someone explain me how to do this?

**Comment by n0samu** [comment]
Hi, can you please click the Discussions tab and open a discussion instead? Issues are not the place for this.

**Comment by huwdp** [comment]
Run this in the Terminal to compile.
```
sudo apt install git gcc g++ nasm cmake libcurl4-gnutls-dev libsdl2-dev libpango1.0-dev libcairo2-dev libavcodec-dev libswresample-dev libglew-dev librtmp-dev libjpeg-dev libavformat-dev liblzma-dev
git clone https://github.com/lightspark/lightspark.git
cd lightspark
./build.sh
```

Then run ```lightspark somefile.swf``` to run a swf file.
