### ISSUE TITLE
Uncharm 12 Rupertcauns not playing

### ISSUE THREAD

**Issue by gisly** [lightspark/lightspark#1111]
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
[Uncharm_12_Rupertcauns_swf.zip](https://github.com/lightspark/lightspark/files/13624156/Uncharm_12_Rupertcauns_swf.zip)

#### Provide the complete set of instructions required to reproduce the problem:

1. use the latest windows release binary (Lightspark version 0.8.7-git)
2. run 
```
lightspark.exe bannergame01hq.swf -l 4 > trace.log 2>&1
```

#### What kind of failure is your issue?

- [x] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
lightspark version 0.8.7-git
```

#### What operating system are you are running on?

- [x] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)
[Uncharm_12_Rupertcauns_trace.zip](https://github.com/lightspark/lightspark/files/13624161/Uncharm_12_Rupertcauns_trace.zip)

### Description of your issue

The swf file starts but then crashes with some errors in the trace file attached.

**Comment by dbluelle** [comment]
I've fixed the crash but unfortunately the game doesn't render anything useful in lightspark afterwards.
The game is heavily obfuscated so it is difficult to debug.
I keep this issue open until the rendering issues are resolved.

**Comment by gisly** [comment]
Hi! Thank you very much for your help. I have installed the nightly build but I was still unable to run the game.
I ran the same command
```
lightspark.exe bannergame01hq.swf -l 4 > trace.log 2>&1
```

Is it an issue with the swf file itself?

**Comment by dbluelle** [comment]
Yes this is a very weird swf. It doesn't even run properly on the adobe standalone flash player, so I don't know how it should "normally" work...
With lightspark you only can click on the "www.escapegames24.com" text (after the intro) and it tries to open that url in a browser (this feature is not implemented for standalone lightspark). 
Is there anything else that should be clickable?
As mentioned above the swf is heavily obfuscated, so it's not easy to  check on the inner workings of the actionscript code.

**Comment by gisly** [comment]
Hi! Sorry for the late reply. Afaik, there should be sort of a platform game there. Here is a screenshot https://s00.yaplakal.com/pics/pics_original/4/6/5/1086564.jpg. However, I am not sure if the swf file is correct at all. Perhaps, the original swf is actually lost.
