### ISSUE TITLE
Fancy Pants Classic Pack Demo crashes when entering the first Portal Tear

### ISSUE THREAD

**Issue by Fancy2209** [lightspark/lightspark#1119]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

[URL of page](https://store.steampowered.com/app/1668460/The_Fancy_Pants_Adventures_Classic_Pack)

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

As this is a demo of a steam game, I would rather not provide a download.

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. *Insert second action here*
3. *Insert third action, and so on*

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.7-git Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [X] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [X] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
When you get to the first portal in the Demo, it'll just crash.
![imagem](https://github.com/lightspark/lightspark/assets/64917206/87217435-8398-4808-9b93-fb3dfeb1ca9c)
Standard Output
[ClassicPack.log](https://github.com/lightspark/lightspark/files/15082039/ClassicPack.log)
with l 4
[ClassicPack.log](https://github.com/lightspark/lightspark/files/15082102/ClassicPack.log)

**Comment by dbluelle** [comment]
Hmm, unfortunately I couldn't reproduce the crash. 
On my machine World 4 is properly loaded (but the graphics are still garbage...).
From the log I see that you are loading the steamworks extension. I tried that, too, but it doesn't have any effect.
So, do you use any additional command line arguments?
I start the game with
`lightspark --air -le ./META-INF/AIR/extensions/com.amanitadesign.steam.FRESteamWorks/library.swf  "ClassicPack.swf"`
or
`lightspark --air "ClassicPack.swf"`

**Comment by Fancy2209** [comment]
Both commands do it, it only happens on windows. Linux works fine, for some reason WSL2 fails though.
![image](https://github.com/lightspark/lightspark/assets/64917206/fa24d856-c1ad-413b-92b4-16f75503c451)
Also pressing the left mouse button and moving the mouse will crash the game due to nativewindows stuff

**Comment by dbluelle** [comment]
It seems like tha crash happens when the game is trying to load the assets of World 4 (the files in World4/assets/Level2).
Apparently lightspark can't access these files.
Does this also happen if you start lightspark with `-s local-with-filesystem` ?

**Comment by Fancy2209** [comment]
> It seems like tha crash happens when the game is trying to load the assets of World 4 (the files in World4/assets/Level2). Apparently lightspark can't access these files. Does this also happen if you start lightspark with `-s local-with-filesystem` ?

yep, exact same error. Lightspark also seems to use the CWD instead of the Directory the swf is on when using Windows

**Comment by dbluelle** [comment]
NativeWindow.startMove is now implemented, so the crash when pressing the mouse button is fixed.
I've changed setting the base path when starting lightspark, that might fix the crash on Windows.

**Comment by Fancy2209** [comment]
Nope
I still have to copy lightspark to the game folder, and lightspark still panics
