### ISSUE TITLE
Error #1056: Cannot create property z on away3d.cameras::Camera3D

### ISSUE THREAD

**Issue by Fancy2209** [lightspark/lightspark#1123]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:
https://github.com/away3d/away3d-tutorials-fp11/raw/master/tutorials/materials/basic_atf_shading/bin/Basic_Shading_with_ATF.swf

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
https://github.com/away3d/away3d-tutorials-fp11/raw/master/tutorials/materials/basic_atf_shading/bin/Basic_Shading_with_ATF.swf

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the SWF

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.7-2142-g2d70f2f5 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux:  Fedora 39
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [X] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ X I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
```
INFO: throwing exception:0x1c95f90 id:1056 Error #1056: Cannot create property z on away3d.cameras::Camera3D.
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1056: Cannot create property z on away3d.cameras::Camera3D.
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1056: Cannot create property z on away3d.cameras::Camera3D.
    at away3d.cameras::Camera3D/()
    at Basic_Shading_with_ATF/initEngine()
    at Basic_Shading_with_ATF/init()
    at Basic_Shading_with_ATF/()

```
[Shading.log](https://github.com/lightspark/lightspark/files/15100363/Shading.log)
![image](https://github.com/lightspark/lightspark/assets/64917206/315cacd8-a660-4673-a054-559a29bd61c3)

**Comment by dbluelle** [comment]
The crash is now fixed, but the 3d rendering still has some glitches...
