### ISSUE TITLE
Fancy Pants Classic pack crashes on boot

### ISSUE THREAD

**Issue by Fancy2209** [lightspark/lightspark#1124]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:

https://store.steampowered.com/app/1668460/The_Fancy_Pants_Adventures_Classic_Pack/

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

Paid Game with Steam DRM, cannot provide a public download
https://store.steampowered.com/app/1668460/The_Fancy_Pants_Adventures_Classic_Pack/

#### Provide the complete set of instructions required to reproduce the problem:

1. Load FPA Classic Pack/ClassicPack.swf (command used `lightspark FPA\ Classic\ Pack/ClassicPack.swf --air -le FPA\ Classic\ Pack/META-INF/AIR/extensions/com.amanitadesign.steam.FRESteamWorks/library.swf`)

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [X] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.7-2142-g2d70f2f5 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: Fedora 39
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue

```
INFO: Lightspark version 0.8.7-2142-g2d70f2f5 Copyright 2009-2013 Alessandro Pignotti and others
INFO: RenderThread this=0x1c23d60
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 37
INFO: FrameRate 60
INFO: Creating VM
INFO: loading extension:FPA Classic Pack/META-INF/AIR/extensions/com.amanitadesign.steam.FRESteamWorks/library.swf
INFO: zlib compressed SWF extension: Version 11
INFO: SWF Metadata:
	:		
INFO: MaxRecursionDepth: 1000, ScriptTimeoutSeconds: 60
INFO: loading extension done:FPA Classic Pack/META-INF/AIR/extensions/com.amanitadesign.steam.FRESteamWorks/library.swf
INFO: Debugger enabled, reserved: 6517, password: $1$9F$bEoR1YpDsPwj2Nj48qU2s.
INFO: MaxRecursionDepth: 256, ScriptTimeoutSeconds: 2
ERROR: Error while reading tag 75. Size=11697 expected: 12165
INFO: FPS: 1 34
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: graphics driver:OpenGL Vendor=AMD Version=4.6 (Compatibility Profile) Mesa 23.3.6 Renderer=AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.54, 6.6.9-200.fc39.x86_64) GLSL=4.60
INFO: OpenGL supported compressed texture format:83f0
INFO: OpenGL supported compressed texture format:83f2
INFO: OpenGL supported compressed texture format:83f3
INFO: OpenGL supported compressed texture format:9274
INFO: OpenGL supported compressed texture format:9278
INFO: OpenGL supported compressed texture format:9270
INFO: OpenGL supported compressed texture format:9272
INFO: OpenGL supported compressed texture format:9271
INFO: OpenGL supported compressed texture format:9273
INFO: OpenGL supported compressed texture format:9276
INFO: throwing exception:0x133fff0 id:1065 Error #1065: Variable vhgdhj is not defined.
INFO: ~RenderThread this=0x1c23d60
INFO: ~InputThread this=0x1c246d0
```
logging set to 4
[ClassicPackFull.log](https://github.com/lightspark/lightspark/files/15101117/ClassicPackFull.log)

**Comment by dbluelle** [comment]
I could reproduce this now.
The problem is that we load the steamworks extension, but we currently don't do anything when the game ist trying to access the extension. The extension is basically a wrapper around a windows dll (FRESteamworks.dll), and I can't easily load that dll from linux.
There seems to exist a linux version of that extension (FRESteamworks.so) but unfortunately the game doesn't ship that.

**Comment by Fancy2209** [comment]
> I could reproduce this now. The problem is that we load the steamworks extension, but we currently don't do anything when the game ist trying to access the extension. The extension is basically a wrapper around a windows dll (FRESteamworks.dll), and I can't easily load that dll from linux. There seems to exist a linux version of that extension (FRESteamworks.so) but unfortunately the game doesn't ship that.
The game does work with it on AIR though, i've tried. If you unpack the ane file from the D20Studios extension and put the files in the right place it'd work on AIR (I tested by replacing files from a game that used AIR for linux)
