### ISSUE TITLE
FPA Classic Pack fails at using the Steam ANE on Windows

### ISSUE THREAD

**Issue by Fancy2209** [lightspark/lightspark#1130]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
https://store.steampowered.com/app/1668460/The_Fancy_Pants_Adventures_Classic_Pack/

#### Provide the complete set of instructions required to reproduce the problem:

1. Open the Game with Lightspark on Windows with AIR on

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:
```
INFO: Lightspark version 0.8.7-git Copyright 2009-2013 Alessandro Pignotti and others`
```

#### What operating system are you are running on?

- [X] Windows 11
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
Game dies when trying to talk to steam.

[FPAckL4.log](https://github.com/user-attachments/files/16071358/FPAckL4.log)
[FPAck.log](https://github.com/user-attachments/files/16071359/FPAck.log)

**Comment by dbluelle** [comment]
The logs look like it didn't look for the native extensions at all.
Maybe you forgot to start lightspark with command line argument `--air ` ?

**Comment by Fancy2209** [comment]
Oh woops, it was just when making logs that I forgot
here's logs with the air option
[FPAckL4.log](https://github.com/user-attachments/files/16073489/FPAckL4.log)
[FPAck.log](https://github.com/user-attachments/files/16073490/FPAck.log)
