### ISSUE TITLE
LS crashing with LC_ALL="C"

### ISSUE THREAD

**Issue by janimo** [lightspark/lightspark#119]
In the current test setup about 20 tests crash because the script sets up LC_ALL="C"
Setting it back as LC_ALL="" after the tools needing the C locale are run (sort and comm)
allows them to pass.
Lightspark should not crash with wrong locale set [*] so I think the test script should be left as
is and see why the app crashes. It calls setlocale(LC_ALL,"") at startup that's why I find it strange
that setting the environment variable matters at all.

This finishes
LC_ALL=""  lightspark tamarin-SWF/ecma3/String/toLocaleUpperCase3_.swf

This crashes
LC_ALL="C"  lightspark tamarin-SWF/ecma3/String/toLocaleUpperCase3_.swf

**Comment by dbluelle** [comment]
I couldn't reproduce this, so I'm closing the issue.
Feel free to create a new one if the problem still exists.
