### ISSUE TITLE
Avoid using heap allocation in favor of stack allocation

### ISSUE THREAD

**Issue by mgehre** [lightspark/lightspark#144]
...because its faster and does not produce memory fragmentation.
A good place to start is abc_opcodes. A lot of functions start with

```
ASObject** args = new ASObject*[argslen];
...
delete[] args;
```

which can be transformed into

```
ASObject* args[argslen];
```

etc.

**Comment by dbluelle** [comment]
I think we have no places anymore where g_newa is not used.
