### ISSUE TITLE
Script exceptions should not halt the vm

### ISSUE THREAD

**Issue by mgehre** [lightspark/lightspark#153]
Producing an uncatched exception in frameScript or ENTER_FRAME handler etc. should not halt the whole vm. The proprietary player prints the exception, but continues to handle further events. I.e. if the first ENTER_FRAME threw, then the next ENTER_FRAME is run nevertheless.
Our current behavior is to halt the whole VM in case of uncatched exception.

**Comment by dbluelle** [comment]
We now have a command line argument that does this
