### ISSUE TITLE
migration to gtk3

### ISSUE THREAD

**Issue by devkral** [lightspark/lightspark#175]
It would be nice if lightspark could use the new features of gtk3.
I tried already to compile with gtk3 instead of gtk2.
My results:
The good thing: The compilation worked (I had to include just one library). Maybe very few things need to be ported.

The bad thing:
As far as I see gtk3 doesn't run beyond a gtk2 program like firefox. But these programs are migrating already.
Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=627699
The same with chromium:
https://code.google.com/p/chromium/issues/detail?id=79722
And epiphany is already gtk3.

I haven't tested lightspark as a standalone application yet. Also I haven't checked the source code for deprecated libraries and functions.

**Comment by dbluelle** [comment]
no dependency on gtk any more in 0.8.1
