### ISSUE TITLE
Bug Report: Audio "echo" (2nd loop) with delay of approx. 3 minutes

### ISSUE THREAD

**Issue by ghost** [lightspark/lightspark#203]
Hardware: Samsung Melroi R510 with GeForce 9200M GS

OS: Slackware Linux 13.37 32bit

Browser: Seamonkey

Lightspark version: 0.6.0.1

When opening a video like https://www.youtube.com/watch?v=4HsGuWRrbOw after a while (for example 3,xx minutes) another loop of the video's audio starts to play in the background (same volume).
So we have 2 traces of audio now, whereat the first one is the correct sound which belongs to the current video time and the second one is an echo with a delay of 3,xx minutes.

When running
ps ax | grep pulse
the output is
 2592 ?        Sl     0:01 /usr/bin/pulseaudio --start

Sorry for bad English!

**Comment by dbluelle** [comment]
This can't be reproduced any more, so I'm closing this
