### ISSUE TITLE
Error #1009: null has no properties [For www.youku.com]

### ISSUE THREAD

**Issue by liangtaohy** [lightspark/lightspark#213]
lightspark couldn't support youku player. The following error is always reported.

CALLS:                                                 getLex: [ns:] Class 
CALLS:                                                 asTypelate
CALLS:                                                 coerce [ns:] Class 
CALLS:                                                 setSlot 4 0x7fd08c000ee0=Null
CALLS:                                                 getScopeObject: 0x7fd084319d20
CALLS:                                                 getSlot 5 0x7fd08c000ee0=Null
CALLS:                                                 pushNull
CALLS:                                                 ifEq (taken)
CALLS:                                                 getScopeObject: 0x7fd084319d20
CALLS:                                                 getSlot 4 0x7fd08c000ee0=Null
CALLS:                                                 pushString getStyleDefinition
CALLS:                                                 getProperty [ns:] [privns:] [staticprotns:Object] [pakintns:fl.mana
gers] [staticprotns:fl.managers:StyleManager] [protns:fl.managers:StyleManager] getStyleDefinition 0x7fd08c000ee0
TRACE:                                                 got an TypeError: Error #1009: null has no properties.

**Comment by dbluelle** [comment]
This can't be reproduced as the site doesn't use flash anymore, so I'm closing this
