### ISSUE TITLE
lightspark 0.5.7 fails to initialize Hulu player (Firefox 17)

### ISSUE THREAD

**Issue by postmodern** [lightspark/lightspark#214]
I recently tested lightspark 0.5.7 with Firefox 17 on Fedora 17 x86-64. When loading the [Hulu player](http://www.hulu.com/watch/53330) I get this error:

<pre>
SWF: http://www.hulu.com/site-player/204841/playerwrapper.swf
Cause: postData.empty() /builddir/build/BUILD/lightspark-0.5.7/src/scripting/flash/net/flashnet.cpp:1597
</pre>

**Comment by eiglow** [comment]
The link you provided seems to no longer exist...

**Comment by postmodern** [comment]
I no longer use lightspark, but you could try any other Hulu link; after "Starting Your Free Trial" of course.
