### ISSUE TITLE
Is not showing player menu

### ISSUE THREAD

**Issue by mkwork** [lightspark/lightspark#233]
Sorry if known issue.
For example, it doesn't working on http://www.osflv.com/Demonstration.html.
Adobe flash player show menu corectly.

**Comment by eiglow** [comment]
That site doesn't seem to exist anymore

**Comment by dbluelle** [comment]
Lightspark currently doesn't implement any support for context menus at all.
I've not yet figured out a way to create context menus without adding an additional dependency for one of the heavier toolkits (gtk/Qt), which I want to avoid if possible.

**Comment by dbluelle** [comment]
support for context menus is now implemented, so I'm closing this.
