### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by rchl** [lightspark/lightspark#234]
I'm from Opera Software. We see a lot of crashes being reported by users using Lightspark on Windows XP. We can reproduce them locally.

Same crash can be reproduced on Chrome if bundled flash is disabled.

We will probably have to block Lightspark for the time being (at least the current version).

Example stack:

```
>libspark.dll::144ddd0      
 libspark.dll::1802f        
 libspark.dll::8cf5     
 libspark.dll::17acc40      
 libspark.dll::1e7498c      
 libspark.dll::1e749cc      
 libspark.dll::1e916e8      
 libspark.dll::17ac740      
 libspark.dll::1e92000      
 libspark.dll::17ac740      
 libspark.dll::17acc40      
 libspark.dll::17ad2b0      
 libspark.dll::17ad2a0      
 webkit::npapi::PluginInstance::NPP_SetWindow       
 webkit::npapi::WebPluginDelegateImpl::DestroyInstance      
 webkit::npapi::WebPluginDelegateImpl       
 webkit::npapi::WebPluginDelegateImpl       
 webkit::npapi::WebPluginDelegateImpl::PluginDestroyed
```

libspark.dll                                                              Base: 6CBC0000 Size: 02C42000 Timestamp: 4ED7B08C
nplightsparkplugin.dll     1, 0, 0, 1                                     Base: 64240000 Size: 000B5000 Timestamp: 4ED7B0E0

**Comment by yueyihua** [comment]
@rchl, when i build windows version in Ubuntu16.04, a link error happened:
[  5%] Linking CXX shared library ../Debug/bin/libspark.dll
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x418): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x898): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xd38): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xf38): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x1828): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x1d88): more undefined references to `_imp__wglGetProcAddress@4' follow
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x8e3c): undefined reference to `glGetString@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x8ea0): undefined reference to `_imp__wglGetCurrentDC@0'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x8f09): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0x8f3f): undefined reference to `_imp__wglGetCurrentDC@0'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xa91f): undefined reference to `glGetString@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xaa54): undefined reference to `glGetString@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xaa92): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xab9e): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xac76): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xacfc): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xad67): undefined reference to `_imp__wglGetProcAddress@4'
/home/sp/work/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.4.0/../../../../i686-w64-mingw32.static/lib/../lib/libGLEW.a(glew.o):glew.c:(.text+0xad80): more undefined references to `_imp__wglGetProcAddress@4' follow
collect2: error: ld returned 1 exit status
src/CMakeFiles/spark.dir/build.make:3273: recipe for target 'Debug/bin/libspark.dll' failed
make[2]: *** [Debug/bin/libspark.dll] Error 1
CMakeFiles/Makefile2:205: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

How to resolve this problem? 
thank you!

**Comment by dbluelle** [comment]
see https://github.com/lightspark/lightspark/issues/288
