### ISSUE TITLE
Audio decoding doesn't build without ffmpeg

### ISSUE THREAD

**Issue by SuperHeron** [lightspark/lightspark#236]
When compiling lightspark without ffmpeg/libavcodec, I get this error:
[ 60%] Building CXX object src/CMakeFiles/spark.dir/scripting/flash/media/flashmedia.cpp.o
cd /var/tmp/paludis/build/net-plugins-lightspark-scm/work/build/src && /usr/bin/x86_64-pc-linux-gnu-g++   -DAUDIO_BACKEND=\"pulseaudio\" -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DENABLE_CURL -DENABLE_RTMP -DGNASH_PATH=\"/usr/bin/gnash\" -DHAVE_ATOMIC -DHAVE_IR_DATALAYOUT_H -DHAVE_NEW_GLIBMM_THREAD_API -DHAVE_SUPPORT_TARGETSELECT_H -DLLVM_31 -DLS_DATADIR=\"/usr/share/lightspark\" -DPRIVATELIBDIR=\"/usr/lib64/lightspark\" -Dspark_EXPORTS -O3 -march=native -mtune=native -pipe -Wall -Wnon-virtual-dtor -Woverloaded-virtual -pipe -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wdisabled-optimization -Wextra -Wno-unused-parameter -Wno-invalid-offsetof -fPIC -I/var/tmp/paludis/build/net-plugins-lightspark-scm/work/build -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/include/freetype2 -I/usr/include/libxml++-2.6 -I/usr/lib64/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng15 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src -I/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting    -o CMakeFiles/spark.dir/scripting/flash/media/flashmedia.cpp.o -c /var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp: In member function 'void lightspark::SoundChannel::playRaw()':
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp:536:2: error: 'FFMpegAudioDecoder' was not declared in this scope
  FFMpegAudioDecoder _decoder = new FFMpegAudioDecoder(format.codec,
  ^
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp:536:22: error: 'decoder' was not declared in this scope
  FFMpegAudioDecoder *decoder = new FFMpegAudioDecoder(format.codec,
                      ^
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp:536:36: error: expected type-specifier before 'FFMpegAudioDecoder'
  FFMpegAudioDecoder *decoder = new FFMpegAudioDecoder(format.codec,
                                    ^
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp:536:36: error: expected ';' before 'FFMpegAudioDecoder'
/var/tmp/paludis/build/net-plugins-lightspark-scm/work/lightspark-scm/src/scripting/flash/media/flashmedia.cpp:561:9: error: type '<type error>' argument given to 'delete', expected pointer
  delete decoder;
         ^
make[2]: *_\* [src/CMakeFiles/spark.dir/scripting/flash/media/flashmedia.cpp.o] Error 1

**Comment by eiglow** [comment]
Is this a bug? libavcodec is a dependency, and it is expected for compilation to fail when missing a dependency.

**Comment by dbluelle** [comment]
closing this as you can just use `-DENABLE_LIBAVCODEC=OFF` to build lightspark without ffmpeg dependency
