### ISSUE TITLE
Installed through RPM incorrectly links to libavcodec

### ISSUE THREAD

**Issue by wvxvw** [lightspark/lightspark#238]
After installing lightspark from RPM Fusion and trying to run it I get this error:

``` sh
$ lightspark --help
lightspark: symbol lookup error: /lib64/libavcodec.so.54: undefined symbol: vpx_codec_vp9_dx_algo
```

I'll try to build it to see if I can do anything about linking, but this is the behavior of both the official repo version and fusion version.

PS. Yes, I could build the project on FC-19 and it loaded fine. So this must be only the problem in the version currently in the repo.

**Comment by leigh123linux** [comment]
I see no bug report

https://bugzilla.rpmfusion.org/buglist.cgi?quicksearch=lightspark&list_id=7512

And if the issue was with F19 it is now EOL so please close this issue.

**Comment by ousia** [comment]
@wvxvw, does this issue still apply with latest released version?

**Comment by eiglow** [comment]
Just tested it, this issue does no longer occur. `lightspark -v` on lightspark installed from rpmfusion-free gives normal output and no errors.

**Comment by dbluelle** [comment]
I think it's safe to close this issue.
Feel free to open a new one if the problem still exists.
