### ISSUE TITLE
Build Against Newer Versions Of LLVM

### ISSUE THREAD

**Issue by ldo** [lightspark/lightspark#251]
Your check for suitable versions of LLVM doesn’t go high enough. Here is an updated check:

    diff --git a/conf/FindLLVM.cmake b/conf/FindLLVM.cmake
    index 51b776c..e60dd4a 100644
    --- a/conf/FindLLVM.cmake
    +++ b/conf/FindLLVM.cmake
    @@ -54,6 +54,9 @@ else (LLVM_INCLUDE_DIR)
         /usr/lib/llvm-3.1/bin
         /usr/lib/llvm-3.2/bin
         /usr/lib/llvm-3.3/bin
    +    /usr/lib/llvm-3.4/bin
    +    /usr/lib/llvm-3.5/bin
    +    /usr/lib/llvm-3.6/bin
         )

       find_program(LLVM_GCC_EXECUTABLE

**Comment by aajanki** [comment]
Thanks for the patch, merged.
