### ISSUE TITLE
During linking: rendering_context.cpp:(.text+0xa23): undefined reference to `__glewUniformMatrix4fv'

### ISSUE THREAD

**Issue by jvme38** [lightspark/lightspark#253]
Hi,

I've taken a git clone from https://github.com/lightspark/lightspark.git, today.

I got the following linking error:

...
CMakeFiles/spark.dir/backends/rendering_context.cpp.o: In function `lightspark::GLRenderContext::setMatrixUniform(lightspark::GLRenderContext::LSGL_MATRIX) const':
rendering_context.cpp:(.text+0xa23): undefined reference to`__glewUniformMatrix4fv'
collect2: error: ld returned 1 exit status
src/CMakeFiles/spark.dir/build.make:2954: recipe for target 'x86_64/Release/lib/liblightspark.so.0.7.2' failed
make[2]: **\* [x86_64/Release/lib/liblightspark.so.0.7.2] Error 1
CMakeFiles/Makefile2:154: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: **\* [src/CMakeFiles/spark.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2
jvme@debian-8:~/Downloads/lightspark$ 

Is this a known problem?

Regards from Belgium,

Ing. Johan Vermeire

**Comment by dbluelle** [comment]
Hmm, there seems to be something wrong with your libglew installation.
Does cmake correctly find libglew?
can you post your cmake command line and the cmake output?
