### ISSUE TITLE
Version 0.8

### ISSUE THREAD

**Issue by dbluelle** [lightspark/lightspark#254]
I was asked by a Debian maintainer if we could do a new release.
As I have never done such a thing, how do we do that?
Is it enough to just follow https://github.com/lightspark/lightspark/blob/master/RELEASING 
without the launchpad stuff?

**Comment by mgehre** [comment]
Yes, as far as I understand.

dbluelle <notifications@github.com> schrieb am So., 12. Juli 2015 11:12:

**Comment by PaddyMac** [comment]
I hate to hijack a thread, but I haven't a clue where else to find out. I have tried to follow Lightspark development for several years now, but it seemed for a while that Lightspark development had completely stopped...or at least nearly stopped. Is the Launchpad page for Lightspark still relevant? What is the best way for users such as myself to follow the project and communicate with developers? And how much of a donation incentive would it take to have you fix a 5-year old bug?

**Comment by dbluelle** [comment]
Well it seems I'm the only one who is currently working on lightspark...
I'm not active on Launchpad, so the best way would be to open issues here.
What is that 5-year old bug?
(I'm only working on lightspark as a hobby, so don't expect too much...)

**Comment by PaddyMac** [comment]
This one: https://bugs.launchpad.net/lightspark/+bug/623628 Of course, I realize that by now, non-SSE2 processors are going the way of the dinosaur, but it would be nice if it was still doable.

**Comment by dbluelle** [comment]
Hmm, I think that's because of the assembler optimized stuff.
To test that, you can try to replace lines 145-153 from src/CMakeLists.txt:
```
  IF(${i386})
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/fastpaths_x86.cpp)
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/fastpaths_i686.asm)
  ELSEIF(${x86_64})
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/fastpaths_x86.cpp)
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/fastpaths_amd64.asm)
  ELSE()
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/slowpaths_generic.cpp)
  ENDIF(${i386})
```
 with 
```
    SET(LIBSPARK_SOURCES ${LIBSPARK_SOURCES} platforms/slowpaths_generic.cpp)
```

**Comment by alexp-sssup** [comment]
Hello everyone,

first of all I need to apologize for not having paid attention to the Ligthspark project for the last three years or so. As the official maintainer of the project it was my duty, but I have failed it.

A big thanks goes to the member of the community that kept the project alive during this time. Thank you guys.

It's past time for me to step down as Lightspark's maintainer and pass this role to someone how is willing to actively steward the project. I will make sure that the new maintainer has all required permissions to access everything related to the project. My minor contribution to the project will be to keep paying for the domain lightspark.org indefinitely.

I had a lot of fun working on Lightspark, and it's something that I truly miss every now and then. In the last few years it has become clear that Flash is going the way of the dodo. But there is a huge amount of content authored using Flash on the Web and as Flash will be abandoned by the industry Lightspark and Gnash will be increasingly important to preserve the existing content.

My hope is that an existing member of the community will step up to officially take the maintainer role. Please let me know. Thanks again.

**Comment by PaddyMac** [comment]
It appears that Gnash has died quietly without anyone noticing. gnashdev.org appears to be gone, and the gnash git repository appears to be empty. Lightspark and Mozilla's Shumway project appear to be the only ongoing open source flash projects. Google's version of Flash only works in Chrome and is proprietary per a non-disclosure agreement with Adobe. I personally find this strange considering that even Adobe is now trying to kill Flash by promoting HTML 5. That aside, I wish I had the knowledge necessary to lead this project. The fact is that I don't. But I'm sure there is someone willing and also able if you but look for a protege.

**Comment by ethus3h** [comment]
This can be closed as fixed now, mm? :D
