### ISSUE TITLE
Build issue with new llvm 3.7.0

### ISSUE THREAD

**Issue by david-geiger** [lightspark/lightspark#258]
Hi,

Trying to build lightspark (tarball created with commit 87e38d55fbf6f818cf77c1019efffa5909c5f2fc ) against llvm 3.7.0 , but I get:

http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20150923053817.daviddavid.valstar.14357/log/lightspark-0.7.2-22.git20150823.2.mga6/build.0.20150923053903.log

That with the same tarball had sucessfully built against llvm 3.6.2.

**Comment by jobermayr** [comment]
https://github.com/jobermayr/lightspark/commit/1376bd6

**Comment by dbluelle** [comment]
fixed through merging of PR https://github.com/lightspark/lightspark/pull/256
