### ISSUE TITLE
Slackwave Flash has crashed. Chromium 22.0.1229.94 and Shockwave Flash 12.1 r601

### ISSUE THREAD

**Issue by krll-k** [lightspark/lightspark#260]
<a href="http://www.zimagez.com/zimage/screenshot-251015-212612.php">
  <img src="http://www.zimagez.com/miniature/screenshot-251015-212612.php" />
</a>
<a href="http://www.zimagez.com/zimage/screenshot-251015-213347.php">
  <img src="http://www.zimagez.com/miniature/screenshot-251015-213347.php" />
</a>

**Comment by eiglow** [comment]
perhaps this issue can be closed, unless OP can still reproduce the issue?

**Comment by dbluelle** [comment]
feel free to eropen this issue, if it is reproducible
