### ISSUE TITLE
cmake man location build option

### ISSUE THREAD

**Issue by orbea** [lightspark/lightspark#262]
Can you please add a build option with cmake for the man page install location?
By default they will be isntalled in `usr/share/man/man1/lightspark.1` which is fine with many distros, but some distros like Slackware install man pages in other locations such as `usr/man/`.  I can just manually move them in my build script, but I would appreciate if I could install them in the correct location with cmake. Thanks!

**Comment by orbea** [comment]
Thanks! My only suggestion is that maybe its best to leave `man1` out of the cmake variable as that should not change between unix systems?

**Comment by dbluelle** [comment]
Yes you're right, I've corrected that.
