### ISSUE TITLE
lightspark doesn't built against new llvm 3.8.0

### ISSUE THREAD

**Issue by david-geiger** [lightspark/lightspark#263]
Hello,

llvm 3.8.0 is now out and we can't compile anymore lightspark against it on Mageia Cauldron:

/home/iurt/rpmbuild/BUILD/lightspark-9e5f3db11e53a1126c32720dda3f5ac7733083de/src/scripting/abc_codesynt.cpp: In member function 'void lightspark::ABCVm::registerFunctions()':
/home/iurt/rpmbuild/BUILD/lightspark-9e5f3db11e53a1126c32720dda3f5ac7733083de/src/scripting/abc_codesynt.cpp:298:30: error: base operand of '->' has non-pointer type 'const llvm::DataLayout'
  ptr_type=ex->getDataLayout()->getIntPtrType(llvm_context());
                              ^
/home/iurt/rpmbuild/BUILD/lightspark-9e5f3db11e53a1126c32720dda3f5ac7733083de/src/scripting/abc_codesynt.cpp: In member function 'lightspark::ASObject* (* lightspark::method_info::synt_method())(lightspark::call_context*)':
/home/iurt/rpmbuild/BUILD/lightspark-9e5f3db11e53a1126c32720dda3f5ac7733083de/src/scripting/abc_codesynt.cpp:1888:23: error: cannot convert 'llvm::iplist<llvm::Argument, llvm::SymbolTableListTraits<llvm::Argument> >::iterator {aka llvm::ilist_iterator<llvm::Argument>}' to 'llvm::Value*' in initialization
  llvm::Value* context=it;
                       ^
src/CMakeFiles/spark.dir/build.make:1001: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc_codesynt.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc_codesynt.cpp.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/lightspark-9e5f3db11e53a1126c32720dda3f5ac7733083de/build'
make[2]: *** Waiting for unfinished jobs....

Regards,
David

**Comment by orbea** [comment]
Yep, same problem here in slackware64-current.
```
[ 35%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc_optimizer.cpp.o
/tmp/SBo/lightspark/src/scripting/abc.cpp: In member function ‘lightspark::tiny_string lightspark::ABCVm::getDefaultXMLNamespace()’:
/tmp/SBo/lightspark/src/scripting/abc.cpp:1913:52: warning: converting to non-pointer type ‘long int’ from NULL [-Wconversion-null]
  return currentCallContext->defaultNamespaceUri == NULL ? tiny_string() : currentCallContext->defaultNamespaceUri->data;
                                                    ^
[ 35%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc_opcodes.cpp.o
/tmp/SBo/lightspark/src/scripting/abc_codesynt.cpp: In member function ‘void lightspark::ABCVm::registerFunctions()’:
/tmp/SBo/lightspark/src/scripting/abc_codesynt.cpp:298:30: error: base operand of ‘->’ has non-pointer type ‘const llvm::DataLayout’
  ptr_type=ex->getDataLayout()->getIntPtrType(llvm_context());
                              ^
/tmp/SBo/lightspark/src/scripting/abc_codesynt.cpp: In member function ‘lightspark::ASObject* (* lightspark::method_info::synt_method())(lightspark::call_context*)’:
/tmp/SBo/lightspark/src/scripting/abc_codesynt.cpp:1888:23: error: cannot convert ‘llvm::iplist<llvm::Argument, llvm::SymbolTableListTraits<llvm::Argument> >::iterator {aka llvm::ilist_iterator<llvm::Argument>}’ to ‘llvm::Value*’ in initialization
  llvm::Value* context=it;
                       ^
[ 36%] Building CXX object src/CMakeFiles/spark.dir/scripting/abctypes.cpp.o
[ 37%] Building CXX object src/CMakeFiles/spark.dir/scripting/flash/accessibility/flashaccessibility.cpp.o
src/CMakeFiles/spark.dir/build.make:998: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc_codesynt.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc_codesynt.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:205: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by david-geiger** [comment]
Hi,

Any comment about this issue? :(

**Comment by dbluelle** [comment]
I will take a look at this once llvm 3.8 is available in Archlinux.

**Comment by david-geiger** [comment]
Hi,

No news? still no llvm 3.8 in Archlinux? :)

**Comment by david-geiger** [comment]
Nice! it built again now!

Thank you very much dbluelle :+1:
