### ISSUE TITLE
FTBFS due to broken include path generation

### ISSUE THREAD

**Issue by gordan-bobic** [lightspark/lightspark#264]
/usr/bin/cmake -E cmake_progress_report /home/mock/rpmbuild/BUILD/lightspark-0.7.2/CMakeFiles 15
[ 12%] Building CXX object src/CMakeFiles/spark.dir/tiny_string.cpp.o
cd /home/mock/rpmbuild/BUILD/lightspark-0.7.2/src && /bin/c++   -DAUDIO_BACKEND=\"pulse\" -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DENABLE_CURL -DENABLE_LIBAVCODEC -DENABLE_RTMP -DGNASH_PATH=\"/usr/bin/gnash\" -DHAVE_ATOMIC -DHAVE_AVCODEC_ALLOC_CONTEXT3 -DHAVE_AVCODEC_DECODE_AUDIO3 -DHAVE_AVCODEC_DECODE_AUDIO4 -DHAVE_AVCODEC_DECODE_VIDEO2 -DHAVE_AVCODEC_OPEN2 -DHAVE_AVFORMAT_CLOSE_INPUT -DHAVE_AVFORMAT_FIND_STREAM_INFO -DHAVE_AVIO_ALLOC_CONTEXT -DHAVE_AV_FRAME_ALLOC -DHAVE_AV_FRAME_UNREF -DHAVE_IR_DATALAYOUT_H -DHAVE_LIBAVRESAMPLE -DHAVE_NEW_GLIBMM_THREAD_API -DHAVE_PASSMANAGER_H -DHAVE_SUPPORT_TARGETSELECT_H -DLLVM_31 -DLLVM_34 -DLLVM_35 -DLS_DATADIR=\"/usr/share/lightspark\" -DPRIVATELIBDIR=\"/usr/lib64/lightspark\" -Dspark_EXPORTS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wall -Wnon-virtual-dtor -Woverloaded-virtual -pipe -fvisibility=hidden -fvisibility-inlines-hidden -std=c++11 -Wdisabled-optimization -Wextra -Wno-unused-parameter -Wno-invalid-offsetof -O2 -DNDEBUG -fPIC -I/home/mock/rpmbuild/BUILD/lightspark-0.7.2 -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng15 -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I"/usr/include/ffmpeg /usr/include/ffmpeg" -I/home/mock/rpmbuild/BUILD/lightspark-0.7.2/src -I/home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/scripting    -o CMakeFiles/spark.dir/tiny_string.cpp.o -c /home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/tiny_string.cpp
In file included from /home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/scripting/flash/net/flashnet.h:29:0,
                 from /home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/swf.h:32,
                 from /home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/timer.cpp:20:
/home/mock/rpmbuild/BUILD/lightspark-0.7.2/src/backends/decoder.h:29:32: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>

Note this part in the invocation above:
-I"/usr/include/ffmpeg /usr/include/ffmpeg"

**Comment by dbluelle** [comment]
It seems that cmake doesn't properly detect ffmpeg.

can you post the output of cmake?

**Comment by dbluelle** [comment]
fixed by https://github.com/lightspark/lightspark/pull/273
