### ISSUE TITLE
Switch to GTK3

### ISSUE THREAD

**Issue by shmerl** [lightspark/lightspark#266]
Firefox recently started using GTK3, and in general things are moving toward Wayland, so GTK2 is becoming increasingly obsolete.

Do you plan to switch Lightspark to GTK3?

**Comment by dbluelle** [comment]
If I understand http://emilio.pozuelo.org/posts/75 correctly, npapi plugins are still expected to use gtk2
(At least the adobe flash plugin seems to use gtk2) .
I've never done anything with gtk, so I would rather switch completely from gtk to sdl2,
but I don't know how much work that will be.
Switching to SDL2 would also have the benefit of getting rid of the different audio plugins and just use sdl2_mixer as the audio backend on all systems.
But I'm open to suggestions...

**Comment by Df458** [comment]
It looks like there was an attempt to switch to GTK3 a few years ago (#175), from the looks of it. Switching over to use SDL sounds interesting. I might try to play around with it in my spare time, though I can't really make any guarantees.

**Comment by dbluelle** [comment]
I've implemented most of the switch to SDL2 (standalone fully works), but I've hit a blocker with the firefox plugin:
I don't know how to create an SDL window that is a subwindow of the window provided by the browser.
You can use SDL_CreateWindowFrom() to create a window, but it seems to be impossible to create an openGL context inside this window... (error "The specified window isn't an OpenGL window")
There is the hint SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT, but this is apparently only handled on Windows :(
I've also found http://forums.libsdl.org/viewtopic.php?t=9247 which would mean patching SDL2 and shipping our own version of SDL2...
So does anybody have an idea how to fix this?

**Comment by dbluelle** [comment]
OK, the switch to SDL2 is now done.
Unfortunately the firefox plugin still needs GTK2, I've found no way to get around that dependency :( .
