### ISSUE TITLE
Sound gets distorted when .swf file loops

### ISSUE THREAD

**Issue by DavidGriffith** [lightspark/lightspark#267]
When this music video loops back to the beginning, the audio is distorted  This doesn't happen with Adobe Flash.

http://www.albinoblacksheep.com/flash/ekkosangen

**Comment by dbluelle** [comment]
the swf file is of version 6 which is not handled by lightspark.
Lightspark automatically starts gnash to handle swf files of version 8 and lower,
so please report this issue to the gnash developers.

**Comment by DavidGriffith** [comment]
Here's the bug reported on the Gnash project page: https://savannah.gnu.org/bugs/index.php?48052
