### ISSUE TITLE
Jump outside DoAction tag implementation missing

### ISSUE THREAD

**Issue by lbssousa** [lightspark/lightspark#274]
This is an historical bug related to Gnash, and I'm not sure whether Lightspark should address it, but several SWF games fail to run properly on Gnash/Lightspark, echoing the following message:

```
UNIMPLEMENTED: Jump outside DoAction tag requested (offset 16 before tag start)
```

Original Gnash bug reports:
- http://savannah.gnu.org/bugs/?25132
- http://savannah.gnu.org/bugs/?40466
- http://savannah.gnu.org/bugs/?38733

Original Gnash open task: http://savannah.gnu.org/task/?12927

**Comment by dbluelle** [comment]
speetest.net has a newer app that is using AVM2, so it is not affected by the gnash bug anymore (but it gets in an endless loop somewhere, so that's another bug...  )
The flash8/AVM1 games mentioned in the bug reports are gnash-only, so no lightspark bug.

**Comment by dbluelle** [comment]
The endless loop issue is now fixed, so I close this
