### ISSUE TITLE
Recipe for target 'cmake_check_build_system' failed

### ISSUE THREAD

**Issue by ethus3h** [lightspark/lightspark#275]
Hi! I'm not sure if this is a bug or something wrong with my setup (dependencies or something), but I'm having this problem when I try to build Lightspark: https://gist.github.com/ethus3h/d497bdd8ca390312832073020b430eff

I would greatly appreciate any help resolving this! Thank you! :)

**Comment by dbluelle** [comment]
Hmm, can't reproduce that, but something went wrong with cmake...
I'm not very familiar with cmake, but please post the contents of
/home/kyan/lightspark/obj/CMakeCache.txt
/home/kyan/lightspark/obj/CMakeFiles/CMakeOutput.log
/home/kyan/lightspark/obj/CMakeFiles/CMakeError.log
maybe we can find something in those files...

**Comment by ethus3h** [comment]
CMakeCache.txt: https://gist.github.com/ethus3h/0deb22f7c0c48fb65badca80e216a6ee
CMakeOutput.log: https://gist.github.com/ethus3h/29d40dbb9fee87de9cbbeb38f7dba40c
CMakeError.log: https://gist.github.com/ethus3h/a7cdd099adbbf7cb506b3016c5d453ba

Thanks! :)

**Comment by dbluelle** [comment]
Hmm, it seems that your llvm-config produces an additional newline for the core-libs (see https://gist.github.com/ethus3h/d497bdd8ca390312832073020b430eff line 43) .
Whats the output of 
```
/usr/bin/llvm-config --libs core ipa ipo instrumentation bitreader bitwriter linker
```
in a terminal?
You can also try the following patch, maybe that already fixes it:
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -100,6 +100,7 @@ else (LLVM_INCLUDE_DIR)
 
   MACRO(FIND_LLVM_LIBS LLVM_CONFIG_EXECUTABLE _libname_ LIB_VAR OBJECT_VAR)
     exec_program( ${LLVM_CONFIG_EXECUTABLE} ARGS --libs ${_libname_}  OUTPUT_VARIABLE ${LIB_VAR} )
+    string(REPLACE "\n" " " ${LIB_VAR} ${${LIB_VAR}})
     STRING(REGEX MATCHALL "[^ ]*[.]o[ $]"  ${OBJECT_VAR} ${${LIB_VAR}})
     SEPARATE_ARGUMENTS(${OBJECT_VAR})
     STRING(REGEX REPLACE "[^ ]*[.]o[ $]" ""  ${LIB_VAR} ${${LIB_VAR}})
```

**Comment by ethus3h** [comment]
Thank you! I'm afraid it still didn't seem to work. :( Here's my:

llvm-config output: https://gist.github.com/ethus3h/bc86ea7c02f6d1a0292798d8f12f58eb

Results when building with that patch: https://gist.github.com/ethus3h/4c4e2d229eb8a9459f9c36a82897924f

**Comment by dbluelle** [comment]
Hmm, llvm-config output seems ok.
Please also post the output of 
```
/usr/bin/llvm-config --system-libs
```
What Distribution are you using and which version of cmake ?

Try the following patch:
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -170,6 +170,7 @@ else (LLVM_INCLUDE_DIR)
     FIND_LLVM_LIBS( ${LLVM_CONFIG_EXECUTABLE} "core ipa ipo instrumentation bitreader bitwriter linker" LLVM_LIBS_CORE_ONLY LLVM_LIBS_CORE_OBJECTS )
   ENDIF(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
   SET(LLVM_LIBS_CORE ${LLVM_LIBS_CORE_ONLY} ${LLVM_SYSTEM_LIBS})
+  STRING(REPLACE "\n" " " ${LLVM_LIBS_CORE} ${${LLVM_LIBS_CORE}})
   UNSET(LLVM_LIBS_CORE_ONLY)
   UNSET(LLVM_SYSTEM_LIBS_FAILED)
   MESSAGE(STATUS "LLVM core libs: " ${LLVM_LIBS_CORE})
```

**Comment by ethus3h** [comment]
The output of /usr/bin/llvm-config --system-libs is a newline.

Here's the result of building with the suggested patch: https://gist.github.com/ethus3h/07ff11783f958a28385bad040f6e773b

**Comment by ethus3h** [comment]
Oh, sorry, I'm using Gentoo with cmake 3.5.2-r1 (I think the -r1 is a Gentoo-specific revision of the package).

**Comment by ethus3h** [comment]
If it's any help, these are the USE flags I have cmake built with:

```
kyan@elegiac ~/4/lightspark/obj nohup compiz --replace openbox $ equery u cmake
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for dev-util/cmake-3.5.2-r1:
 U I
 - - doc            : Add extra documentation (API, Javadoc, etc). It is
                      recommended to enable per package instead of globally
 - - emacs          : Add support for GNU Emacs
 + + ncurses        : Add ncurses support (console display library)
 + + qt5            : Add support for the Qt 5 application and UI framework
 - - system-jsoncpp : Use system copy of dev-libs/jsoncpp instead of bundled
                      one.
 - - test           : Workaround to pull in packages needed to run with
                      FEATURES=test. Portage-2.1.2 handles this internally, so
                      don't set it in make.conf/package.use anymore
kyan@elegiac ~/4/lightspark/obj nohup compiz --replace openbox $ 
```

Thanks! :)

**Comment by dbluelle** [comment]
> The output of /usr/bin/llvm-config --system-libs is a newline.

Okay, I think this is what causes the problem.

The previous patch should have already fixed this, but I made a mistake :roll_eyes: 
So try this one: 
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -169,6 +169,7 @@ else (LLVM_INCLUDE_DIR)
   ELSE(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
     FIND_LLVM_LIBS( ${LLVM_CONFIG_EXECUTABLE} "core ipa ipo instrumentation bitreader bitwriter linker" LLVM_LIBS_CORE_ONLY LLVM_LIBS_CORE_OBJECTS )
   ENDIF(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
+  STRING(REPLACE "\n" " " ${LLVM_SYSTEM_LIBS} ${${LLVM_SYSTEM_LIBS}})
   SET(LLVM_LIBS_CORE ${LLVM_LIBS_CORE_ONLY} ${LLVM_SYSTEM_LIBS})
   UNSET(LLVM_LIBS_CORE_ONLY)
   UNSET(LLVM_SYSTEM_LIBS_FAILED)
```

**Comment by ethus3h** [comment]
I'm afraid it's still not working, but it's giving a different error now: https://gist.github.com/ethus3h/823485cc9aa2bcf4a9727968838f5c21

I think  libavcodec is part of ffmpeg, and I have ffmpeg installed, so I'm not sure what this is about… Thank you for your help and patience :)

**Comment by dbluelle** [comment]
ffmpeg is properly detected, it's just not the newest version, but that's no problem.
The real problem is still the newline in llvm.
I've modified my patch, please try this one:
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -169,6 +169,7 @@ else (LLVM_INCLUDE_DIR)
   ELSE(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
     FIND_LLVM_LIBS( ${LLVM_CONFIG_EXECUTABLE} "core ipa ipo instrumentation bitreader bitwriter linker" LLVM_LIBS_CORE_ONLY LLVM_LIBS_CORE_OBJECTS )
   ENDIF(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
+  STRING(REPLACE "\n" " " LLVM_SYSTEM_LIBS "${LLVM_SYSTEM_LIBS}")
   SET(LLVM_LIBS_CORE ${LLVM_LIBS_CORE_ONLY} ${LLVM_SYSTEM_LIBS})
   UNSET(LLVM_LIBS_CORE_ONLY)
   UNSET(LLVM_SYSTEM_LIBS_FAILED)
```

**Comment by ethus3h** [comment]
Thanks! It's a different error now, and gets 93% done: `ld: cannot find -l-lLLVMX86Disassembler`.

https://gist.github.com/ethus3h/a4fcc93ae403444ae20ecfb69355faa4

I also tried with adding `STRING(REPLACE "-l-l" "-l" LLVM_SYSTEM_LIBS "${LLVM_SYSTEM_LIBS}")` too, but that didn't work either… Sorry for the trouble. Thanks! :)

**Comment by dbluelle** [comment]
Okay, it seems that replacing newlines with spaces does not really fix the problem.
Maybe stripping whitespaces helps:
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -169,6 +169,7 @@ else (LLVM_INCLUDE_DIR)
   ELSE(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
     FIND_LLVM_LIBS( ${LLVM_CONFIG_EXECUTABLE} "core ipa ipo instrumentation bitreader bitwriter linker" LLVM_LIBS_CORE_ONLY LLVM_LIBS_CORE_OBJECTS )
   ENDIF(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
+  STRING(STRIP LLVM_SYSTEM_LIBS "${LLVM_SYSTEM_LIBS}")
   SET(LLVM_LIBS_CORE ${LLVM_LIBS_CORE_ONLY} ${LLVM_SYSTEM_LIBS})
   UNSET(LLVM_LIBS_CORE_ONLY)
   UNSET(LLVM_SYSTEM_LIBS_FAILED)
```

**Comment by ethus3h** [comment]
I'm afraid that didn't work either. Sorry. https://gist.github.com/ethus3h/f3d920ef08b987b333f8dff6affc9270

**Comment by ethus3h** [comment]
Oops, the relevant part starts here, sorry. https://gist.github.com/ethus3h/f3d920ef08b987b333f8dff6affc9270#file-gistfile1-txt-L425

**Comment by dbluelle** [comment]
It seems that I still do not really understand how cmake works... :wink: 
OK, next try:
```
--- conf/FindLLVM.cmake
+++ conf/FindLLVM.cmake
@@ -169,6 +169,8 @@ else (LLVM_INCLUDE_DIR)
   ELSE(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
     FIND_LLVM_LIBS( ${LLVM_CONFIG_EXECUTABLE} "core ipa ipo instrumentation bitreader bitwriter linker" LLVM_LIBS_CORE_ONLY LLVM_LIBS_CORE_OBJECTS )
   ENDIF(${LLVM_STRING_VERSION} VERSION_GREATER 3.7)
+  STRING(REPLACE "\n" " " LLVM_SYSTEM_LIBS "${LLVM_SYSTEM_LIBS}")
+  STRING(STRIP ${LLVM_SYSTEM_LIBS} LLVM_SYSTEM_LIBS)
   SET(LLVM_LIBS_CORE ${LLVM_LIBS_CORE_ONLY} ${LLVM_SYSTEM_LIBS})
   UNSET(LLVM_LIBS_CORE_ONLY)
   UNSET(LLVM_SYSTEM_LIBS_FAILED)
```

**Comment by ethus3h** [comment]
That fixed it, hooray! :D Thank you for your help and patience! :)
