### ISSUE TITLE
Cannot run swf which is built by crossbridge [flascc]

### ISSUE THREAD

**Issue by leiwen83** [lightspark/lightspark#280]
I use lightspark to play the sample swf created by crossbridge, and it crashed. Does it mean lightspark current don't support flascc?

INFO: Lightspark version 0.7.2-613-g308241e Copyright 2009-2013 Alessandro Pignotti and others
INFO: RenderThread this=0x7edb80
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 26
INFO: FrameRate 0.117188
INFO: Creating VM
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: Debugger enabled, reserved: 0, password: 
INFO: throwing exception:1065 Variable Telemetry is not defined.
    at Class/()
    at global/()
    at global/modAllocSects()
    at global/()

INFO: throwing exception:1065 Variable WorkerDomain is not defined.
    at global/()
    at global/()
    at Class/()
    at global/()
    at global/modAllocSects()
    at global/()

DefaultPreloader::initialize
INFO: throwing exception:1065 Variable HTTPBackingStore is not defined.
    at com.adobe.flascc.preloader::DefaultPreloader/initialize()
    at com.adobe.flascc.preloader::DefaultPreloader/()

INFO: Window resized to 800x600
INFO: FPS: 1 1
DefaultPreloader::onPreloaderComplete
Console::created

(process:16123): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: LS smart pointer: NULL pointer access

Trace/breakpoint trap (core dumped)

**Comment by dbluelle** [comment]
Do you have any links to examples of flash files created with crossbridge?
(All the links to examples on http://crossbridge.io/ are not working)
