### ISSUE TITLE
Super Smash Flash doesn't run in Lightspark

### ISSUE THREAD

**Issue by Oflameo** [lightspark/lightspark#282]
Package: browser-plugin-lightspark 
Version: 0.7.2-6
OS: Debian GNU/Linux 8 (jessie)

Here is the image of the specific error.
http://i.imgur.com/Kqn3UNW.png

**Comment by eiglow** [comment]
could you please provide a direct link to the swf? I wasn't able to easily grab the file off that site.

**Comment by eiglow** [comment]
Never mind, I found another instance of it at [here](http://www.mcleodgaming.com.gameslol.net/SSF2/1032/game.swf). Running it normally using lightspark version 0.8.1-273-g1bdb3108 standalone does not work; I attached [a log](https://github.com/lightspark/lightspark/files/3544426/ssf2-log.zip) but the following seems to be the most relevant part:
```
...
ERROR: not found:[ns:flash.net] GroupSpecifier
ERROR: not found:[ns:flash.net] GroupSpecifier
ERROR: not found:[ns:flash.net] GroupSpecifier
ERROR: Unhandled ActionScript exception in VM SecurityError: SecurityError: connect to local file
INFO: dynamic cast:SecurityError
ERROR: Unhandled ActionScript exception in VM SecurityError: SecurityError: connect to local file
    at com.mcleodgaming.ssf2.util::Resource/load()
    at Class/load()
    at com.mcleodgaming.ssf2::Main/onRootLoadComplete()

**Comment by dbluelle** [comment]
the swf downloads additional files, so you need to add the download url to the call:
`lightspark -u http://www.mcleodgaming.com.gameslol.net/SSF2/1032/  game.swf`
