### ISSUE TITLE
lightspark fails to build with llvm 4.0

### ISSUE THREAD

**Issue by xavierba** [lightspark/lightspark#284]
Hi,
A snapshot of lightspark taken a few days ago fails to build against llvm 4.0. The snapshot has code up to 2017-01-07 (commit 308241eb55c5379765033e60f28dfdd956c7abcd). I haven't tried to take a newer snapshot, nothing in the recent commits seems related.
(fwiw, this is the same snapshot as the one I'm using in the problem described in issue #283, but built against llvm 4.0 rather than 3.9)

Several headers files fail to be detected and so several defines are not set. The build then shocks later on a missing header that is searched in the wrong place due to the missing defines.

Here's an extract of the build log : 
-- LLVM llvm-config found at: /usr/bin/llvm-config
-- LLVM version: 4.0.0
-- LLVM CXX flags: -I/usr/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -fasynchronous-unwind-tables -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O2 -g -DNDEBUG  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM LD flags: -L/usr/lib
-- LLVM core libs: -lLLVM-4.0
-- LLVM JIT libs: -lLLVM-4.0
-- LLVM JIT objs: 
-- Looking for C++ include llvm/Support/TargetSelect.h
-- Looking for C++ include llvm/Support/TargetSelect.h - found
-- HAVE_SUPPORT_TARGETSELECT_H: 1
-- Looking for C++ include llvm/IRBuilder.h
-- Looking for C++ include llvm/IRBuilder.h - not found
-- HAVE_IRBUILDER_H: 
-- Looking for C++ include llvm/DataLayout.h
-- Looking for C++ include llvm/DataLayout.h - not found
-- Looking for C++ include llvm/IR/DataLayout.h
-- Looking for C++ include llvm/IR/DataLayout.h - not found
-- Looking for C++ include llvm/IR/Verifier.h
-- Looking for C++ include llvm/IR/Verifier.h - not found
-- Looking for C++ include llvm/PassManager.h
-- Looking for C++ include llvm/PassManager.h - not found
-- Looking for C++ include llvm/Transforms/Scalar/GVN.h
-- Looking for C++ include llvm/Transforms/Scalar/GVN.h - not found
-- HAVE_DATALAYOUT_H: 
-- HAVE_IR_DATALAYOUT_H: 
-- HAVE_IR_VERIFIER_H: 
-- HAVE_PASSMANAGER_H: 
-- HAVE_TRANSFORMS_SCALAR_GVN_H:

Full build log is available here : http://koji.rpmfusion.org/kojifiles/work/tasks/9378/99378/build.log

Regards,
Xavier

**Comment by dbluelle** [comment]
seems like the llvm guys have reorganized their interfaces once again ...
I will take a look at this when llvm4.0 hits ArchLinux

**Comment by orbea** [comment]
I can confirm this happens with the master as well.

**Comment by xavierba** [comment]
It works now, thanks :-)
