### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#285]
First of all thank you to the (only I think) developer who is contributing to lightspark. It is a pity Lightspark is not interesting for others, It is good that you are still contribute and hope you won't stop (afaik you are doing it in your spare time).

Even thought flash is dying it is still widespread and there will be a lot of legacy material online.

I saw another post where a new release is mentioned, but since 2 years have passed I decided to write here.

I am not a developer so I can't contribute to the development, but if a new release is done (possibly as deb or in the software center) I am happy to test and report bugs on my platform (ubuntu 16.04.02) or in a virtual machine (if that can be considered helpful) and hopefully we can make lightspark more stable and more compatible.

I would also be happy to update and extend the supported websites list (which is probably out-of date as 2017).

WP

**Comment by ethus3h** [comment]
FWIW, my interest in Lightspark is getting Realm of the Mad God (a computer game, http://www.realmofthemadgod.com/), and to a lesser extent Scratch 2 (a visual programming environment, https://github.com/lightspark/lightspark/issues/265) to work...

**Comment by ethus3h** [comment]
Ugh, I keep forgetting GitHub's JavaScript is broken so I can't post reactions or edit comments. Anyway, I'm basically in the same situation as you, with having an interest in developing it but not having the technical skills / time to learn them.

**Comment by WPFilmmaker** [comment]
Yes online games are a big chunk of the material that will probably never be converted to html5 especially those flashgames for casual people. Unfortunately seems that the interest in a free alternative to Flash is not strong (anymore), Gnash was removed from the FSF high priority projects list this year.. Anyway I made a list of the most popular videoplatforms I intend to test lightspark on. When a new version will be out and someone gives me the rights to edit the "supported sites list" I will be happy to give my small contribution.

**Comment by dbluelle** [comment]
I will have more time to work on lightspark in the upcoming weeks, so I plan to do a release sometime soon. 
As stated in the other thread, I don't have any knowledge how the ubuntu/launchpad stuff works (and I don't think I have the privileges to do any lightspark stuff on launchpad), so I will only do the neccessary steps here on github.
I just found out I have writing rights to the repository for the lightspark website (lightspark.github.com), so I can also update the website.

**Comment by WPFilmmaker** [comment]
Hi dbluelle, great news then!

Yes I had read the other thread I think working on github is no problem at all.

When  you (or someone else) releases a new version I am happy to test it and report bugs. Since you can also update the website I am happy to send you my test results once I experimented thoroughly (I am on Ubuntu 16.04). 

I already have a list of big websites I will test lightspark on :)

**Comment by dbluelle** [comment]
I'm planning on releasing version 0.8 next weekend.

Just for clarification: With "website" I meant https://lightspark.github.io, not the wiki ( https://github.com/lightspark/lightspark/wiki ) .
I think I don't have the permission to give anybody the right to edit the wiki pages, so maybe one of the original contributors can handle that...

**Comment by alexp-sssup** [comment]
@dbluelle You should have the required rights now

**Comment by WPFilmmaker** [comment]
Great! I am looking forward to it =)

**Comment by dbluelle** [comment]
Sorry, but I think we have to delay the release, because currently the firefox plugin doesn't work at all.
(I don't think it makes sense to make a release without a working firefox plugin) 
It seems that the firefox guys recently removed the support for windowed plugins 😞  , so we have to convert it to a windowless plugin...

**Comment by WPFilmmaker** [comment]
Oh :( bad news, hope it does not add too much work.

But yours is indeed a wise choice as most of the users are likely to be interested in a firefox plugin.

Again thank you for your hard work!

**Comment by yueyihua** [comment]
@dbluelle 

Firefox npapi plugin doesn't work at all. But the chrome ppapi plugin not work well too. Which browser i can use?

**Comment by ethus3h** [comment]
Most popular browsers are discontinuing and/or discouraging plugin support, I think (especially for plugins other than the ones shipped with the browser). Lightspark provides a standalone app similar to Adobe's standalone Flash player. Also, Firefox can still be compiled with NPAPI support as of version 52, I think, even though it's not included in the binary builds. Hope this helps!

**Comment by yueyihua** [comment]
My Firefox version is “Mozilla Firefox 54.0“, when use the naapi plugin, I can not play the video on Videolectures, I don't know why, can you help me?
![20170706093952](https://user-images.githubusercontent.com/10558846/27891909-27c1d01c-622f-11e7-99f5-89d899af1dbf.png)

**Comment by WPFilmmaker** [comment]
I am not a developer but videolectures is not in the list of supported sites, what I would do is wait until dbluelle releases a new version and try again. If it does not work report the issue.

**Comment by yueyihua** [comment]
@dbluelle 
When release new version? I can not play any flash video.

**Comment by dbluelle** [comment]
As long as the rendering problem in the plugin is not solved (see https://github.com/lightspark/lightspark/issues/290#issuecomment-313765219 ), it doesn't make much sense releasing a new version.

**Comment by dbluelle** [comment]
The Firefox plugin now works on Linux.
I've not tested the Windows version.

**Comment by yueyihua** [comment]
@dbluelle 
Did you really tested Firefox plugin in Linux? Which site have you tested? I tested the plugin fail.
Site Videolectures.net complain an error like this:
SWF file: http://static.videolectures.net/r.1483388978/common/swf/PlayerViidea.swf
ArgumentError: Error #1063: Argument count mismatch on robotlegs.bender.extensions.viewManager.impl::ViewManager. Expected 1, got 0.
    at org.swiftsuspenders.typedescriptions::NoParamsConstructorInjectionPoint/createInstance()
    at robotlegs.bender.framework.impl::RobotlegsInjector/instantiateUnmapped()
    at org.swiftsuspenders.dependencyproviders::SingletonProvider/createResponse()
    at org.swiftsuspenders.dependencyproviders::SingletonProvider/apply()
    at robotlegs.bender.framework.impl::RobotlegsInjector/getInstance()
    at robotlegs.bender.extensions.modularity::ModularityExtension/configureExistenceWatcher()
    at robotlegs.bender.extensions.modularity::ModularityExtension/handleContextView()
    at ObjectHandler/handle()
    at robotlegs.bender.framework.impl::ObjectProcessor/processObject()
    at robotlegs.bender.framework.impl::ConfigManager/addConfig()
    at robotlegs.bender.framework.impl::Context/configure()
    at com.viidea::PlayerApp/()
    at ViideaPlayer/init()
    at Preloader/init()
    at Preloader/onProgress()
![videolectures net_20170712094906](https://user-images.githubusercontent.com/10558846/28098440-d818bc92-66e8-11e7-9d38-219ee49ff6cb.png)

Site www.deraktionaer.tv complain a crash error  like this:
![www deraktionaer tv_20170712084505](https://user-images.githubusercontent.com/10558846/28098448-e3870390-66e8-11e7-9576-d5fb60617d99.png)

Why http://tv.sohu.com or http://www.youku.com doesn't work?

**Comment by ethus3h** [comment]
Looks like it's working to me, and just doesn't support those sites yet?

**Comment by yueyihua** [comment]
@ethus3h  But I played fail on Ubuntu linux, I don't know why. can you help me?

**Comment by WPFilmmaker** [comment]
@yueyihua try a website in this list https://github.com/lightspark/lightspark/wiki/Site-Support or simply a popular website. 

@dbluelle as far I understood you haven't "released" a new version right? It is just a fix to make the current version work as windowless. I am not familiar with how github works, would it be possible having a package to download and build?or a deb? Thank you:)

**Comment by yueyihua** [comment]
@WPFilmmaker 
Yes, the site DAF.fm and Videolectures are listed in https://github.com/lightspark/lightspark/wiki/Site-Support

**Comment by WPFilmmaker** [comment]
@yueyihua You are right it is listed and also as working...I think the list has to be updated, as soon as I manage to get the new version I will heavily test it on a list of popular websites so that list can be updated.

@ethus3h Is videolectures working for you?

**Comment by ethus3h** [comment]
@WPFilmmaker: Nope, I'm getting the same argument count mismatch error (running independently rather than in-browser).

(My point earlier was just that at least it sounds like the browser is loading the plugin correctly, not necessarily what the plugin did after that.)

**Comment by dbluelle** [comment]
OK, so I've just created the release, see https://github.com/lightspark/lightspark/releases (I hope I got everything right, as I've never done that before...) .
Please keep in mind that this is still alpha software.  
A lot of sites will not work, as we currently only implement around 50% of the APIs (and some of them are only implemented as stubs, search for "NOT_IMPLEMENTED" in the sourecode...) .

@yueyihua : The stacktrace you reported is "normal" for an swf that uses APIs that are not properly implemented yet. However you should get a proper error message rendered in the browser window, so there seems to be something still not working correctly in the new windowless plugin.

@WPFilmmaker : https://github.com/lightspark/lightspark/wiki/Site-Support is indeed very outdated.
You should now have editing rights on the Wiki pages, so feel free to update them.
