### ISSUE TITLE
After install Lightspark, I still can't play videos on Firefox

### ISSUE THREAD

**Issue by tanukamittra** [lightspark/lightspark#286]
![mediacorp](https://cloud.githubusercontent.com/assets/28604504/25911652/3d87fd64-35e7-11e7-9231-d4fd182373d1.JPG)

apparently, my firefox 52.0 cannot find Lightspark as a plugin or add-on

**Comment by yueyihua** [comment]
Maybe, you can add the plugin dll into system like this:
regsvr32 C:\Program Files (x86)\Lightspark 0.5.3-git\nplightsparkplugin.dll
But when i load it in firefox, i can not play video too, i don't why.
