### ISSUE TITLE
win32 build error

### ISSUE THREAD

**Issue by yueyihua** [lightspark/lightspark#288]
when i build lightspark，this error appear：

/home/sp/work/lightspark/src/scripting/abc_codesynt.cpp: In member function 'lightspark::ASObject* (* lightspark::method_info::synt_method(lightspark::SystemState*))(lightspark::call_context*)':
/home/sp/work/lightspark/src/scripting/abc_codesynt.cpp:4732:17: error: invalid use of incomplete type 'class llvm::FunctionPassManager'
  getVm(sys)->FPM->run(*llvmf);
                 ^
In file included from /home/sp/work/lightspark/src/scripting/abc_codesynt.cpp:60:0:
/home/sp/work/lightspark/src/scripting/abc.h:44:8: note: forward declaration of 'class llvm::FunctionPassManager'
  class FunctionPassManager;
        ^
src/CMakeFiles/spark.dir/build.make:1013: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc_codesynt.cpp.obj' failed

How to resolve it？

**Comment by dbluelle** [comment]
Compilation works now.
I've not tested the npapi/ppapi plugins.
They compile but I don't know if they actually run (I don't have a Windows installation to test)
