### ISSUE TITLE
Release Win64 and Win32 version?

### ISSUE THREAD

**Issue by yueyihua** [lightspark/lightspark#289]
When release Win64 and Win32 installer version?

**Comment by ethus3h** [comment]
From the conversation I've seen here, I think the Windows support is pretty experimental. Probably this will only happen if/when someone who wants it decides to work on it (it could be you!), but I could just be being pessimistic...

**Comment by WPFilmmaker** [comment]
Dbluelle (the only active developer) is planning on releasing a new version soon, see  #285. No idea if he is going to release it for Win too. Perhaps you can ask and see if he can make it. Also if you are familiar with debugging you can report bugs for such version.

**Comment by dbluelle** [comment]
As I only have limited testing possibilities via wine (and personally no need for windows packages ;) ), I will not provide binary packages for windows.
If anyone is interested in providing these, I think it should be possible to add them as a download to the release page https://github.com/lightspark/lightspark/releases
