### ISSUE TITLE
NP_Initialize not called in Fedora

### ISSUE THREAD

**Issue by yueyihua** [lightspark/lightspark#290]
When I use npapi plugin in firefox browser，NP_Initialize not called，why?
But NP_GetMIMEDescription and NP_GetValue are called.

**Comment by WPFilmmaker** [comment]
No idea if it is something not implement, but as you can see at #285 a new version should be out soon, therefore what I would do is just wait to get the newer version and see if you still have the same issue.

**Comment by dbluelle** [comment]
This is because Firefox has removed the support for windowed plugins.
We have to implement the NPAPI plugin as a windowless plugin.
Unfortunately I have not yet found a solution for rendering in the windowless plugin, as you only get a  X11 drawable (not a real window where you can insert the opengl window).
Maybe someone with more experience in X11 can help?
The plugin will be started if you add
```
--- src/plugin/plugin.cpp
+++ src/plugin/plugin.cpp
@@ -368,6 +368,7 @@ nsPluginInstance::nsPluginInstance(NPP aInstance, int16_t argc, char** argn, cha
 			}
 			//The SWF file url should be getted from NewStream
 		}
+		NPN_SetValue(aInstance,NPPVpluginWindowBool,(void*)false);
 		//basedir is a qualified URL or a path relative to the HTML page
 		URLInfo page(getPageURL());
 		m_sys->mainClip->setBaseURL(page.goToURL(baseURL).getURL());
```
but it will not display anything...

**Comment by yueyihua** [comment]
@dbluelle 
When i added you code in Linux, it can run, but some errors accur:
INFO: Lightspark version 0.7.2-716-gea421a4 Copyright 2009-2013 Alessandro Pignotti and others
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
INFO: RenderThread this=0x7f6d22ec6c00
INFO: Creating input thread
INFO: PLUGIN: NPScriptObjectGW returned to browser
ERROR: Resize not supported
ERROR: Resize not supported
ERROR: Resize not supported
INFO: Newstream for http://tv.sohu.com/upload/swf/playerGetUID131031.swf
INFO: zlib compressed SWF file: Version 11
INFO: Download complete http://tv.sohu.com/upload/swf/playerGetUID131031.swf
INFO: FrameRate 24
INFO: Creating VM
INFO: SWF Metadata:
	:		
INFO: MaxRecursionDepth: 1000, ScriptTimeoutSeconds: 60
INFO: SWF Info:
	ProductId:		3
	Edition:		6
	Version:		4.5.0.21328
	CompileTime:		1447229215131
NOT_IMPLEMENTED: End of parsing, bytesLoaded != bytesTotal:2895/2897
ERROR: Resize not supported
NOT_IMPLEMENTED: End of parsing, bytesLoaded != bytesTotal:813180/813182
ERROR: Resize not supported
ERROR: Resize not supported
INFO: Lightspark version 0.7.2-716-gea421a4 Copyright 2009-2013 Alessandro Pignotti and others
NOT_IMPLEMENTED: LoaderInfo: childAllowsParent and parentAllowsChild always return true
INFO: RenderThread this=0x7f6d0acecc00
INFO: Creating input thread
funcname
sogou_fid_temp_func_1499655485007
INFO: PLUGIN: NPScriptObjectGW returned to browser
ERROR: Resize not supported
ERROR: Resize not supported
ERROR: Resize not supported
INFO: Newstream for http://img.wan.sogou.com/cdn/ufo/fid/sogoufid_v3.swf
INFO: zlib compressed SWF file: Version 15
INFO: Download complete http://img.wan.sogou.com/cdn/ufo/fid/sogoufid_v3.swf
INFO: FrameRate 20
INFO: Creating VM
INFO: SWF Metadata:
	:		
	:		
	:		
NOT_IMPLEMENTED: End of parsing, bytesLoaded != bytesTotal:2819/2821

Can you resolve these? And if i run plugin in Windows, it crashed for runtime error, is this the same problem?

**Comment by dbluelle** [comment]
npapi plugin is now implemented windowless and works on linux, 
but the site http://tv.sohu.com still doesn't work
