### ISSUE TITLE
Official Newgrounds Support

### ISSUE THREAD

**Issue by Delphik** [lightspark/lightspark#296]
If anyone was active in the golden years of Newgrounds, it was a glorious creative commons like media portal repository and ranking system for flash animation, games , and music. It had a very great community of really helpful creative nerdy types, with and organically formed FLOSS like mentality. Only problem was the use of flash. Despite my fond memories of flash 8's ide, frame by frame development, action script 2.0 scriptable vectors and other assess. and its ability to allow anyone who came upon a *COUGH* legal copy to do some pretty amazing creative work, It had always suffered from its state as a closed source, buggy, proprietary, insecure, and monolithic vehicle for adobe to force brand lock-in, and control of rich web content development.

If lightspark were able to official support Newgrounds, and merge an amazing creative commons community with it would make my inner 13yr old lover of vulgar free games and cartoons, and my modern Libre sensibilities, very happy,

**Comment by ethus3h** [comment]
If this is a portal with a bunch of different Flash apps, won't adding support for it basically mean adding official support for *every* Flash app? This doesn't sound like just fixing the issues with a single thing...

**Comment by WPFilmmaker** [comment]
Best thing IMHO is installing the latest version and try different animations and report eventual bugs you find :)

**Comment by dbluelle** [comment]
What do you mean with "official support" ?
We can only say that game/app "x" does/doesn't work on lightspark, but it cannot be guarranteed that every flash file on the website works.
However feel free to test some apps and open issues for apps that don't work or post a list of apps that work.

**Comment by Delphik** [comment]
Official is the wrong word but there was a list of website support on the github project wiki. I found it strange that a site that was essentially the mecca for home brew hobbyist flash development and animation wasn't included. Unfortunately I won't have time to try much bug testing but I was hoping my feedback could at least be useful

**Comment by dbluelle** [comment]
Ok, maybe we can make a special section on the "site support" page for sites that offer multiple flash apps and report the status of the apps that have been tested

**Comment by madovsky** [comment]
for info for those who don't know shumway, a project from mozilla developers stopped 1 year ago
managing swf from a bunch of javascript files, This project can be forked and maybe helps lightspark to evolve. Check on Git Shumway

**Comment by WPFilmmaker** [comment]
I just tried a bunch of games and they all work with Lightspark 0.8.0. However I was unable to play any of the videos in their "movies" section.

**Comment by ousia** [comment]
@Delphik, maybe https://ruffle.rs may be aiming at supporting that (just my impression).

**Comment by eiglow** [comment]
I think due to the variety of flash content on sites like Newgrounds, only "supported" or "not supported" states is not the right way to look at this. If people want to test individual Flash applications, they can contribute to the table at the top of [this](https://github.com/lightspark/lightspark/wiki/Status-of-Lightspark-support) page.
