### ISSUE TITLE
Lightspark in Waterfox

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#297]
I am opening this issue to keep track on Lightspark and Waterfox.

**The background:**
Firefox is going to drop XUL-based add-ons with FF 57, in favor of WebExtension. Many addons will become incompatible or just become useless because the new format is much more restrictive than XUL.
It is likely that either Firefox users will migrate somewhere else or there will be a fork of Firefox.

**What is Waterfox:** 
It is a 64bit broswer based on Firefox, which features:
Disabled Encrypted Media Extensions (EME)
Disabled Web Runtime (deprecated as of 2015)
Removed Pocket
Removed Telemetry
Removed data collection
Removed startup profiling
Allow running of all 64-Bit NPAPI plugins
Allow running of unsigned extensions
Removal of Sponsored Tiles on New Tab Page
Addition of Duplicate Tab option

Since Waterfox "will also most likely carry on using XUL after Mozilla deprecate it and I’ll hopefully carry on maintaining it properly (while also including features Mozilla bring in). This could be very hard to do though, so we’ll have to see" (source: waterfoxproject.com) 

Waterfox is likely to be a good for many, to replace Firefox.

Has anyone ever tried to build Lightspark for Waterfox? Afaik they two browser can be installed side by side and since Waterfox is based on Firefox I would imagine Lightspark has no problem running on it. 

If it does not (asap I manage to build Lightspark I will check) IMHO it would be great having it support.

Waterfox's github page: https://github.com/MrAlex94/Waterfox

**Comment by ethus3h** [comment]
Addons/extensions are something different from plugins. Lightspark is a plugin (NPAPI/PPAPI), so the switch to WebExtensions I think would be irrelevant.

**Comment by WPFilmmaker** [comment]
@ethus3h Yes I know that, my point was that it is very likely that after FF 57 many users, especially power users, will feel the need to switch to something else (why would I want to use FF with Chrome's addons when I can use Chromium or Chrome?). 

Waterfox is one of the few alternatives based on FF, therefore having Lightspark working on it, would be a big plus.

As soon as i solve my issues with copiling Lightspark I will see if I am able to run it.

**Comment by ethus3h** [comment]
Ah, I see. Cool :)

**Comment by dbluelle** [comment]
There should be no problem running lightspark on Waterfox, as long as they are keeping the NPAPI interface.

**Comment by ousia** [comment]
@WPFilmmaker, any news on this?

**Comment by huwdp** [comment]
This apparently works on Linux. See here (https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser)
