### ISSUE TITLE
Lightspark in Chromium

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#298]
Chrome is shipped with flash, however Chromium, is not. 

Because many favor Chromium over Chrome (I am one of them) as it is fully open, IMHO having Lightspark supporting it would be great.

Lightspark 0.7.2 on Chrome didn't work as reported on: https://bugs.launchpad.net/lightspark/+bug/1158260

Seems because of this: https://bugs.webkit.org/show_bug.cgi?id=115210

Has something changed with 0.8.0 version?

**Comment by madovsky** [comment]
you can install flash player PPAPI for chromium directly from adobe website

**Comment by WPFilmmaker** [comment]
@madovsky Thanks for the information, Flash however is not open, therefore many people prefer not to install it. i am sure many would be happy to see Lightspark running on Chromium.

**Comment by madovsky** [comment]
sure that the best would be to run any swf natively. The only problem is for now AS1/AS2 engine is not in lightspark (unfortunately), and despite of people belief it is still widely used around the world.
Also keep alternative swf interpreter updated from new feature is a real hard work to maintain, especially for free

**Comment by dbluelle** [comment]
Lightspark 0.8.0 has a working PPAPI plugin, as mentioned in the release notes (and the changelog and the README ... ), so you should be able to use it with all chromium based browsers.
However keep in mind that chromium only allows one flash plugin to be installed, so you can't use both the adobe plugin and lightspark in the same browser instance.

**Comment by ousia** [comment]
@WPFilmmaker, any news on this?

**Comment by Lokesh-Raghavendra** [comment]
Hello, is Lightspark supported in chromium

**Comment by WPFilmmaker** [comment]
@dbluelle maybe you can answer to this?

**Comment by dbluelle** [comment]
The chromium plugin currently doesn't seem to work on windows, see https://github.com/lightspark/lightspark/issues/518 
Unfortunately nobody has yet found a way to get any log output to get a hint why it isn't working...
Does the swf file work when started with lightspark.exe?
Can you make the swf file available for download somewhere?

**Comment by Lokesh-Raghavendra** [comment]
> The chromium plugin currently doesn't seem to work on windows, see #518
> Unfortunately nobody has yet found a way to get any log output to get a hint why it isn't working...
> Does the swf file work when started with lightspark.exe?
Since its a web application, i tried to launch providing hosted server url but it didnt work. when i copied the swf and launched using path to the file, it failed
> Can you make the swf file available for download somewhere?
I am sorry, I wont be able provide it due to legal issues..

**Comment by dbluelle** [comment]
> I am sorry, I wont be able provide it due to legal issues..
In that case there is not much I can do to help you.
Can you build a debug version of lightspark and provide a log and/or stacktrace of the crash?
Can you test it on linux?

**Comment by Lokesh-Raghavendra** [comment]
> > I am sorry, I wont be able provide it due to legal issues..
> > In that case there is not much I can do to help you.
> > Can you build a debug version of lightspark and provide a log and/or stacktrace of the crash?
> > Can you test it on linux?

I am sorry for the delayed response, i have never built a debug version of lightspark. I will read the documentation and provide the stacktrace and also i will test the same in linux OS.. i need some time..

**Comment by MTKor** [comment]
I am working in a project with an aim to extend the lifetime of some internal Flash based applications. The idea is to build a tailor-made Windows browser application with embedded Chromium browser and we would like to use Lightspark for Flash support.

Therefore we would like to know if there has been progress in Chromium support and what are your plans regarding it.

**Comment by dbluelle** [comment]
The problem is that so far no one has got any clue why it doesn't work.
I've tried it inside a Windows7 virtual machine, but there was no message regarding lightspark in the debug log or the event log, so I don't know where else to look. 
The firefox plugin and the standalone application work, so maybe google has added some additional checks to ensure only the adobe plugin is loaded.
Maybe somebody with a lot of time and disk space can build a debug version of chromium for windows and try to find out how loading of the plugin works...

**Comment by redbrain** [comment]
I've installed Lightspark via the AUR and tried launching Chromium 87 with it like so:
`chromium --ppapi-flash-path=/usr/lib/lightspark/liblightspark.so`
Regrettably it doesn't work; no console error, just continuously displays "Right-click to run"
You may have already known this; in the case you didn't, I wanted to make sure you had more information.
+1 for Chromium support; thanks for keeping the ghost of Flash alive.

**Comment by dbluelle** [comment]
I only got the plugin to work on chromium if I explicitely tell the webseite to allow flash.
Just using the "ask" setting doesn't seem to work.
