### ISSUE TITLE
Veoh.com not supported (Lightspark 0.8.0)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#302]
Tried on FF 54 Ubuntu 17.04.

We are sorry, Lightspark encountered a yet unsupported Flash file
SWF file: http://www.veoh.com/static/swf/veoh/VideoBrowser.swf?version=1502726124
ReferenceError: Error #1065: Variable FlexBitmap is not defined.
    at global/()

**Comment by dbluelle** [comment]
should work in 0.8.1
