### ISSUE TITLE
Error #1009: Cannot access a property or method of a null object reference (crazymonkeygames.com)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#303]
On crazymonkeygames.com Lightspark can't play any games. Either crash or freezes. I got:
_SWF file: http://www.crazymonkeygames.com/swf-nr2kjn-jekb/raze.swf
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at Achievements/setFields()
    at Achievements/frame6()_

**Comment by ethus3h** [comment]
Here is debug output for running this item: https://gist.github.com/ethus3h/aafb6ec7a5bc339489509dd5bffb3d74

**Comment by dbluelle** [comment]
works in 0.8.1
