### ISSUE TITLE
Speedtest.net unsupported (Lightspark 0.8.0)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#305]
It is possible loading the test but it has many glitches and it is unusable, then it crashes and gives:

_SWF file: http://c.speedtest.net/flash/speedtest.swf?v=352081
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at _-3Y/if()_

**Comment by ousia** [comment]
@WPFilmmaker, do they still use Flash? (I would say they don’t.)

**Comment by WPFilmmaker** [comment]
@ousia I don't think so, I suppose it can be closed, unless anyone else suggests they still use Flash
