### ISSUE TITLE
Amazon Music is partially supported!

### ISSUE THREAD

**Issue by mastad0n** [lightspark/lightspark#309]
Hi,

Just wanted to say that the **web version** of Amazon Music (https://music.amazon.com) works, with a small loophole.

It appears that depending on your user agent string, it will work or not work.

I've got lightspark on https://music.amazon.com working in:

- Firefox 57 Developer Edition 57.0b3 (64-bit) Linux

- Palemoon Version: 27.5.0 (64-bit) Manjaro Linux

However, in both cases, you have to change your user agent string to:

**Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0|20170125094131**

In Firefox 57 I did that with this WebExtension Addon: [Custom User-Agent (Revived)](https://addons.mozilla.org/en-US/firefox/addon/custom-user-agent-revived/)

In Palemoon this can be done with the [Eclipsed Moon Addon](https://addons.palemoon.org/addon/eclipsedmoon/)

Just wanted to let you all know that. 

Thank you for the hard work!

**Comment by dbluelle** [comment]
I've added your information to the wiki page https://github.com/lightspark/lightspark/wiki/Site-Support
