### ISSUE TITLE
Push a new version of lightspark out for next Ubuntu LTS release (help required)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#317]
At the moment Ubuntu 17.10 still has 0.7.2 in the repos. Ubuntu Bionic Beaver 18.04 aka the next LTS release supported for 5 years will be out in April (here more details: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule ) it would be great having an updated version of lightspark there. If anyone knows the procedure to do that, please do so! Otherwise we would end up with a basically dead version in a popular distro for 5 years!

**Comment by dbluelle** [comment]
I think this is done via launchpad ( https://launchpad.net/lightspark/ ),
but I don't know the exact procedure.
I think there need to be some adjustments made in some of the files in the debian subfolder at https://github.com/lightspark/lightspark/tree/master/debian, but looking at all those weird files scares me ;)
I'm planning to release version 0.8.1 sometime soon, so that at least the build problems you encountered in issue #316 should be solved.

**Comment by WPFilmmaker** [comment]
@dbluelle Yes I thought so too, I think the best way would be contacting @alexp-sssup (I saw on his profile that he is active on github).

**Comment by WPFilmmaker** [comment]
@dbluelle I found these 

https://askubuntu.com/questions/75352/how-to-request-a-package-upgrade-in-the-next-ubuntu-release 

https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages

https://www.kubuntuforums.net/showthread.php/54134-FAQ-Requesting-new-packages-new-versions-new-features

Could be useful in the future :)

**Comment by orbea** [comment]
@dbluelle Thanks for the new release. One suggestion is only put the version number in the git tag. Github doesn't handle the directory names well with the tarballs and creates `lightspark-lightspark-0.8.1/` when extracted.

**Comment by dbluelle** [comment]
Thanks for the suggestion, I didn't recognize that.
Release is updated.

**Comment by jhwgh1968** [comment]
Ubuntu 18.04 released a while ago, and [lightspark seems to be missing entirely](https://packages.ubuntu.com/search?keywords=lightspark&searchon=names).

Is this issue still open to track something else?

**Comment by dbluelle** [comment]
Well, I thought I keep it open in case someone with some insight into Debian/Ubuntu package management will take over handling the Debian stuff...

**Comment by WPFilmmaker** [comment]
Chrome will remove flash in Dec 2020, I suppose Firefox will do the same, I think next LTS will be in 2021 so after flash's official death, but I think it shouldn't be a problem to have it included in the reps anyway. Next intermediate release could be targeted?
