### ISSUE TITLE
fatal error: llvm/Module.h: No such file or directory (trying to compile lightspark 0.8.0 Lubuntu 18.04)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#322]
I installed all the dependencies but when I reached "make" I get this error:

`lubuntu@pc:~/Downloads/lightspark-lightspark-0.8.0/obj$ make`

`[  3%] Built target translations
[  4%] Building CXX object src/CMakeFiles/spark.dir/scripting/abc.cpp.o`

`/home/lubuntu/Downloads/lightspark-lightspark-0.8.0/src/scripting/abc.cpp:38:12: fatal error: llvm/Module.h: No such file or directory
include <llvm/Module.h>
compilation terminated.
src/CMakeFiles/spark.dir/build.make:950: recipe for target 'src/CMakeFiles/spark.dir/scripting/abc.cpp.o' failed
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/CMakeFiles/spark.dir/all' failed
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

I tried to google it but nothing exactly came up, and all the questions were resolved with a fix on the software's side (so in this case would be Lightspark). Any idea?

Edit: I just realized that this error was also present a post in #316, are they related?

**Comment by dbluelle** [comment]
I think this is already solved in the git repository.
I will release version 0.8.1 soon, so if you don't want to use the git repository, please wait a few days...

**Comment by WPFilmmaker** [comment]
thanks a lot!

**Comment by dbluelle** [comment]
OK, I've just released 0.8.1.
Please check if your problem is fixed with that release.

**Comment by WPFilmmaker** [comment]
@dbluelle It compiled perfectly! Thank you! I have one issue though, I can't find lightspark in the plugins list in FF 60. Afaik last time I installed 8.0 on FF 56 after compiling it turned up after restarting it. How do I add lightspark to FF?

**Comment by dbluelle** [comment]
I assume you don't set the install prefix, so everything will be installed into /usr/local/.
If that is the case, the plugin is installed to /usr/local/lib/mozilla/plugins.
AFAIK firefox doesn't look in that folder for plugins, so you can either copy the plugin to /usr/lib/mozilla/plugins or under your home folder in ~/.mozilla/plugins
But to be sure please post the output of your "make install" step.

**Comment by WPFilmmaker** [comment]
I moved "plugins" from /usr/local/lib/mozilla to /home/lubuntu/.mozilla and it appeared! Thanks a lot!

Just for the record here is "make install":
`[  3%] Built target translations
[ 92%] Built target spark
[ 93%] Built target lightspark
[ 94%] Built target tightspark
[ 98%] Built target lightsparkplugin
[100%] Built target pepflashplayer
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/icons/hicolor/16x16/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/22x22/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/24x24/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/32x32/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/36x36/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/48x48/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/64x64/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/72x72/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/96x96/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/128x128/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/192x192/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/256x256/apps/lightspark.png
-- Up-to-date: /usr/local/share/icons/hicolor/scalable/apps/lightspark.svg
-- Up-to-date: /usr/local/share/applications/lightspark.desktop
-- Installing: /usr/local/share/locale/pl/LC_MESSAGES/lightspark.mo
-- Installing: /usr/local/share/locale/fr/LC_MESSAGES/lightspark.mo
-- Installing: /usr/local/share/locale/zh_CN/LC_MESSAGES/lightspark.mo
-- Up-to-date: /etc/xdg/lightspark.conf
-- Installing: /usr/local/lib/lightspark/liblightspark.so.0.8.1
-- Up-to-date: /usr/local/lib/lightspark/liblightspark.so.0.8
-- Up-to-date: /usr/local/lib/lightspark/liblightspark.so
-- Set runtime path of "/usr/local/lib/lightspark/liblightspark.so.0.8.1" to "/usr/local/lib/lightspark"
-- Installing: /usr/local/bin/lightspark
-- Set runtime path of "/usr/local/bin/lightspark" to "/usr/local/lib/lightspark"
-- Up-to-date: /usr/local/share/man/man1/lightspark.1
-- Installing: /usr/local/bin/tightspark
-- Set runtime path of "/usr/local/bin/tightspark" to "/usr/local/lib/lightspark"
-- Installing: /usr/local/lib/mozilla/plugins/liblightsparkplugin.so
-- Set runtime path of "/usr/local/lib/mozilla/plugins/liblightsparkplugin.so" to "/usr/local/lib/lightspark"
-- Installing: /usr/local/lib/PepperFlash/libpepflashplayer.so
-- Set runtime path of "/usr/local/lib/PepperFlash/libpepflashplayer.so" to "/usr/local/lib/lightspark"
-- Up-to-date: /usr/local/lib/PepperFlash/manifest.json`
