### ISSUE TITLE
ReferenceError: Error #1069 (veoh.com)

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#328]
Tested on Firefox 60.0.2 Lightspark 0.8.1, crashes at every file.

`SWF file: http://www.veoh.com/static/swf/veoh/VideoBrowser.swf?version=1529349265
ReferenceError: Error #1069: Property _VideoBrowser_mx_managers_SystemManager not found on QName and there is no default value.
    at mx.managers::SystemChildrenList/addChild()
    at _VideoBrowser_mx_managers_SystemManager/addChildToSandboxRoot()
    at mx.managers::ToolTipManagerImpl/createTip()
    at mx.managers::ToolTipManagerImpl/showTimer_timerHandler()`

**Comment by Randrianasulu** [comment]
I have same reference error #, but with different file:

http://www-cs-students.stanford.edu/~amitp/_test/
spaceship-world.swf  09-Oct-2012 15:16   108K  
guest@slax:/dev/shm/lightspark/x86_64/Release/bin$ LANG=C ./lightspark spaceship-world.swf
INFO: Lightspark version 0.8.1-198-gff8878a6 Copyright 2009-2013 Alessandro Pignotti and others
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
INFO: RenderThread this=0x8f25a08
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 13
INFO: FrameRate 60
INFO: Creating VM
nv50_screen_get_param: unhandled cap 44
nv50_screen_get_param: unhandled cap 44
INFO: Fragment shader compilation
INFO: Vertex shader compilation
INFO: throwing exception:1069 Property loadCompressedDataFromByteArray not found on flash.media::Sound and there is no default value.
    at Class/init()
    at Class/main()
    at boot_8ebf/init()
    at boot_8ebf/start()
    at boot_8ebf/()

ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1069: Property loadCompressedDataFromByteArray not found on flash.media::Sound and there is no default value.
INFO: dynamic cast:ReferenceError
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1069: Property loadCompressedDataFromByteArray not found on flash.media::Sound and there is no default value.
    at Class/init()
    at Class/main()
    at boot_8ebf/init()
    at boot_8ebf/start()
    at boot_8ebf/()

INFO: ~RenderThread this=0x8f25a08
