### ISSUE TITLE
Unknown Allocations to Unaccounted Memory Pool slowly consume all memory

### ISSUE THREAD

**Issue by jhwgh1968** [lightspark/lightspark#330]
I have a Flash file not suitable for distribution. On a recent master, it will play but has a lot of
graphical artifacts due to shape morph errors. These messages come in groups:

    NOT_IMPLEMENTED: morphing for line styles
    NOT_IMPLEMENTED: MorphShape currently ignores most morph settings and just displays the start/end shape. ID:77 ratio:32768

I am actually happy about this! :tada: I have been waiting for the project to even be able to play it instead of getting null object reference errors.

But something else is wrong: Lightspark is trying to consume all memory on my machine.

First, I noticed that the ID of the shapes kept going up, often skipping 3-15 numbers at various times. I did some checking with jemalloc, and the function ``TagFactory::readTag()`` does a lot of memory allocation.

So I decided to do a little poking around with GDB. Here is a cleaned up excerpt from my session:

    INFO: FPS: 17 0
    
    Thread 15 "lightspark" hit Breakpoint 3, lightspark::TagFactory::readTag (
        this=0x7fffc5ffa660, root=0x10c5880)
        at /tmp/lightspark-git/src/lightspark-build/src/parsing/tags.cpp:88
    88                              ret=new DefineShapeTag(h,f,root);
    (gdb) n
    250             firstTag=false;
    (gdb) p *ret
    $21 = {_vptr$Tag = 0x7ffff7b78a00 <vtable for lightspark::DefineShapeTag+16>, 
      Header = {Length = {val = 49}, CodeAndLen = {val = 191}}}
    (gdb) n
    INFO: FPS: 0 0
    252             unsigned int end=f.tellg();
    (gdb) n
    254             unsigned int actualLen=end-start;
    (gdb) 
    INFO: FPS: 0 0
    256             if(actualLen<expectedLen)
    (gdb) 
    261             else if(actualLen>expectedLen)
    (gdb) 
    269             if (root->loaderInfo->getBytesTotal() != f.tellg())
    (gdb) 
    INFO: FPS: 0 0
    270                     root->loaderInfo->setBytesLoaded(f.tellg());
    (gdb) 
    273     }
    (gdb) 
    INFO: FPS: 0 0
    lightspark::ParseThread::parseSWF (this=0x10e1f30, ver=...)
        at /tmp/lightspark-git/src/lightspark-build/src/swf.cpp:1446
    1446                            switch(tag->getType())
    (gdb) 
    INFO: FPS: 0 0
    1473                                            root->addToDictionary(d);
    (gdb) p *d
    $22 = {<lightspark::Tag> = {
        _vptr$Tag = 0x7ffff7b78a00 <vtable for lightspark::DefineShapeTag+16>, Header = {
          Length = {val = 49}, CodeAndLen = {val = 191}}}, bindedTo = 0x0, 
      bindingclassname = {_buf_static = '\000' <repeats 63 times>, 
        buf = 0x7fff2eee2678 "", stringSize = 1, numchars = 0, 
        type = lightspark::tiny_string::STATIC, isASCII = true, hasNull = false, 
        static npos = 4294967295}, loadedFrom = 0x10c5880}
    (gdb) p root->dictionary.size()
    $25 = 638
    (gdb) c
    Continuing.
    INFO: FPS: 0 0
    
    Thread 15 "lightspark" hit Breakpoint 5, lightspark::TagFactory::readTag (
        this=0x7fffc5ffa660, root=0x10c5880)
        at /tmp/lightspark-git/src/lightspark-build/src/parsing/tags.cpp:144
    144                             ret=new DefineShape3Tag(h,f,root);
    (gdb) n
    INFO: FPS: 0 0
    250             firstTag=false;
    (gdb) p *ret
    $28 = {_vptr$Tag = 0x7ffff7b78fe8 <vtable for lightspark::DefineShape3Tag+16>, 
      Header = {Length = {val = 121}, CodeAndLen = {val = 2111}}}
    (gdb) n
    INFO: FPS: 0 0
    252             unsigned int end=f.tellg();
    (gdb) 
    254             unsigned int actualLen=end-start;
    (gdb) 
    256             if(actualLen<expectedLen)
    (gdb) 
    261             else if(actualLen>expectedLen)
    (gdb) 
    269             if (root->loaderInfo->getBytesTotal() != f.tellg())
    (gdb) 
    270                     root->loaderInfo->setBytesLoaded(f.tellg());
    (gdb) 
    INFO: FPS: 0 0
    273     }
    (gdb) 
    lightspark::ParseThread::parseSWF (this=0x10e1f30, ver=...)
        at /tmp/lightspark-git/src/lightspark-build/src/swf.cpp:1446
    1446                            switch(tag->getType())
    (gdb) n
    INFO: FPS: 1 0
    1473                                            root->addToDictionary(d);
    (gdb) p *d
    $30 = {<lightspark::Tag> = {
        _vptr$Tag = 0x7ffff7b78fe8 <vtable for lightspark::DefineShape3Tag+16>, Header = {
          Length = {val = 121}, CodeAndLen = {val = 2111}}}, bindedTo = 0x0, 
      bindingclassname = {_buf_static = '\000' <repeats 63 times>, 
        buf = 0x7fff2eee5c18 "", stringSize = 1, numchars = 0, 
        type = lightspark::tiny_string::STATIC, isASCII = true, hasNull = false, 
        static npos = 4294967295}, loadedFrom = 0x10c5880}
    (gdb) p root->dictionary.size()
    $31 = 640

So it seems Lightspark is parsing of the same tag over and over again Each copy is added to the root movie's dictionary, and it just grows.

Other files I've tested don't do this. It seems to be this file. I don't know why. Which animations I play does not matter.

Would it be possible to prevent the tag dictionary from inserting duplicates somehow?

**Comment by dbluelle** [comment]
TagFactory::readTag() is called once for every tag in the swf, so it's normal that the IDs are going up until the whole swf file has been parsed.
There is a unique ID for every asset (sprite,shape,bitmap,sound,...) that is defined inside the swf.
The main swf file is only parsed once, so the only case where an swf file may be parsed multiple times is when it's (for whatever reasons) repeatedly downloaded from an external source by an URLLoader inside the main swf.
Please post the output of lightspark when setting the log level to LOG_TRACE:
```
lightspark -l 4 file.swf
```

**Comment by jhwgh1968** [comment]
Here is the log, huge as one would expect. I also took the liberty of piping the output through a program that timestamped each line in order to better help understand the timing of events.

0 sec: I started the application. It displayed a "loading" animation.
25 sec: The loading finished, and the first main animation ran. I let it sit there and play. Memory remained fairly stable at around 370 MB.
40 sec: I pressed a key to start the main animation. Memory usage starts growing at around 10 MB/sec.
~190 sec: main animation finished, went into secondary loop. Memory consumption is 3.2 GB.
205 sec: I closed the window. Memory consumption was still 3.2 GB.

[trace_log.txt.gz](https://github.com/lightspark/lightspark/files/2239142/trace_log.txt.gz)

**Comment by jhwgh1968** [comment]
I figured out how to get ENABLE_MEMORY_PROFILING working again (I'll submit a PR separately), and it seems Tags are not at fault after all. Here's a quick table of what I found from the memory accounting tables:

Timing | Unaccounted | Tags | Tiny_string | VM_Data
-------- | ----------------- | ------ | -------------- | ------------
After loading, before animation |  015401736 | 20815268 | 667 | 22416
Idle 10 sec, before animation | 015847992 | 20815268 | 667 | 22496
Part way through animation | 237346616 | 20815268 | 667 | 22496
Further into animation | 906031104 | 20815268 | 667 | 22496
Completed animation | -1364424104 | 20815268 | 667 | 22496

Note the integer rollover on the last line. Yikes.

It is a better place to start, I hope. I will update the title of this issue to reflect these findings.

**Comment by dbluelle** [comment]
I have a similar behaviour on some of my example swf files, which I'm still investigating.
It seems to be that reference counting does not correctly work everywhere.
With my last commit, this problem is somewhat reduced, so feel free to test if that fixes your problems.
However my test files still use about twice the amount of memory in comparison to the adobe player, so that problem is not completely fixed...

**Comment by jhwgh1968** [comment]
I did try your last commit, and the memory usage is the same as before.

Now that I have memory profiling working, I was thinking about creating additional memory pools for different types of resources, in the hopes that could narrow it down. Is there any specific area you think it would be useful to look in?

**Comment by dbluelle** [comment]
I think the main memory "eater" is BitmapContainer, maybe you can verify that.
(These objects handle the memory for images after they are decoded from jpeg/png)

**Comment by dbluelle** [comment]
That's a good hint, I will check on that.
Maybe you can confirm it by adding seperate memory accounts to the different TokenContainer-derived classes (Shape, MorphShape, Sprite, Bitmap).

I've also committed more reference count fixes, but I don't think they will help with your issue.

**Comment by jhwgh1968** [comment]
I've created a new patch to expand tracking for different types of tokens. I will open a PR for it.

Here is what the patch revealed:

| event | approx time | Tokens.Text | Tokens.Shape | Tokens.MorphShape | Tokens.Bitmap | Tokens.Sprite |
|-------|------------------|-------------|--------------|-------------------|---------------|---------------|
| loaded + idle | 0:10 | 58368 | 562248 | 1463760 | 0 | 0 |
| start of main animation | 0:30 | 58368 | 63483408 | 381755904 | 0 | 0 |
| more leaking | 0:50 | 58368 | 100903680 | 694783488 | 0 | 0 |
| large morph transform | 1:10 | 58368 | 175974960 | 1039923504 | 0 | 0 |
| more leaking | 1:45 | 58368 | 386684352 | 1358812968 | 0 | 0 |
| animation complete | 2:45 | 58368 | 655081392 | -2096154904 | 0 | 0 |

It's also worth noting that there is a temporary token buffer created by ``TokenContainer::FromDefineMorphShapeTagToShapeVector``. I made that use MorphShape tokens, since that seemed to be what was copied in there.

**Comment by jhwgh1968** [comment]
It reduces the leakage from several gigabytes to less than 50 MB or so. Just based on that, I would personally consider the issue fixed, but I know you want to track down the last couple of leaks.

>  It would be very helpful if you can somehow give me access to a demo swf file that produces the leakage.

I will send an e-mail to you shortly, using the e-mail address on your commit messages.

**Comment by jhwgh1968** [comment]
I will call this issue fixed. There is still a small leak, but it's not making the files unplayable.

Thanks for your efforts!
