### ISSUE TITLE
Please let me know the reference docs where you know what is to be impl for FLash in LSpark

### ISSUE THREAD

**Issue by EasyTechClick** [lightspark/lightspark#340]
Hi

Please let me know the reference docs where you know what is to be impl for FLash in Light Spark
Basically from which docs or books do you know what all is to be implemented in LightSpark so that Flash works perfectly in LighSpark. Please pardon me if this question seems idiotic, I am a newbie to Flash.

Thanks and yours sincerely,
Arvind.

**Comment by ethus3h** [comment]
These pages in the wiki might help:
- https://github.com/lightspark/lightspark/wiki/Development-Guide
- https://github.com/lightspark/lightspark/wiki/DevelTasks
:smile:
