### ISSUE TITLE
Does Lightspark fully support any old version of Flash viz, for eg Flash v9 etc>

### ISSUE THREAD

**Issue by EasyTechClick** [lightspark/lightspark#341]
Hi

Does Lightspark support any old version of Flash fully viz Flash v8  or v9 etc?

Thanks and sincerely,
Arvind.

**Comment by dbluelle** [comment]
Currently there is a fallback to gnash for all swf files with versions < 9 .
(Basically we just start a gnash process with the swf file as parameter).
See also https://github.com/lightspark/lightspark/issues/339
