### ISSUE TITLE
CMake Error: No source or binary directory provided

### ISSUE THREAD

**Issue by AndreasDM** [lightspark/lightspark#343]
When trying to install on arch linux from aur:

```
==> Building and installing package
==> Making package: lightspark-git 0.8.1.r156.g59a39ee4-1 (Sun 27 Jan 2019 10:31:03 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating lightspark-git git repo...
Fetching origin
==> Validating source files with md5sums...
    lightspark-git ... Skipped
==> Extracting sources...
  -> Creating working copy of lightspark-git git repo...
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
CMake Error: No source or binary directory provided
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build lightspark-git.
```

**Comment by ethus3h** [comment]
I wonder if this is related to the repository containing an object with zero-padded file mode. That prevents cloning it without passing custom options to `git clone`. See https://stackoverflow.com/questions/41029654/ignore-fsck-zero-padded-file-mode-errors-in-git-clone for some information about that issue... (I don't think the repo used to have any files like that in it, but it does now.)

**Comment by ethus3h** [comment]
For Gentoo GNU/Linux, having the package do a shallow clone instead of a full clone allowed working around the issue and let the build succeed. If this was the same issue for Arch, maybe that solution could be used there too. :)

**Comment by dbluelle** [comment]
I've just tested building the AUR package and got the same error.
I think it's because the cmake command in the PKGBUILD script is missing the path to the source as parameter.
When adding a dot at the end, everything builds fine:
```
build() {
  cd "$pkgname"
  cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCOMPILE_PLUGIN=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DGNASH_EXE_PATH=/usr/bin/gtk-gnash \
    -DAUDIO_BACKEND="pulseaudio sdl" .
  make
}
```
It's weird that this has worked all the time, as AFAIK cmake always needs the path to the sources as argument :confused:

**Comment by orbea** [comment]
I would suggest building in a `build` directory for cmake.
```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DMANUAL_DIRECTORY=man \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DGNASH_EXE_PATH=/usr/bin/gtk-gnash \
    -DCMAKE_BUILD_TYPE=Release ..
  make
  make install DESTDIR=$PKG
cd ..
```

**Comment by xuiqzy** [comment]
Is this error from the same common source or should I open a new issue for it?

```CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
```

**Comment by dbluelle** [comment]
It seems that you have also forgotten to specify a separate directory for building.
Ensure that you setup a separate directory for building, then start cmake from that directory with the last parameter pointing to the source directory.
please post your cmake command  here.

**Comment by nobodywasishere** [comment]
I have just took over as maintainer of lightspark-git on the AUR. I fixed this error and so it should work now. I'll work on adding a separate directory for cmake. Let me know if you run into any issues or have other suggestions.

**Comment by YMF00** [comment]
I need help, please !
┌──(ka0s㉿kali)-[~/snort_src/hyperscan-5.4.0-build]
└─$ sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DB00ST_R00T=~/snort_src/boost_1_76_0/../hyperscan-5.4.0
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the                                                       
  same as the current working directory, but note that this warning will                                                        
  become a fatal error in future CMake releases.

**Comment by dbluelle** [comment]
Are you sure this is for building lightspark?
However, you have to provide a directory as the last parameter to the cmake call. cmake will then look in that directory for the sourcecode of the project.
so in your case `cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DB00ST_R00T=/snort_src/boost_1_76_0/../hyperscan-5.4.0 ..` should work.

**Comment by Kassy607** [comment]
Hello I have the same Warning:  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


But I specified a separate directory for building.  ~/Documents/Paddle/Paddle/build (develop)

I followed made this:  

rm -rf build
mkdir build
cd build

cmake  .. \
    -DWITH_CONTRIB=OFF \
    -DWITH_MKL=ON \
    -DWITH_MKLDNN=ON  \
    -DWITH_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DON_INFER=ON \
    -DWITH_PYTHON=ON

**Comment by dbluelle** [comment]
OK, this also doesn't seem to be lightspark related...
As already written above, the folder where cmake looks for the CMakeLists.txt files always has to be the **last** argument of the command, so in your case put the ".." after all the -D... flags and it should work
