### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by matrix3d** [lightspark/lightspark#345]
```
-- Gnash not found
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
-- Found OpenGL: opengl32
-- Could NOT find GLEW (missing: GLEW_LIBRARY GLEW_INCLUDE_DIR)
-- Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR PCRE_LIBRARY)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
```

**Comment by jhwgh1968** [comment]
I didn't think building on Windows was supported, [only building on Linux with MXE](https://github.com/lightspark/lightspark/blob/master/README.win32).

That said, I might still be able to help you, since I have some experience with compiling open source on Windows. Could you explain more about what you did, and what you installed first? (MinGW, Cygwin, etc)

**Comment by matrix3d** [comment]
I just used cmake

**Comment by jhwgh1968** [comment]
Oh. Then I'm afraid I can't offer much help.

As the errors suggest, you need a lot of different open source libraries to build Lightspark, most of which are not native to Windows. Getting those on Windows is not easy, and things keep changing as Windows and the packages update. That is why (I think) there are no Windows build instructions.

If you don't have a Linux machine, you can [download a pre-built VM of Ubuntu](https://www.osboxes.org/ubuntu/) for either VirtualBox or VMware, run the [MXE cross build instructions](https://github.com/lightspark/lightspark/blob/master/README.win32) on that, and copy the EXE files to your Windows desktop.

Hope that helps.

**Comment by matrix3d** [comment]
Thank you, but I just want to use vs test on windows, not really want to use it on windows. My ultimate goal is to compile this library into ios, I don't know if I can do this.

**Comment by matrix3d** [comment]
Is there an open source flashair library that can parse swf on ios? Adobe air sdk is closed source. I want to use an open source implementation.

**Comment by jhwgh1968** [comment]
I'm afraid an iOS port is out of the question. Not only in terms of logistics, which are worse than Windows, but for legal reasons:

1. The iOS Developer terms [generally do not allow general purpose interpreters, such as a Flash Player](https://www.macobserver.com/tmo/article/apple_revises_ios_developer_terms_with_interpreted_code_support).
2. This library is released under the LGPL, [which is incompatible with the Apple Store shrink wrap license](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement).
