### ISSUE TITLE
Lightspark 08.1 does not show up in firefox 66.0.3

### ISSUE THREAD

**Issue by WPFilmmaker** [lightspark/lightspark#347]
I compiled lightspark from github master and from terminal I can see I have 0.8.1. However when I launch FF it does not show up in the 'plugins' section. I tried some websites from the wiki and they seem to be working, however when I tried to use one of those sites 'do I have flash installed?' the 2 I tried both reported that I didn't. So now I am confused :/ any help?

I am on Lubuntu 18.04.

**Comment by dbluelle** [comment]
Where did you install the firefox plugin?
By default it's installed into <PREFIX>/lib/mozilla/plugins/liblightsparkplugin.so.
It seems that the plugin is installed into a path where firefox doesn't look for plugins.
(The default PREFIX is /usr/local, so it may be firefox doesn't look there)
Please post the output of the "sudo make install" step.

**Comment by WPFilmmaker** [comment]
@dbluelle very weird /lib contains no mozilla folder :/ I use FF shipped with ubuntu... could that be the reason?maybe they install it in another folder?

**Comment by dbluelle** [comment]
I don't know how ubuntu handles this, but normally it should be /usr/lib/...
However, please post the output of the "sudo make install" step.

**Comment by WPFilmmaker** [comment]
@dbluelle I fixed this with 
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install

Which I found in an old ticket I opened for the same reason:D
