### ISSUE TITLE
Resize window scales contents as a vector instead of as rasters

### ISSUE THREAD

**Issue by wyatt8740** [lightspark/lightspark#348]
Lightspark appears to perform bilinear filtering or similar when resizing a window; that is, it doesn't scale shapes as vector graphics but as rasters. This makes it look far inferior to The Real Deal (tm) when both windows are maximized with lower "resolution" tagged flashes.

**Comment by wyatt8740** [comment]
Silly me, got my title reversed.

**Comment by ousia** [comment]
@wyatt8740, this should be fixed with commit d6865bb45d78098f37d58f7975671c33535f48c3.

Could you check the issue with current master and close the issue if this works?

**Comment by ousia** [comment]
@wyatt8740,

since you don’t provide any content to check and commit d6865bb45d78098f37d58f7975671c33535f48c3 fixed an issue with the same description as yours (#378), I think this one may be safely closed.

Would you be so kind to check whether the statement above applies and close the issue?

**Comment by wyatt8740** [comment]
I will check it today, thanks.

**Comment by wyatt8740** [comment]
Yes, this seems to have solved that particular issue. Thanks for letting me know, and sorry about the poor phrasing on my part.
