### ISSUE TITLE
Build failure with LLVM v7 or v8

### ISSUE THREAD

**Issue by bill-auger** [lightspark/lightspark#358]
### What is the purpose of your issue?
- [X ] If none of the above apply, check this box. FTBS

#### Provide the complete set of instructions required to reproduce the problem:
```
  cmake -DCMAKE_INSTALL_PREFIX=/usr         \
        -DCOMPILE_PLUGIN=1                  \
        -DCMAKE_BUILD_TYPE=Release          \
        -DGNASH_EXE_PATH=/usr/bin/gtk-gnash \
        -DAUDIO_BACKEND="pulseaudio sdl"   ..
  make
```

#### What operating system are you are running on?
- [X]] Other: parabola (arch)

### Description of your issue

lightspark v0.8.1
llvm v8.0.0

the error is identical to the one in the closed BR "Build failure with llvm 7" (#336 ); but i got the the same error also using LLVM v7.1.0 - it built successfully with LLVM v6.0.1

```
... scripting/abc.cpp: In static member function ‘static void lightspark::ABCVm::Run(lightspark::ABCVm*)’:
... scripting/abc.cpp:1960:22: error: ‘createPromoteMemoryToRegisterPass’ is not a member of ‘llvm’
 1960 |   th->FPM->add(llvm::createPromoteMemoryToRegisterPass());
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... scripting/abc.cpp:1964:22: error: ‘createInstructionCombiningPass’ is not a member of ‘llvm’; did you mean ‘initializeInstructionCombiningPassPass’?
 1964 |   th->FPM->add(llvm::createInstructionCombiningPass());
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dbluelle** [comment]
This one is (sort of) solved in git master branch, so currently you have to use the git master for building.
The next release 0.8.2 will be coming after building ubuntu packages with travis is completed (see https://github.com/lightspark/lightspark/issues/355 )

**Comment by dbluelle** [comment]
0.8.2 is released, so I close this.
