### ISSUE TITLE
Can't build Lightspark on Ubuntu 19.04 x86_64

### ISSUE THREAD

**Issue by nomelif** [lightspark/lightspark#360]
### What is the purpose of your issue?
- [x] If none of the above apply, check this box.

### Description of your issue

I can't get Lightspark to build on Ubuntu. My specs (or whatever pseudo-relevant Neofetch comes up with):

```
OS: Ubuntu 19.04 x86_64
Host: Aspire SW5-012P V1.10 
Kernel: 5.0.0-23-generic 
CPU: Intel Atom Z3735F (4) @ 1.832GHz 
GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display 
Memory: 1126MiB / 1896MiB 
```

I manually installed packages untill cmake was happy. Now I get this error:

```
cursed@kiinake:~$ cd lightspark-0.8.1/obj/
cursed@kiinake:~/lightspark-0.8.1/obj$ make
[  3%] Built target translations
[  4%] Building CXX object src/CMakeFiles/spark.dir/allclasses.cpp.o
In file included from /home/cursed/lightspark-0.8.1/src/scripting/flash/net/flashnet.h:29,
                 from /home/cursed/lightspark-0.8.1/src/swf.h:32,
                 from /home/cursed/lightspark-0.8.1/src/scripting/class.h:28,
                 from /home/cursed/lightspark-0.8.1/src/scripting/toplevel/ASString.h:23,
                 from /home/cursed/lightspark-0.8.1/src/allclasses.cpp:20:
/home/cursed/lightspark-0.8.1/src/backends/decoder.h:327:2: error: ‘CodecID’ does not name a type; did you mean ‘AVCodecID’?
  CodecID LSToFFMpegCodec(LS_AUDIO_CODEC lscodec);
  ^~~~~~~
  AVCodecID
make[2]: *** [src/CMakeFiles/spark.dir/build.make:63: src/CMakeFiles/spark.dir/allclasses.cpp.o] Virhe 1
make[1]: *** [CMakeFiles/Makefile2:211: src/CMakeFiles/spark.dir/all] Virhe 2
make: *** [Makefile:152: all] Virhe 2
```

Can you help me?

**Comment by dbluelle** [comment]
It seems that ffmpeg is not properly detected.
That seems to happen sometimes if the ffmpeg packages are not installed when running cmake for the first time.
Please clear your build directory and then redo the cmake step.
Also post the output of cmake here.

**Comment by eiglow** [comment]
I was also able to reproduce this issue on Ubuntu 19.10. Here is the output of cmake: [cmake-output.txt](https://github.com/lightspark/lightspark/files/4267186/cmake-output.txt)

**Comment by guest951** [comment]
I had the same issue because I installed libavcodec after having run cmake. Erasing the build directory solved that problem for me.
