### ISSUE TITLE
Commando 2 not working

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#361]
### What is the purpose of your issue?
A specific game does not work.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

https://static4.kizi.com/system/static/games/commando-2.swf

#### What kind of failure is your issue?

- [x] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``

Output of ``lightspark -v``:
`Lightspark version 0.8.1-268-g1f54b650 Copyright 2009-2013 Alessandro Pignotti and others`

#### What operating system are you are running on?

KDE Neon User Edition 5.16 (Ubuntu 18.04.2 LTS)

#### How are you are running Lightspark?

Running from the command line.

#### Which of these actions you have taken to help debug the problem?

I attached a log, but the relevant part seems to be the following:
```
INFO: throwing exception:1074 Illegal write to read-only property bitmapdata on flash.display::MovieClip.

ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1074: Illegal write to read-only property bitmapdata on flash.display::MovieClip.
INFO: dynamic cast:ReferenceError
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1074: Illegal write to read-only property bitmapdata on flash.display::MovieClip.
```
[commando-2-lightspark-log.zip](https://github.com/lightspark/lightspark/files/3520177/commando-2-lightspark-log.zip)

**Comment by dbluelle** [comment]
Just FYI:
The error is fixed, but the game still doesn't work (You get into the main menu, but after clicking "start" the game hangs in the loading screen... )
