### ISSUE TITLE
Discussion on compatibility information

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#362]
For games and other kinds of Flash content, having entire sites marked as supported doesn't make much sense to me. Perhaps support could be documented on a per-application basis, a bit like how [Wine](https://appdb.winehq.org/) or [Proton](https://www.protondb.com/) have it? I think this would make more sense, as the information would be more useful to anyone who wants to know whether something works with Lightspark or not.

**Comment by jchv** [comment]
Actually, it looks like this was attempted at a time: https://github.com/lightspark/lightspark-appdb

Sadly, it also looks like it is a relic of the past at this point. Perhaps a reboot is in order?

**Comment by dbluelle** [comment]
I've never looked into the appdb repository, so I don't know how that works.
Maybe it would be enough to just edit the wiki page and add a table for the status of specific applications.
That way anyone with a github account is able to add status reports.
Another possibility would be to simply add a status page to the lightspark.github.com repository.
However feel free to look into the appdb repository and try to make some sense out of it...

**Comment by eiglow** [comment]
I think adding to the Wiki will be the most straightforward thing to do at the moment. If I were to add it to [this](https://github.com/lightspark/lightspark/wiki/Site-Support) page, do you think it would be a good idea to rename it from "Status of Lightspark support for various websites using Flash" to simply "Lightspark support status", in reflecting the now broadened purpose of this page?

**Comment by dbluelle** [comment]
Yes, do that.

**Comment by eiglow** [comment]
[I added it](https://github.com/lightspark/lightspark/wiki/Site-Support), what do you think? I have plenty of SWFs that I would like to test and record compatibility info for, and I think documenting it in this format would be preferable to spamming the issue tracker.

**Comment by dbluelle** [comment]
I've edited the page to reflect the new title and put the applications on top,
as I think more and more Websites will be removed from the list and the list of tested applications will become more important.
(Well it's a new page now, as changing the title apparently does create a new page :( )
Everyone feel free to add more applications there.
