### ISSUE TITLE
Website link still points to Sourceforge

### ISSUE THREAD

**Issue by jchv** [lightspark/lightspark#363]
_Ignoring issue template since it is not particularly useful in this case..._

Simple enough:

![image](https://user-images.githubusercontent.com/938744/63653082-0433e680-c71d-11e9-84f4-91807cf61f57.png)

I suggest moving it to [https://lightspark.github.io/](https://lightspark.github.io/) since that appears to be the current landing page for the project.

**Comment by dbluelle** [comment]
done.
