### ISSUE TITLE
cannot load file from url

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#370]
Trying to load file form an url (such as http://www.free-culture.tk/lessig-freeculture-loader.swf) seems not to be recognized by _Lightspark_.

Here you have my command and the output:

```
$ lightspark --url http://www.free-culture.tk/lessig-freeculture-loader.swf
INFO: Lightspark version 0.8.2 Copyright 2009-2013 Alessandro Pignotti and others
ERROR: Usage: lightspark [--url|-u http://loader.url/file.swf] [--disable-interpreter|-ni] 
[--enable-fast-interpreter|-fi] [--log-level|-l 0-4] [--parameters-file|-p params-file]
[--security-sandbox|-s sandbox] [--exit-on-error] [--HTTP-cookies cookie] [--air]
[--avmplus] [--disable-rendering] [--version|-v] <file.swf>
```

**Comment by dbluelle** [comment]
You always have to provide a local swf file when using the command line tool.
The --url parameter only makes lightspark pretend that the swf file is run from the provided URL.
This is useful if the swf downloads other files from that website.
So you have to download the swf file first like this:
```
wget http://www.free-culture.tk/lessig-freeculture-loader.swf
```
After that, the following call works:
```
lightspark --url http://www.free-culture.tk/lessig-freeculture-loader.swf  lessig-freeculture-loader.swf
```
