### ISSUE TITLE
[AS2] distorted sound playing

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#381]
@dbluelle,

I don’t know why sound from https://video-vectorial.tk/video-vectorial-presentation.swf is played too slow.

It is an MP3 file (compressed with `lame -m m -b 32 sound.wav`), the same as other presentation without this issue (such as the ones I mentioned here).

Many thanks for your help.

**Comment by dbluelle** [comment]
Just FYI: your MP3 has a sampling rate of 16 kHz, but the DefineSoundTag only has flags for 5.5, 11, 22 or 44 kHz. 
(So we now just ignore the flag and use the "correct" sampling rate as reported by ffmpeg)

**Comment by ousia** [comment]
@dbluelle, many thanks for your fixes.

And many thanks for the information on the audio sample rate, too.
