### ISSUE TITLE
[AS2]  Mouse listening not working

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#388]
@dbluelle,

https://ousia.gitlab.io/free-culture/lfc-presentation.swf contains the following AS2 code for mouse:

``` js
Mouse.onMouseDown = function() {
    if ((getTimer() - lastClick) < 400) {
        pause_or_play();
    } else {
        lastClick = getTimer();
    }
};

Mouse.addListener(Mouse);
```

Double click should pause or restart the sound, but Lightspark doesn’t recognize it.

BTW, the slides and sound of the previous presentation is the same as the one in http://www.free-culture.tk/lessig-freeculture.swf, but AS2 code isn’t the same.

Would you be so kind to implement or fix this?

Many thanks for your help.

**Comment by dbluelle** [comment]
The link you provided is broken.

**Comment by ousia** [comment]
Corrected now: https://ousia.gitlab.io/free-culture/lfc-presentation.swf.
