### ISSUE TITLE
issue with https://www.improve-presentations.tk/

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#393]
@dbluelle,

many thanks for all the fixes and implementations.

The presentation contained at https://www.improve-presentations.tk has the following issues:

1.  Related to commit fa9ea80574b260ba2c2c9e2857c69ee2d25ed60c, frame transition displays a black screen with text on it, horizontally and vertically centered. There should be nothing displayed between frames.

1. Button centering in the loader (the same one as in #384) is problematic, because it is first displayed on the upper left corner and then placed with ActionScript to the middle of the screen.
    It should be displayed only when centered.

1. Presentation contains frames numbered from 0 to 9. Lightspark isn’t able to display anything after 6 (although the sound ends in 9).

    Using the desktop program, Lightspark complains twice when it reaches frame 7 (with number y on it):

    ```
    Invalid return value 0 for stream protocol
    ```

Do you want me to report each issues individually or is it fine with this common report? 

Many thanks for your help.

**Comment by dbluelle** [comment]
Seperate issues are better, as it's easier to reference them in the commit messages and you don't have to keept them open until all parts are solved.
(I've fixed part 3, but 1 and 2 are not done yet)

**Comment by ousia** [comment]
Many thanks for your fixes, @dbluelle.

It works like charm when presentation is loaded directly (https://www.improve-presentations.tk/Presentacion-presentation.swf, in this case).

But I’m afraid the presentation blinks when advancing frame when it comes through a loader (either https://www.improve-presentations.tk/Presentacion-loader.swf or the website itself, in this case).

I don’t know how this is handled, but blinking comes from:

1. Render frame  in presentation and advance to next frame.
1. Before the new frame is rendered, remove the old frame and load the contents from loader.
1. Render the new frame in presentation.

There should be no step 2, when using a loader.

I’m afraid I cannot reopen the issue myself.

Many thanks for your help.
