### ISSUE TITLE
Sound.Position() needs 500ms (audio buffering)

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#398]
@dbluelle,

this might look like a tricky issue, but it isn’t. Of course, we can discuss it.

It seems that Flash Player gives 500 milliseconds delay in playing for audio buffering (you might test this with the latest [projector debugger](https://www.adobe.com/support/flashplayer/debug_downloads.html)). This causes that LS always gets `Sound.position()` 500ms too late. All presentations that I have suffer from this.

https://free-culture.tk/lfc-presentation.swf shows it clearly. BTW, sound in this presentation is totally independent from frames (movies inside don’t contain sound).

I modified it to get straight to the point. If you press _c_, you go to the slide before a minimal sample video.

If you play both with FP and LS, you will notice that the jaw sound is accurate with FP; but the jaw sound is played a bit later with LS.

Would it be possible that `Sound.position()` worked with 500 milliseconds less than its actual value?

I hope I have shown the issue in a clear way. Let me know if my explanation wasn’t clear.

Many thanks for your help.

**Comment by dbluelle** [comment]
I could not exactly reproduce this (on my machine the sound was always ahead of the movie, not behind...)
However, I modified lightspark to start counting the played time based on the first time something is actually sent to the sound device (see https://github.com/lightspark/lightspark/commit/f65bea2f77e0d7d97722e6d4263db4648b3cee36 ), so maybe that fixes this issue.

Btw, thanks for all your reports, this really helps finding out some of the inner workings and quirks of flash.

**Comment by ousia** [comment]
@dbluelle,

many thanks for your fixes.

This one fixes the sound, now sound is too early, not too late.

I added https://free-culture.tk/lfc-nodelay.swf (which has no delay).

If you reproduce both files with FP and LS, sound is synced with images in the first one with FP and in the second one for LS.

FP plays sound 500ms too late in https://free-culture.tk/lfc-nodelay.swf.

These presentations contain time arrays. When originally created (not by myself), I realized that there was an audio delay of half a second. I was told that FP needs that time (500ms) to buffer audio, so it is played with that 500ms delay.

Italians say _se non è vero, è ben trovato_ (»wenn es nicht richtig ist, es ist gut erfunden« 😅).

Let me know what you think of this.

Many thanks for your help.

**Comment by ousia** [comment]
@dbluelle,

[testing-sound-loader.swf.txt](https://github.com/lightspark/lightspark/files/3982293/testing-sound-loader.swf.txt) and [testing-sound-presentation.swf.txt](https://github.com/lightspark/lightspark/files/3982294/testing-sound-presentation.swf.txt) show the issue more clearly.

Just in case it helps.
