### ISSUE TITLE
sprite inslide Flash blinks

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#401]
@dbluelle,

regarding both https://free-culture.tk/lfc-presentation.swf and https://free-culture.tk/lfc-nodelay.swf, both contain sprites with a video. They flick in Lightspark.

Do you need the actual code for the sprite? Or what would be required to fix this?

Many thanks for your help.

**Comment by ousia** [comment]
Sorry, I forgot. You get to the video by pressing _c_ 😅.

**Comment by eiglow** [comment]
Do you mean that the videos flicker? I'm not noticing any difference between Adobe Flash and Lightspark when running this file. Ensure that you're using the most recent version of Lightspark, compiled from master.

**Comment by ousia** [comment]
I see a basic difference: image isn’t constant with Lightspark (it blinks).

**Comment by dbluelle** [comment]
Sorry, I couldn't reproduce that.
What do you mean by "it blinks"? Are there black frames between the frames of the movie?
Are you using a debug build of lightspark (that sometimes leads to graphical glitches as it is significantly slower than the release build)

**Comment by ousia** [comment]
@dbluelle,

there are black frames between the movie frames.

I use a release build (as packaged for _Fedora_ by RPM Fusion).

Many thanks for your help.
