### ISSUE TITLE
Build failure with boost-1.72.0

### ISSUE THREAD

**Issue by orbea** [lightspark/lightspark#406]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [x] **Build**: Lightspark fails to compile
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

https://github.com/lightspark/lightspark/commit/f65bea2f77e0d7d97722e6d4263db4648b3cee36

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: `Slackware64-current`
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

### Description of your issue

With `boost-1.72.0` lightspark fails to compile, I have attached a complete build log.

log: [lightspark.log](https://github.com/lightspark/lightspark/files/3969035/lightspark.log)

**Comment by SoapGentoo** [comment]
@orbea This issue can be closed now. All packagers of boost should include my patch should they wish to package Boost 1.72.

**Comment by orbea** [comment]
@SoapGentoo Is there an upstream boost commit for that patch?

From reading the relevant threads I see upstream suggests downstream should be fixed.

> Downstream should `#include <boost/serialization/split_member.hpp>` if they need it.

https://github.com/boostorg/serialization/commit/c32a663c9963385430abc563f9c85f94d8da43a9#r36528430

> I don't think that inclusion of boost/serialization/split_member.hpp should be necessary anymore. Perhaps serialization of some other component requires this inclusion but didn't specify it expliciltly. Things would still work "by accident". The solution would be to explicitly add this inclusion in the component that complains about its absense.

https://github.com/boostorg/serialization/commit/c32a663c9963385430abc563f9c85f94d8da43a9#r36529755

**Comment by SoapGentoo** [comment]
If you're looking for a fix, it's https://github.com/boostorg/bimap/commit/f61dd9c5324d8439c52764c7aebaac7d0d4b7128

**Comment by orbea** [comment]
That is not an upstream boost commit and lightspark doesn't ship those files.

**Comment by orbea** [comment]
@SoapGentoo Here is a potential fix thanks to your helpful links.

https://github.com/lightspark/lightspark/pull/409

**Comment by SoapGentoo** [comment]
@orbea I personally wouldn't change lightspark just to fix an issue in boost. Packagers should just use my patch in boost.

**Comment by orbea** [comment]
@SoapGentoo Most packagers will not apply some random patch to boost unless boost upstream also accepts the change and I'm not sure they are interested. Although please submit it upstream so we can see.

**Comment by SoapGentoo** [comment]
@orbea The link I gave you is the official patch that goes into boost for 1.73. It doesn't get more official than that.

**Comment by orbea** [comment]
@SoapGentoo Apologies, I didn't understand earlier, given that is the case I'll try patching boost on my end to test.

I'm now confused why the boost maintainers claimed this should be done downstream if they are patching upstream?

**Comment by SoapGentoo** [comment]
@orbea "downstream" here is slightly misleading. **Downstream from Boost.Serialization** is anything consuming Boost.Serialization, which includes Boost.Bimap. The issue of this bug is in Boost.Bimap, which is a semi-abandoned lib in Boost which Robert Ramey forgot to port when modernizing his Boost.Serialization headers. I have added the patch in Gentoo, and with the Boost.Bimap patch, lightspark works fine in Gentoo.

**Comment by dbluelle** [comment]
I'm planning on removing boost dependency completely sometime soon as we are using it only for bimap and filesystem access.
