### ISSUE TITLE
full list of dependencies?

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#408]
@dbluelle,

also related to #386, I experience LS hangs.

This makes LS hardly usable to me.

Could you confirm the full list of LS dependencies?

This is to check whether I’m missing something.

Many thanks for your help.

**Comment by dbluelle** [comment]
The dependies as listed in READMe.md are correct.
I also occasionally have hangs when exiting lightspark, but I couldn't yet create a reproducible test case.
I suspect that under certain cirumstances, the thread producing the sound doesn't exit properly, but I'm not sure yet

**Comment by ousia** [comment]
@dbluelle, if you experience segfaults too and the dependencies are satisfied on my computer, then the problem is in LS.

Many thanks for your help.

**Comment by dbluelle** [comment]
Do you have a reproducible case where it always hangs?

**Comment by ousia** [comment]
I’m afraid I don’t have it.

Segfaults are too erratic. I would report the segfault as far as I find a reproducible one 😅.

**Comment by ousia** [comment]
Closing the issue myself.
