### ISSUE TITLE
(again) sound is played twice

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#425]
@dbluelle,

many thanks for commit 3dd5ae12a2b77805790d8385315bfd6703e45bb4, but I’m afraid I’m still experiencing the issue described in #422.

When I start playing https://randomfoo.net/oscon/2002/lessig/free_culture.swf, sound is played twice, as if the presentation were created with echo.

Sorry, but this wasn’t intended. Does sound play right for you? (You need to click three times to  get to the frame/slide where sound is started.)

Many thanks for your help.

**Comment by dbluelle** [comment]
I could not reproduce this, but I think I found the reason and fixed that.
