### ISSUE TITLE
screenshot at fullscreen with external margins

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#428]
@dbluelle,

here you have two screenshot files from LS (compressed as PNG imgages):

1. Screenshot from size defined in SWF file.
    ![nscreen](https://user-images.githubusercontent.com/203767/72108772-963b3500-3334-11ea-881c-e43eeba1a197.png)

1. Screenshot from SWF file in fullscreen.
    ![fscreen](https://user-images.githubusercontent.com/203767/72108770-963b3500-3334-11ea-9c72-73d0e207d099.png)

Margins are external to the rendering of the SWF file, so I guess they shouldn’t be included in the screenshot image.

Many thanks for your help.

**Comment by dbluelle** [comment]
I think it's better to store the screenshot as it is displayed in fullscreen mode (with the black borders), because if you want to show some rendering issue, it is better to know how the borders look like.
