### ISSUE TITLE
Bloons Tower Defense 4 unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#429]
swf: [bloons_tower_defense_4.zip](https://github.com/lightspark/lightspark/files/4052144/bloons_tower_defense_4.zip)

lightspark version: `0.8.2-424-gde923506`

The main culprit appears to be the following:
```
INFO: throwing exception:1024 Error #1024: Stack underflow occurred.
    at bloonstd4_fla::menu_medals_strap_94/()
```

Terminal output: [output.log](https://github.com/lightspark/lightspark/files/4052153/output.log)

**Comment by eiglow** [comment]
Also, just for future reference, is there any extra info I should include on these kinds of "unsupported" issues to make them easier to fix?

**Comment by dbluelle** [comment]
No, that info is enough.
