### ISSUE TITLE
Doesn't save shared objects (.sol files/"flash cookies") to disk.

### ISSUE THREAD

**Issue by dragontamer8740** [lightspark/lightspark#435]
### What is the purpose of your issue?

Save files (.sol) for persistence between sessions are not created, but should be.

- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:

Any SWF that saves data between sessions/plays (most games that store progress).

Bloons Tower Defense 4 ([download](https://mega.nz/#!fl4g2KaA!DU3MxrfJoGUGqqriJOCDvnmgcqAPePv14ZjPZ5FMN8I)) (doesn't currently work in lightspark due to other issues) is one.

#424 's SWF is another such file (that does largely work now besides this and a few minor font size issues).

#### Provide the complete set of instructions required to reproduce the problem:

1. Load an SWF that saves to files.
2. Attempt to save game.
3. Close the page (prior to this Lightspark appears to store them temporarily in RAM or something, because restore works at this point).
4. Re-open the page.
5. Attempt to load the save. No save data will be detected.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [x] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.2-424-gde923506 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [x] Other: FreeBSD

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue

Shared Object files (save data) are not written to disk when a game or application tries to save them. They will appear to have been written but only until the game or application is reloaded, at which time they disappear.

Meanwhile, on the AVM1/AS2 side of things, Gnash can save .sol files and load them, but Lightspark does not.

**Comment by dbluelle** [comment]
I've not yet added support for saving Shared object files mainly to avoid tracking when using the firefox/chrome plugin.
I think we should first add some possibility for users to setup wether they want to save shared objects,
that means adding a settings dialog and context menu support.

**Comment by dragontamer8740** [comment]
In my humble opinion, something like an `mms.cfg`-type file containing settings would be good enough for now.
But I also see your point.
