### ISSUE TITLE
Running Fred unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#440]
swf: [running_fred.zip](https://github.com/lightspark/lightspark/files/4082319/running_fred.zip)

lightspark version tested with: `0.8.2-430-g8f2c80b1`

The main culprit appears to be the following:
```
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1014: Error #1014: Class UnityApp could not be found.
    at com.unity::UnityContent/onFrameInitStep()
```

Terminal output: [runningfred.log](https://github.com/lightspark/lightspark/files/4082321/runningfred.log)

**Comment by dbluelle** [comment]
This seems to be fixed by one of the latest commits.
It runs now, but there are still massive graphical glitches (mostly because the game uses Stage3D which is not yet properly implemented)

**Comment by dbluelle** [comment]
Also just FYI the game needs avmplus, so you have to start it with command line parameter --avmplus
