### ISSUE TITLE
Endless War Defense unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#441]
swf: [endless-war-defense-6121.zip](https://github.com/lightspark/lightspark/files/4082657/endless-war-defense-6121.zip)

lightspark version tested with: `0.8.2-430-g8f2c80b1`

The error comes up only while the game attempts to load the main menu, after the intro.
```
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
    at entrenchments::Trench_7/registerTurret()
    at Soldier/()
    at Soldier/()
    at Class/getEntrenchment()
    at ScreenSaver/init()
    at ScreenSaver/onComplete()
    at GameArea/onDrawTexture()
```

Terminal output: [ewd.log](https://github.com/lightspark/lightspark/files/4082660/ewd.log)

**Comment by eiglow** [comment]
That commit fixed this specific issue, but unfortunately, there is now another unsupported issue on this game. This one however requires entering the campaign and hovering the mouse over specific levels which display blindage unlocks, so the terminal output log will be pretty long. Tested with version `0.8.2-450-gfaf1e5bb`:
```
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1010: Error #1010: A term is undefined and has no properties.
    at entrenchments.GER::Blindage_5/clear()
    at entrenchments.GER::Blindage_5/()
    at entrenchments.GER::Blindage_5/()
    at entrenchments.GER::Blindage_5/()
```
Terminal output: [ewd2.log](https://github.com/lightspark/lightspark/files/4150967/ewd2.log)
I appreciate all your hard work very much!

**Comment by dbluelle** [comment]
This is now fixed, but the game is still not playable due to graphical glitches and some buttons do not work properly...
Just for future reference: It would be better to open a new issue as no one really looks at the closed issues after they are closed ;)
