### ISSUE TITLE
Context menu support

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#443]
Part of achieving eventual feature parity with Adobe Flash Player includes adding support for context menus. Adobe's standalone Flash Player Projector seems to use GTK2 to handle this (I think?), and it seems like that using a GUI toolkit like GTK or QT is necessary to implement this in a sane way, unless we want to re-invent the wheel. Also, using a GUI toolkit will allow things like some kind of a GUI settings app to be implemented.

**Comment by dbluelle** [comment]
Today I've found the freeglut library (see https://www.openglprojects.in/2016/12/opengl-glut-create-menu-example.html), that should be a much smaller dependency.
Do you have any example of an swf file that actually uses context menus?
Most of the games don't use the ContextMenu class at all or only to disable the context menus completely...

**Comment by dbluelle** [comment]
I've tested freeglut, but unfortunately it only works with it's own event loop and window handling, so it's not suitable for lightspark.
Also the generated menus are (on linux) just basic x11 menus without any theming :disappointed:

**Comment by ousia** [comment]
https://www.free-culture.tk/lfc-presentation.swf contains a context menu.
