### ISSUE TITLE
Fireboy and Watergirl unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#445]
Lightspark version: `0.8.2-452-gd223339e`

swf: [Fireboy And Watergirl.zip](https://github.com/lightspark/lightspark/files/4176527/Fireboy.And.Watergirl.zip)

Error:
```
ERROR: Unhandled ActionScript exception in VM SecurityError: SecurityError: connect to network
    at CPMStar::AdLoader/addedHandler()
```

Terminal output: [fw.log](https://github.com/lightspark/lightspark/files/4176528/fw.log)

**Comment by dbluelle** [comment]
This swf downloads stuff from the internet, which is by default not allowed when running lightspark from the command line.
In order to allow network access you have to add the parameter "-s local-with-networking" or "-s local-trusted".

**Comment by Calvin304** [comment]
Fireboy and Watergirl only uses network to load ads, so with a [modified swf](https://drive.google.com/open?id=1tBwntkuSMzAjEcQxncyqjVj0U1kwmWTp) you get a [different set of issues](https://www.youtube.com/watch?v=1v4UZwEdBoA), [flash player projector for comparison](https://youtu.be/z6a6mHmZxeQ)

**Comment by eiglow** [comment]
@Calvin304 What graphics card/driver are you using? I get different graphical glitches, with mesa+amdgpu.
