### ISSUE TITLE
Swords and Souls unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#447]
Lightspark version: `0.8.2-454-gc65be101`

swf: [swordssouls-17817.zip](https://github.com/lightspark/lightspark/files/4219029/swordssouls-17817.zip)

Main error:
```
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1065: Error #1065: Variable CurrencyFormatter is not defined.
    at Class/()
    at global/()
    at ButtonSGloader/()
    at ButtonSGloader/()
    at ButtonSGloader/()
    at com.soulgame.interfaces::Preloader/()
    at Main/()
```

Terminal output: [swordssouls.log](https://github.com/lightspark/lightspark/files/4219034/swordssouls.log)

**Comment by huwdp** [comment]
Looks like CurrencyFormatter is not implemented. I'm happy to try implement as much as I can so I can get this working

**Comment by huwdp** [comment]
I have all the boilerplate setup for CurrencyFormatter. I just need to fill in the logic of the class which will take a while.

**Comment by dbluelle** [comment]
You don't have to implement all logic at once, just add a NOT_IMPLEMENTED log output for unimplemented methods.
Just implement the logic needed to run the swf file, so that you can verify that those methods work.

**Comment by huwdp** [comment]
I have more issues such as 
```Cannot create property componentInspectorSetting on interfaces::ButtonItem.``` and ```ERROR: trying to get variable on null:[ns:] blockPowerText```. I'll look into these soon.

Terminal output: [log.log](https://github.com/lightspark/lightspark/files/4252625/log.log)

**Comment by huwdp** [comment]
```CALLS:                         callFunctionNoArgsVoid_l _applyColorMaxed on [object interfaces::ButtonStats](0x7fee986c85f0 / 8) 
CALLS:                           getLex_l:[ns:game] FightManager
CALLS:                           getProperty_sl [ns:] hero [class game::FightManager](0x7feea81efab0 / 1 not constructed)  1
CALLS:                           Calling the getter for [ns:] hero on [class game::FightManager](0x7feea81efab0 / 1 not constructed) 
CALLS:                             getLex_l:[privns:] _hero
CALLS:                             returnValue_l Null
CALLS:                           locals:Undefined
CALLS:                           locals:Null
CALLS:                           locals:Undefined
CALLS:                           End of getter [object Function](0x7feea89b5350 / 1)  result:Null
CALLS:                           coerce [ns:characters] Hero
CALLS:                           setLocal 1
CALLS:                           getLex_l:[ns:interfaces] Screens```
