### ISSUE TITLE
Lightspark browser support after Dec 31, 2020

### ISSUE THREAD

**Issue by andmig** [lightspark/lightspark#448]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [x ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

### Description of your issue

It seems the major browsers will terminate all plugins support as of December 31, 2020. Will it be possible to run Lightspak flush plugin in any of the browsers after this date?

Thank you.

**Comment by dbluelle** [comment]
I'm not sure but I think that Chrome and Firefox will completely remove Flash support, so there won't be a way to run lightspark in those browsers.
I think browsers forked from older versions of Firefox (PaleMoon, WaterFox,...) will keep Flash support.
I don't know about browsers based on the Chromium Engine (Falkon,Opera, Vivaldi,...).

**Comment by Geo25rey** [comment]
Browsers based on the Qt Web Engine (Falkon, qutebrowser, etc.) natively support lightspark for swf content.

It might be worth looking into support for lightspark on Chromium (not Google Chrome) since Chromium supports external browser plugins like lightspark, but Google Chrome does not. Speaking of Chromium, Brave might work too.

**Comment by huwdp** [comment]
I think a wiki page on setting up Lightspark would be a good idea. I guess the stuff written there can then be converted into the installer, make files, etc.

I'd like to try convert Lightspark over to wasm but I still have a PR and a busy life right now. Should be back to normal pushing more PRs up in a few weeks. Can't promise I'll succeed converting it over as I've only used Emscripten on a personal project which is small and has little depedencies

**Comment by Geo25rey** [comment]
@huwdp The main dependency that needs to be handled is GLEW since web pages don't have "windows" like in normal desktop environments, but I think that's a separate issue.

**Comment by huwdp** [comment]
@Geo25rey GLEW should be fine by the looks of things. https://www.mtmckenna.com/posts/2019/04/08/opengl-wasm

**Comment by huwdp** [comment]
External libraries such as FFPMEG can be compiled into Bitcode and then into wasm. Haven't looked at that though

**Comment by Geo25rey** [comment]
@huwdp The reason I brought up GLEW specifically is that GLEW provides a window with an OpenGL context. And web browsers don't have explicit windows accessible to JS and Web Assembly.

**Comment by dbluelle** [comment]
I close this, as we now have a wiki page for suported browsers: https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser
