### ISSUE TITLE
Lightspark 0.8.2 on Windows crashing on start

### ISSUE THREAD

**Issue by ArmanHayots** [lightspark/lightspark#454]
I'm trying to run lightspark.exe on Win7x64 and getting this error

---------------------------
lightspark.exe - Entry Point Not Found
---------------------------
The procedure entry point ScriptIsComplex could not be located in the dynamic link library GDI32.dll. 
---------------------------
OK   
---------------------------

That's all.

**Comment by dbluelle** [comment]
I could reproduce that on a windows7 virtual machine.
It seems to be some 64bit problem with mxe, I've opened an issue there: https://github.com/mxe/mxe/issues/2465
When building lightspark for 32bit windows, the resulting binary works, so maybe we should add a 32bit windows build to the next release

**Comment by tonytheodore** [comment]
See:
https://docs.microsoft.com/en-us/windows/win32/api/usp10/nf-usp10-scriptiscomplex#remarks

> Important  Starting with Windows 8: To maintain the ability to run on Windows 7, a module that uses Uniscribe must specify Usp10.lib before gdi32.lib in its library list.

gdi32 is automatically added, so you can probably add usp10 here:
https://github.com/lightspark/lightspark/blob/d54c32f290d1ed30d5c965896b325475599d88d7/CMakeLists.txt#L287-L289
