### ISSUE TITLE
FNAF unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#456]
Lightspark version: `0.8.2-467-gaf8495b2`

swf: [link](https://ncade.ssl.hwcdn.net/flash/five-nights-at-freddys.swf) (too big to upload directly)

Main error:
```
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1065: Error #1065: Variable GameInput is not defined.
    at boot_d9be/init()
    at boot_d9be/start()
    at boot_d9be/()
```

Terminal output: [fnaf.log](https://github.com/lightspark/lightspark/files/4244083/fnaf.log)

**Comment by dbluelle** [comment]
I've added some stub classes for GameInput support, but according to the specs, GameInput is only supported on Adobe AIR, not on "normal" flash files.
So you have to start it with command line option --air.
However, we now get another exception, so it's still not running...

**Comment by eiglow** [comment]
Not entirely sure what the cause of the main error is, but there are a few instances of
```
ERROR: TextField HTML parser error
```
in the terminal output. This message comes from `src/scripting/flash/text/flashtext.cpp:1343`, and this message is sent due to `pugi::xml_document::load_buffer()` failing. So this could possibly be a bug in pugixml. I'm not sure when the last time pugixml was updated, perhaps we should update it? If the issue persists, we could report upstream.

**Comment by dbluelle** [comment]
I've fixed the html parsing, but that was not the issue that causes the exception.
(pugixml only parses xml, so it does fail on html wich allows unclosed tags like <br>)
