### ISSUE TITLE
Johnny Upgrade unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#457]
Lightspark version: `0.8.2-467-gaf8495b2`

swf: [mochi_johnnyupgrade1.zip](https://github.com/lightspark/lightspark/files/4244099/mochi_johnnyupgrade1.zip)

The error comes up after a few seconds from starting the swf. I tried both "-s local-with-networking" and "-s local-trusted", neither helped.

Here is the main error:
```
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
    at Class/loadError()
```

Full terminal output: [johnnyupgrade.log](https://github.com/lightspark/lightspark/files/4244127/johnnyupgrade.log)

**Comment by dbluelle** [comment]
This tries to download some swf files from mochiads.com, but the downloaded files are not swf files, but html pages, and the main swf does not handle the resulting IOErrors properly :(
Maybe we should add a command line switch to ignore unhandled exceptions (the flashplayerdebugger displays an error message and then continues normally)

**Comment by eiglow** [comment]
I think that command-line switch would be a good idea.
