### ISSUE TITLE
Learn 2 Fly: The Emperor Strikes Back - possible crash

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#459]
Lightspark version: `0.8.2-467-gaf8495b2`

swf: [learn_2_fly_the_emperor_strikes_back.zip](https://github.com/lightspark/lightspark/files/4259408/learn_2_fly_the_emperor_strikes_back.zip)

This doesn't seem like a segfault, but Lightspark closes almost instantly after trying to start the game.

I think this is the main error:
```
ERROR: Exception in ParseThread unsupported ActionPush type
```

Terminal output: [learn_2_fly_the_emperor_strikes_back.log](https://github.com/lightspark/lightspark/files/4259409/learn_2_fly_the_emperor_strikes_back.log)

**Comment by eiglow** [comment]
gdb points towards `lightspark/src/asobject.cpp:903`. However, I'm not sure how to find out exactly where the function was called from and with what parameters.

**Comment by masatake** [comment]
It seems that you have to switch to the thread that prints the message before taking a backtrace.
https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_24.html

**Comment by dbluelle** [comment]
This game uses some invalid code for obfuscation, I don't know yet how to handle that properly.
