### ISSUE TITLE
Bubble Trouble unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#465]
Lightspark version: `0.8.2-493-g57b872cd`

swf: [bubbletroublewm.zip](https://github.com/lightspark/lightspark/files/4305350/bubbletroublewm.zip)

The error appears shortly after loading into the main menu. The main error seem to be
```
Type Coercion failed: cannot convert MovieClip to flash.ui::ContextMenu.
```

**Comment by dbluelle** [comment]
this is fixed by https://github.com/lightspark/lightspark/commit/94ac08ca2cab3272f8f87cfd7160d66fac93b3ab
