### ISSUE TITLE
Strike Force Heroes 2 unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#467]
Lightspark version: `0.8.2-507-ge4d51eec`

swf: [strike_force_heroes_2_official_.zip](https://github.com/lightspark/lightspark/files/4321188/strike_force_heroes_2_official_.zip)

Main error:
```
ERROR: Unhandled ActionScript exception in VM Error: Error #1024: Error #1024: Stack underflow occurred.
    at Logo_LogoBox/()
    at LoaderScreen/()
    at Main/()
```

Terminal output: [strike_force_heroes_2.log](https://github.com/lightspark/lightspark/files/4321189/strike_force_heroes_2.log)

**Comment by dbluelle** [comment]
this needs to be started with --ignore-unhandled-exceptions
