### ISSUE TITLE
Glitch - Homestuck, flicker and no audio

### ISSUE THREAD

**Issue by kenan1099** [lightspark/lightspark#489]
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

URL of file
FILE 1: https://www.homestuck.com/flash/hs2/00836/00836.swf
FILE 2: https://www.homestuck.com/flash/hs2/01070/01070.swf

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [x ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

```
INFO: Lightspark version 0.8.2-564-gb8650884 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ x] Linux: *Arch btw*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x ] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ x] I have reproduced the problem using the Lightspark command line executable
- [x ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

---

---

### Description of your issue

FILE 1 has audio, but has severe flicker. Also some blur effects are missing from the tall character in the background.
FILE 2 does not play audio and suffers from flicker as well.

**Comment by kenan1099** [comment]
[logs_lsprk.zip](https://github.com/lightspark/lightspark/files/4497948/logs_lsprk.zip)

**Comment by eiglow** [comment]
Specifically, it looks like `BlurFilter from Tag` and `ColorMatrixFilter from Tag` needs to be implemented.

Flickering is also present in a few other apps, like the intro of [Learn 2 Fly: The Emperor Strikes Back](https://github.com/lightspark/lightspark/files/4498354/learn_2_fly_the_emperor_strikes_back.zip).

In the second file, 01070.swf, there's several instances of
```
[mp3 @ 0x7fc994001980] Failed to read frame size: Could not seek to 1026.
ERROR: invalid streamDecoder
```
Yet the audio works fine on Adobe Flash. Lightspark uses ffmpeg for mp3 decoding right? What are the differences between Adobe's mp3 decoding and Lightspark's mp3 decoding? I used [jpexs-decompiler](https://github.com/jindrapetrik/jpexs-decompiler) to get the mp3 file from 01070.swf, and playing it directly with mpv worked fine for me, which confuses me more.

**Comment by dbluelle** [comment]
The sound issue is fixed, but the flickering still occurs
