### ISSUE TITLE
liblightsparkplugin.so not loading on recent firefox

### ISSUE THREAD

**Issue by newperson1746** [lightspark/lightspark#495]
Just compiled git HEAD. Symbolic linked /usr/lib/mozilla/plugins/liblightsparkplugin.so ( and libflashplugin.so, perhaps they have a whitelist now) to /usr/local/lib/mozilla/plugins/liblightsparkplugin.so, copied the plugin instead of symlinking in case firefox doesn't like symlinks, tried copying and symlinking under both names in ~/.mozilla/plugins, nothing. It's as if it doesn't exist. Nothing under about:addons or about:plugins (the cisco h264 .so is loaded though, from a hardcoded path in config i think)

Ubuntu 20.04, tested with both firefox nightly 77.0a1 and distro firefox 75.0. 

UPDATE: Also tested chromium snap. based on https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1771162 I copied libpepflashplayer.so to ~/snap/chromium/current/.local/lib/libpepflashplayer.so. It is successfully picked up by the chrome startup script as seen in ps aux:
`/snap/chromium/1105/usr/lib/chromium-browser/chrome --no-default-browser-check --no-first-run --password-store --ppapi-flash-path=/home/daniel/snap/chromium/1105/.local/lib/libpepflashplayer.so --ppapi-flash-version`
After toggling the switch under preferences:site settings:"block sites from running flash (recommended)" to "ask first", Flash doesn't load because the ppapi-flash-version is missing. I copied the command and ran it in a terminal and set ppapi-flash-version=12 (any number works) and it loads and works in some websites.

**Comment by dbluelle** [comment]
Where did you put liblightspark.so (it's usually in /usr/lib/lightspark or /usr/local/lib/lightspark when installed via make install) ?
AFAIK for chromium you also have to put manifest.json into the same directory as libpepflashplayer.so

**Comment by newperson1746** [comment]
/usr/local/lib prefix doesn’t work for Mozilla’s plugins so I tried /usr/lib/mozilla/plugins as well as ~/.mozilla/plugins, no dice.

**Comment by dbluelle** [comment]
Just to clarify, I was asking about liblightspark.so (the base library that the plugins link to) .
If I understand you correctly, you are running the browser from a snap and want to use lightspark from inside the snap, right?
(Otherwise you can just do sudo make install and have everything properly installed system wide)
I don't know much about snaps, but I would think you have to somehow link lightspark against the libs inside the snaps, to avoid any inconsistencies with the system libraries.
I don't know if that is possible.

**Comment by clausghe** [comment]
I have similar problems with Firefox80 under Windows.
in extensions there is the np...dll listed for SWF types.
the dll is there but no swf content is showing up.

**Comment by huwdp** [comment]
I'm closing this as the latest version of firefox does not support plugins like Java, Flash, Lightspark and more. We have a page [here](https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser) that can get you up and running in alternative web browsers.
