### ISSUE TITLE
lightspark symbol not found- chromium DEB, ubuntu

### ISSUE THREAD

**Issue by newperson1746** [lightspark/lightspark#496]
Tested on http://www.viciouspotato.net/ (classic "lol limewire" mini animation)

HEAD, Ubuntu 20.04, Chromium snap 81.
 `/snap/chromium/1105/usr/lib/chromium-browser/chrome --type=ppapi --field-trial-handle=6314907767575176769,12066467370212901878,131072 --ppapi-flash-args --lang=en-US --shared-files: symbol lookup error: /home/daniel/snap/chromium/1105/.local/lib/libpepflashplayer.so: undefined symbol: _ZN10lightspark11AudioStream11startMixingEv
`

**Comment by dbluelle** [comment]
It seems that you have an older version of liblightspark.so installed somewhere in your system and the plugin tries to use that one.

**Comment by eiglow** [comment]
Here is the swf itself: [pirate.zip](https://github.com/lightspark/lightspark/files/4520186/pirate.zip)

**Comment by newperson1746** [comment]
I do not have an older version installed, this is my first time running lightspark... I ran a find / | grep lightspark just to be sure, and the only results were the files from my HEAD compile.

**Comment by dbluelle** [comment]
You should have liblightspark.so somewhere in your library path, otherwise the plugin will not run.
The alternative would be building lightspark with static linking, but I have never tried that.
Also as mentioned in https://github.com/lightspark/lightspark/issues/495,  using lightspark from inside the snap may need compiling it somehow against the snap libraries...

**Comment by newperson1746** [comment]
Okay. It's been a few months now and I was busy with school, but now I just got rid of the chromium snap since it would just give me an "operation not permitted" with HEAD libpepflashplayer.so. I used:
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev

I don't care much for google signin support anyway, so this'll work.

This time I had pepflashplayer in its default /usr/local/lib path, and passed it to chromium like this:
`chromium-browser --ppapi-flash-path=/usr/local/lib/PepperFlash/libpepflashplayer.so `

And... I get the famous 
```
INFO: download finished:pirate.swf 141920
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 2
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 2
INFO: AUDIO DEC: Initial timestamp 0
INFO: FPS: 0 0
/usr/lib/chromium-browser/chromium-browser --type=ppapi --field-trial-handle=7591324611162177225,5011577019045335001,131072 --ppapi-flash-args --lang=en-US --shared-files: symbol lookup error: /usr/local/lib/PepperFlash/libpepflashplayer.so: undefined symbol: _ZN10lightspark11AudioStream11startMixingEv
```
it still happens with an unsandboxed chromium like this, so something must be off? I can't figure out what is wrong.

**Comment by newperson1746** [comment]
It works!! This is a really big win for preservation. Adobe's official proprietary plugin obviously won't work as browsers and APIs move on, but it works with Lightspark! Quick demo here: https://www.youtube.com/watch?v=Uy37ssPOi3o

Thank you developers. This is amazing that history will be preserved like this.
