### ISSUE TITLE
Bloons Tower Defence regression

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#515]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

swf: [bloons_tower_defense_4.zip](https://github.com/lightspark/lightspark/files/4052144/bloons_tower_defense_4.zip)

#### Provide the complete set of instructions required to reproduce the problem:

Run ```lightspark bloons_tower_defense_4.swf```.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [x] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version
```
INFO: Lightspark version 0.8.2-622-g77c98ba4 Copyright 2009-2013 Alessandro Pignotti and others
```
Local build of master
#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: *KDE Neon 5.18*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

Game crashes on startup. I can see two problems via the log file I have included. One is:
```ERROR: Malformed SWF file: JPEGTable was expected before DefineBits```
The other one is: 
```
ERROR: trying to get variable on null:[ns:] currentFrame
INFO: throwing exception:1009 Error #1009: Cannot access a property or method of a null object reference.
    at &!::",/doFrameOne()
    at &!::",/stageAddedHandler()
    ```

**Comment by huwdp** [comment]
[bloons_tower_defense_4_error.log](https://github.com/lightspark/lightspark/files/4805716/bloons_tower_defense_4_error.log)

**Comment by dbluelle** [comment]
Are you sure this is the correct swf file?
I couldn't reproduce the crash, and according to your log it seems like it is from some swf file with obfuscated code, which bloons_tower_defense_4 is not.

**Comment by huwdp** [comment]
This is what I get. The code is up to date.
```huw@huw-desktop ~/flash % lightspark bloons_tower_defense_4.swf 
INFO: Lightspark version 0.8.2-626-gdd5f1083 Copyright 2009-2013 Alessandro Pignotti and others
INFO: RenderThread this=0x55ed25ad3b20
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 10
INFO: FrameRate 35
INFO: Creating VM
INFO: Switched to local-with-networking sandbox by FileAttributesTag
[mp3 @ 0x7f3b5002d840] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 22050
INFO: AUDIO DEC: Audio channels 1
[mp3 @ 0x7f3b50030760] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 1
[mp3 @ 0x7f3b50030760] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 1
[mp3 @ 0x7f3b50030760] Skipping 2 bytes of junk at 0.
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 1
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: FPS: 2 0
ERROR: not found:[ns:com.google.analytics.debug] _Style
INFO: existing frame label found:load, new value:load
INFO: existing frame label found:intro, new value:intro
INFO: existing frame label found:main, new value:main
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
INFO: dynamic cast:flash.net::URLRequest
INFO: NET: STANDALONE: DownloadManager::download 'http://www.google-analytics.com/__utm.gif?utmwv=4.3as&utmn=619109629&utmhn=localhost&utmcs=UTF-8&utmsr=1920x1080&utmsc=24-bit&utmul=en&utmje=0&utmfl=15.0%20r0&utmhid=47038756&utmr=-&utmp=/BTD4&utmac=UA-626139-8&utmcn=1&utmcc=__utma%3D111872281.652672058301512800.1592841629.1592841629.1592841629.1%3B%2B__utmz%3D111872281.1592841629.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B'
INFO: NET: STANDALONE: DownloadManager: remote file
INFO: NET: CurlDownloader::execute: reading remote file: http://www.google-analytics.com/__utm.gif?utmwv=4.3as&utmn=619109629&utmhn=localhost&utmcs=UTF-8&utmsr=1920x1080&utmsc=24-bit&utmul=en&utmje=0&utmfl=15.0%20r0&utmhid=47038756&utmr=-&utmp=/BTD4&utmac=UA-626139-8&utmcn=1&utmcc=__utma%3D111872281.652672058301512800.1592841629.1592841629.1592841629.1%3B%2B__utmz%3D111872281.1592841629.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B
INFO: download finished:http://www.google-analytics.com/__utm.gif?utmwv=4.3as&utmn=619109629&utmhn=localhost&utmcs=UTF-8&utmsr=1920x1080&utmsc=24-bit&utmul=en&utmje=0&utmfl=15.0%20r0&utmhid=47038756&utmr=-&utmp=/BTD4&utmac=UA-626139-8&utmcn=1&utmcc=__utma%3D111872281.652672058301512800.1592841629.1592841629.1592841629.1%3B%2B__utmz%3D111872281.1592841629.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B 35
INFO: dynamic cast:flash.net::URLRequest
INFO: NET: STANDALONE: DownloadManager::download 'https://assets.nkstatic.com/nklogin/Banana.swf?gamename=BTD4'
INFO: NET: STANDALONE: DownloadManager: remote file
INFO: NET: CurlDownloader::execute: reading remote file: https://assets.nkstatic.com/nklogin/Banana.swf?gamename=BTD4
INFO: zlib compressed SWF file: Version 12
INFO: FrameRate 48
ERROR: Malformed SWF file: JPEGTable was expected before DefineBits
INFO: download finished:https://assets.nkstatic.com/nklogin/Banana.swf?gamename=BTD4 153019
ERROR: Trying to addListener an InteractiveObject that's already added.
NKBar v20150127.16.24.58 for BTD4 (production mode)
ERROR: trying to get variable on null:[ns:] currentFrame
INFO: throwing exception:1009 Error #1009: Cannot access a property or method of a null object reference.
    at &!::",/doFrameOne()
    at &!::",/stageAddedHandler()

ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
INFO: dynamic cast:TypeError
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
    at &!::",/doFrameOne()
    at &!::",/stageAddedHandler()

INFO: FPS: 20 38
INFO: FPS: 0 0
```

**Comment by dbluelle** [comment]
OK, no I can reproduce the issue.
(It's in the "banana.swf" that is downloaded by the main swf)
