### ISSUE TITLE
Potential optimisation

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#516]
Is there any way we could optimise the code here on line 217 in swf.cpp (https://github.com/lightspark/lightspark/blob/dd5f1083dbaa2f7866f0a79408cf7ec0237f5af3/src/swf.cpp#L217). The system adds a lot of unique numbers to the map and it does slow startup. I think it might impact grabbing unique string ids throughout the system as well.

**Comment by dbluelle** [comment]
Yeah, it should be possible to speedup the string generation at startup, but I doubt that it has a lot of impact afterwards. 
Grabbing the string IDs (or the strings by ID) is indeed quite costly, as it involves multithread locking, but we already try to avoid these lookups in a lot of situations.
I haven't found an example that really does a lot of these lookups during runtime.
