### ISSUE TITLE
MacOS Support request / Questions

### ISSUE THREAD

**Issue by KenaiTheWolf** [lightspark/lightspark#526]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [x] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [x] Mac OS X: *10.15 / 11*
- [ ] Other: *<specify OS and version here>*

### If this issue is a *feature request*:

Identify the type of request:

- [x] Support for a new OS: Native support for MacOS 10.15 or higher
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [x] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [x] Other subject matter not listed

---

My question is as such - is macOS support planned, and is it possible to build for macOS from source at the moment, would it be possible to get instructions for macOS if they differ significantly from linux?

**Comment by dbluelle** [comment]
We test building using llvm, so in theory it should be possible to build for MacOS as long as all dependencies are available.
However I don't have a Mac, so I can't help you here.

**Comment by KenaiTheWolf** [comment]
Is it possible for me to find a list of dependencies, and (maybe keep this open in case I have to use some weird Mac specific version) get the list here. I wouldn’t mind building the application for MacOS in a fork then providing a binary in said fork’s release tab.

**Comment by dbluelle** [comment]
Take a look at the list of libraries in the "Building and Installation" chapter in the README.md file.
They are all open source, so they should be available for MacOS.

**Comment by KenaiTheWolf** [comment]
So I took a look and searched the dependencies in homebrew (the package manager) cant find these:

- libavcodec
- libavresample
- libglew
- librtmp
- libavformat
- liblzma is now part of xz on MacOS

I will update later when I have more info, or if I can find a way to install these w/o using homebrew as they may just not be in homebrew.

**Comment by KenaiTheWolf** [comment]
FFMPEG contains the av libs, so installing that should put them on the system. 

libglew is just glew on macOS

so that just leaves librtmp, which I'll have to compile for macOS.

**Comment by KenaiTheWolf** [comment]
Ok, so I got all the libs installed, now I'm being stopped by an error message stating that x11 is required, I have XQuartz (the macOS x11 server) installed though, is there any way I could point the configuration script at XQuartz?

**Comment by masatake** [comment]
Here is an example of x11.pc:
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

xthreadlib=-lpthread

Name: X11
Description: X Library
Version: 1.6.7
Requires: xproto kbproto
Requires.private: xcb >= 1.11.1
Cflags: -I${includedir} 
Libs: -L${libdir} -lX11
Libs.private: -lpthread
```

This one is taken from Fedora 28.

**Comment by dbluelle** [comment]
X11 is only needed for the Firefox plugin on Linux.
I doubt that Firefox is using X11 on MacOS, so even if you manage to install X11, the plugin probably won't work.
So I suggest to disable building the Firefox plugin for now (set the cmake variable COMPILE_NPAPI_PLUGIN to OFF)

**Comment by KenaiTheWolf** [comment]
Gonna have to find a work around for that then, or something else, MacOS has an X11 server, XQuartz.
Both Safari and Firefox use the NPAPI plugin, so I need it to be able to use it.

**Comment by dbluelle** [comment]
OK, that means several modifications to the plugin sourcecode (look at all MOZ_X11 occurences in src/plugin/plugin.cpp and src/plugin/CMakeLists.txt)
I think for MacOS you have to set  ADD_DEFINITIONS(-DXP_UNIX) and ADD_DEFINITIONS(-DXP_MACOSX) in src/plugin/CMakeLists.txt and then implement event handling and drawing...

**Comment by KenaiTheWolf** [comment]
I know it's been a while since I've updated this issue, but I am still interested in getting this to build on macOS 11, (not targeting 10.15 or lower because there's not a point right now with MacOS 11 about to go into a GM candidate) - need to find an alternative to GNASH, I'm having issues getting it to compile. 

I just updated my fork to be in sync with the branch master today, the stable code gives me more time to fix issues.

Additionally, Safari 14 has completely stripped out the NPAPI, so I won't have to worry about getting that to draw using macOS' native API, so for now, I'm only going to try to get the chrome extension working in the future.

**Comment by LoganDark** [comment]
Please don't exclude macOS 10.14.

**Comment by KenaiTheWolf** [comment]
> Please don't exclude macOS 10.14.

So, I've not updated in a while because my time has been consumed by work. However, I unfortunately don't intend to compile or even ensure compatibility with 10.14 for the reason that, I no longer have a system with it and I'm uncomfortable putting my name (even my screen name) on something that I can't test. When I find time and have a break from work and my more pressing projects I need to finish I plan to build for OS 11. I won't be testing on or helping with issues on anything older. You're welcome to try it yourself but again - I can't support something I don't have anymore. 

Presently I'm still stuck getting GNASH to work as I can't find the repo off of GNU.

**Comment by huwdp** [comment]
Work is affecting me too so I haven't had much time to work on a PR for Lightspark, so I feel your pain too. Gnash is optional and Lightspark is starting to support AV1 so no need to compile unless I'm missing something.

**Comment by KenaiTheWolf** [comment]
> Work is affecting me too so I haven't had much time to work on a PR for Lightspark, so I feel your pain too. Gnash is optional and Lightspark is starting to support AV1 so no need to compile unless I'm missing something.

Unsure, I'll look into it, if AV1's current package has any x32 in it, I'll have to recompile to a strictly x64 binary, but that's the only hang up that might happen. I'm going to check if it's available on my package manager and go from there.

**Comment by dbluelle** [comment]
Just to clarify:
Gnash is not needed to compile lightspark. It was only used as a fallback for AVM1 based swf files, but even that is no longer the case as lightspark supports AVM1 directly for quite some time now.

**Comment by KenaiTheWolf** [comment]
> Just to clarify:
> 
> Gnash is not needed to compile lightspark. It was only used as a fallback for AVM1 based swf files, but even that is no longer the case as lightspark supports AVM1 directly for quite some time now.

Made a few checks, I've got a copy of GNASH now that appears to work on my system. I'm unsure if AVM1 is supported by default by chrome (hopefully it is) however either way, if it isn't I'm planning on compiling with GNASH available so I can fall back on it. 

I may attempt to make a chromium plugin that uses gnash and one that relies strictly on AVM1 to see which works the most reliably.

**Comment by KenaiTheWolf** [comment]
Closing this, I've decided not to pursue this any further. While it was good to work on for a while, I like the direction of another emulator which isn't platform dependent and doesn't require the user to install a plugin or browser extension to use.

**Comment by SealsRock12** [comment]
Would you mind sending the name/repo of this "another emulator?"

**Comment by KenaiTheWolf** [comment]
I’m using ruffle. Works fine for what I need.

**Comment by SealsRock12** [comment]
Oh ok, that didn't work for my application.
For what you've done, have you came across the following error?
```
/path/to/lightspark/src/scripting/flash/utils/Timer.h:36:1: error: expected class-name before '{' token
```
That line has
```c
class Timer: public EventDispatcher, public ITickJob
```
and `EventDispatcher` is in `scripting/flash/events/flashevents.h`, which `Timer.h` includes.

**Comment by KenaiTheWolf** [comment]
I'm unable to help with that error unfortunately. My only goal here was to get lightspark compiled for macOS. I don't possess the knowledge to to much else other than that.
