### ISSUE TITLE
Building lightspark gives following errors on Ubuntu 

### ISSUE THREAD

**Issue by AveLexinton** [lightspark/lightspark#532]
I ran the following steps:
Step1: sudo apt install git gcc nasm cmake libcurl4-gnutls-dev libsdl2-mixer-dev libsdl2-dev libglibmm-2.4-dev libpango1.0-dev libcairo2-dev libavcodec-dev libavresample-dev libglew-dev librtmp-dev libjpeg-dev libavformat-dev liblzma-dev
Step2: ./build
but got the following errors:
...
-- Looking for avcodec_decode_audio3
-- Looking for avcodec_decode_audio3 - not found
...
[  1%] Generating pl.gmo
make[2]：GETTEXT_MSGMERGE_EXECUTABLE-NOTFOUND：Command not found
make[2]: *** [CMakeFiles/translations.dir/build.make:64：pl.gmo] Error127
make[1]: *** [CMakeFiles/Makefile2:167：CMakeFiles/translations.dir/all] Error 2
make: *** [Makefile:152：all] Error 2

**Comment by alibell** [comment]
I finally found out what's wrong.

The GETTEXT_MSGMERGE_EXECUTABLE results from the absence of the gettext package.
You should install it : sudo apt install msgmerge, remove the obj folder then try again.
