### ISSUE TITLE
Endless War Defense - locations not selectable

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#554]
swf: [endless-war-defense-6121.zip](https://github.com/lightspark/lightspark/files/4259095/endless-war-defense-6121.zip)

I think this has also been around since 5e9768248d0888a57be743c9a94a200e473fe2cf, I could be wrong though.

On the location select screen, after clicking Campaign and choosing a nation, it is impossible to select a location on the map. Hovering seems to randomly work, but the hitboxes for that are way off from where they should be.
![image](https://user-images.githubusercontent.com/16441870/99141557-5e132a00-269c-11eb-8ab0-7f5bf301c8b8.png)

**Comment by eiglow** [comment]
As of now, this seems to be kind of fixed (or maybe I just didn't initially test thoroughly enough), but either way, its still difficult to hit these buttons. Maybe some problem with the click hitboxes?

**Comment by huwdp** [comment]
I've had issues with hit boxes on other Flash files too. I don't know how this works internally but I might _try_ to fix this
