### ISSUE TITLE
Bloons TD 4 - intro flickering

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#555]
[SWF](https://github.com/lightspark/lightspark/files/4052144/bloons_tower_defense_4.zip)

The intro Ninja Kiwi clip flickers pretty badly. I recorded it here: https://youtu.be/-xrSugkb0X0

**Comment by huwdp** [comment]
https://github.com/lightspark/lightspark/issues/556#issuecomment-727638670
