### ISSUE TITLE
Johnny Upgrade - frequent segfault

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#557]
[SWF](https://github.com/lightspark/lightspark/files/4244099/mochi_johnnyupgrade1.zip)

This is on commit 206f2eab74e54af6277274efde27df34fb287557.

Game needs to be run with `-ne`.

In my testing, it segfaults during or immediately after the loading screen about 80% of the time. However, when trying to redirect terminal output to a log-file, it doesn't crash, instead coming up with an unsupported error:
```
Error #1009: Cannot access a property or method of a null object reference.
    at Class/loadError()
```
[Here](https://github.com/lightspark/lightspark/files/5541747/ju.log) is my terminal output.

Overall though, the behaviour of this game seems a bit random.

**Comment by huwdp** [comment]
I'll have a look at this soon as 206f2ea is my commit
