### ISSUE TITLE
Dead Zed 2 - unsupported error

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#560]
[SWF](https://github.com/lightspark/lightspark/files/4478618/deadzed2.zip)

To reproduce the error, click the Play button, and then wait for the notdoppler intro to finish.

```
Error #1024: Stack underflow occurred.
    at com.quasimondo.geom::ColorMatrix/concat()
    at com.quasimondo.geom::ColorMatrix/colorize2()
    at Singleton::GameWorld/()
    at Class/instance()
    at Main/init()
    at Preloader/startup()
    at Preloader/onBrandingMovieComplete()
```

I think this started happening somewhere between 5d39de4414546d70b5bdfb84abc24293a0d9adc9 and 206f2eab74e54af6277274efde27df34fb287557, but my bisecting was cut short because the Play button stopped appearing. I might try to do some more bisecting soon.

**Comment by huwdp** [comment]
I'll try this on my machine and see if my changes broke anything. Thanks for testing and reporting these issues

**Comment by huwdp** [comment]
I had a look yesterday and found my changes aren't causing the issues here

**Comment by eiglow** [comment]
I did some more testing. I think the first commit where the Play button does not show is 5d39de4414546d70b5bdfb84abc24293a0d9adc9.
