### ISSUE TITLE
Bloons - Incorrect cyling through scenes

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#566]
[SWF](https://github.com/lightspark/lightspark/files/5554613/bloons.zip)

Tested on current master of 2b12cfd.

The game must run with `-s local-with-networking`.

After the Ninja Kiwi splash, the game rapidly cycles through various scenes and animations on its own, endlessly.

[Here](https://github.com/lightspark/lightspark/files/5554642/bloons-l4.zip) is my `-l 4` terminal output.

**Comment by dbluelle** [comment]
cycling is fixed, but now the main menu is not displayed. 
I don't know how that should normally work.
I haven't found any actionscript code that displays the main menu after showing the intro.
The file is obfuscated so it may use some undocumented feature...
