### ISSUE TITLE
Bubble Tanks 1, 2, and 3 - loading forever or not working

### ISSUE THREAD

**Issue by BojayB** [lightspark/lightspark#575]
### What is the purpose of your issue?
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

http://i.notdoppler.com/files/bubbletanks.swf
http://i.notdoppler.com/files/bubbletanks2.swf
cache.armorgames.com/files/games/bubble-tanks-3-10015.swf

#### Provide the complete set of instructions required to reproduce the problem:

1. Download swf
2. Drag and drop swf onto Lightspark.exe / set swf files to always open with Lightspark.exe
3. Wait indefinitely for swf to load

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [X] **Broken**: Lightspark shows something, but most of the file is not usable

#### Provide the Lightspark version

0.8.3

Output of lightspark :

https://pastebin.com/XYB03BV5

#### What operating system are you are running on?

- [X] Windows 10

#### How are you are running Lightspark?

- [X] Lightspark executable

#### Which of these actions you have taken to help debug the problem?

- [X] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it 
---

### Description of your issue

Every time I try to launch one of the Bubble tank games, it either says "Loading" forever or crashes. I'll try the browser plugin and if that works than fine but I'd really like to be able to own these SWF files and play them locally. Thank you!

![image](https://user-images.githubusercontent.com/41974762/100806240-1b708200-33fe-11eb-968c-c521157dc1eb.png)
![image](https://user-images.githubusercontent.com/41974762/100806259-24615380-33fe-11eb-8a44-e090d234ab54.png)
![image](https://user-images.githubusercontent.com/41974762/100806287-2d522500-33fe-11eb-8269-872199668bdf.png)

**Comment by eiglow** [comment]
I am testing on the current master, which is 0c5f4e34b72e8b07013b2360a0fe3867a2a16fd7 at this time.

- **Bubble Tanks 1** seems to kind of get to the main menu, but it's not really usable.
![image](https://user-images.githubusercontent.com/16441870/101121034-09315680-363f-11eb-8a82-f6f24b492f92.png)
[Here](https://github.com/lightspark/lightspark/files/5640566/bt1-l4.log) is my terminal output with `-l 4`. Here's a few `NOT_IMPLMENTED` lines I saw, though there were more:
```
NOT_IMPLEMENTED: CLIPEVENTFLAG ClipEventRollOut not handled
NOT_IMPLEMENTED: CLIPEVENTFLAG ClipEventRollOver not handled
```
```
NOT_IMPLEMENTED: DefineFontAlignZonesTag Tag
```

- **Bubble Tanks 2** also doesn't get past the loading bar.
![image](https://user-images.githubusercontent.com/16441870/101121061-1e0dea00-363f-11eb-9275-cc0500367f8b.png)
[Here](https://github.com/lightspark/lightspark/files/5640569/bt2-l4.zip) is my terminal output with `-l 4`. Towards the end, it complains about this a few times:
```
NOT_IMPLEMENTED: AVM1:319 0 ActionGetMember for scriptobject type Undefined loadClip
NOT_IMPLEMENTED: AVM1:319 0 ActionGetMember for scriptobject type Undefined load_txt
NOT_IMPLEMENTED: AVM1:319 0 ActionSetMember for scriptobject type Undefined 4 text
```

- **Bubble Tanks 3** had the same unsupported error.
```
Error #1009: Cannot access a property or method of a null object reference.
    at /()
    at PlayerProfile/()
    at Main/()
```
[Here](https://github.com/lightspark/lightspark/files/5640593/bt3-l4.zip) is my terminal output with `-l 4`.

**Comment by dbluelle** [comment]
Bubble Tanks 1 works with current master
