### ISSUE TITLE
Bloons TD 4 - freeze after difficulty selection

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#579]
[SWF](https://github.com/lightspark/lightspark/files/4052144/bloons_tower_defense_4.zip)
This occurs since 7ec8f7a1307f1ee08c79b7644f16f28baffed8d8.

To reproduce:
1. Wait for the intro to finish.
2. Click 'New Game'
3. Choose a track
4. Choose a difficulty

Prior to this commit, an animation of the tower unlocking would play. Since this commit, the game appears to hang.

Before the commit:
![image](https://user-images.githubusercontent.com/16441870/101303710-8d2d4d80-388e-11eb-9ed3-8ed4b899fba2.png)

After the commit:
![image](https://user-images.githubusercontent.com/16441870/101303604-535c4700-388e-11eb-9b4f-0ec90ef4918f.png)

**Comment by dbluelle** [comment]
It seems that some of the latest commits have fixed this

**Comment by eiglow** [comment]
I'm not sure this issue has been fully fixed, I still run into it.
