### ISSUE TITLE
Controlling RNG seed through commandline

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#586]
Some games make heavy use of RNG, which makes it really annoying to reproduce and try to demonstrate issues which only present themselves as a result of this RNG. A means to control this RNG, like setting a specific `srand()` seed with a commandline argument would be really useful.

**Comment by dbluelle** [comment]
I've added an environment variable (LIGHTSPARK_RANDOM_SEED) to set the random seed.
IMHO it's better than a commandline argument as it can also be set when using the browser plugins.
