### ISSUE TITLE
frontend executable won't link (undefined references)

### ISSUE THREAD

**Issue by niansa** [lightspark/lightspark#589]
Okay sorry but this template is entirely unapropriate for my issue lol

Long story short, I am on Kubuntu 20.04 (64 bit). I downloaded latest tag (0.8.3), issued following commands:
 1. `mkdir builddir && cd builddir`
 3. `cmake -DCMAKE_BUILD_TYPE=Release ..`
 4. `make -j4`

Waited for a while, waited for stuff to compile. But then, when linking `../x86_64/Release/bin/lightspark` I got these undefined references:
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `pango_font_family_get_face'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_uri_split_network'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_uri_is_valid'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_uri_join'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_uri_split_with_user'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_file_set_contents_full'`
`/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `pango_font_map_get_family'`
And the build failed.

**Comment by niansa** [comment]
The issue might be that I have multiple gtk versions installed (one of which is master branch of gtk with breaking changed)

**Comment by huwdp** [comment]
I was able to spin up a Kubuntu 20.04 machine and build Lightspark with commands below.

```sudo apt install git gcc nasm cmake libcurl4-gnutls-dev libsdl2-mixer-dev libsdl2-dev libpango1.0-dev libcairo2-dev libavcodec-dev libavresample-dev libglew-dev librtmp-dev libjpeg-dev libavformat-dev liblzma-dev
sudo apt-get install gettext
sudo apt-get install build-essential
cd lightspark
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install```

These are the libs I have installed on the VM:
        libpangoxft-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangoxft-1.0.so.0
        libpangoxft-1.0.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangoxft-1.0.so
        libpangoft2-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
        libpangoft2-1.0.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangoft2-1.0.so
        libpangocairo-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
        libpangocairo-1.0.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libpangocairo-1.0.so
        libpango-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpango-1.0.so.0
        libpango-1.0.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libpango-1.0.so
        libgio-2.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgio-2.0.so.0
        libgio-2.0.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libgio-2.0.so

**Comment by dbluelle** [comment]
The undefiened references are not from methods that lightspark uses directly, so there is something wrong with the dependencies between the pango/cairo/gio libraries.
The error message shows that it tries to link to libraries in /usr/local/lib, maybe there is something mixed up with the libs in /usr/lib.

**Comment by niansa** [comment]
I reinstalled my linux, it is solved now :-)
