### ISSUE TITLE
Hero Fighter - buttons and text render incorrectly

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#593]
[SWF](https://drive.google.com/file/d/1sP0U7bz2XWSgZrYW1Qrubd9ooRFXszM-/view?usp=sharing)
Tested on current master (edf083bf4c90228cb57347915b5ca4cf9937939f)

Lightspark:
![image](https://user-images.githubusercontent.com/16441870/102945795-b98fcd80-450e-11eb-90c7-7b0f4bbe0ec2.png)

Adobe Flash:
![image](https://user-images.githubusercontent.com/16441870/102945776-af6dcf00-450e-11eb-8324-652430fe715a.png)

**Comment by huwdp** [comment]
Some of the filters listed here (https://huwdp.github.io/Flash-Matrix/) are missing hence why some things like buttons are missing glow, dropshadow, etc

**Comment by eiglow** [comment]
Testing on current master (12e20a4675ee5a2bb888f4f3eea1507bc7962797), and it looks better.
![image](https://user-images.githubusercontent.com/16441870/105139548-5bbec780-5b46-11eb-8640-68afc685e885.png)
