### ISSUE TITLE
Lightspark is not working properly on HomestarRunner.com (issues with older flash support)

### ISSUE THREAD

**Issue by stux2000** [lightspark/lightspark#595]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [X] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

Lightspark is not working properly on HomestarRunner.com (issues with older flash support)

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

https://homestarrunner.com/
https://homestarrunner.com/main17.html
http://www.homestarrunner.com/sbemail.html
http://www.homestarrunner.com/vcr_homsar.html
http://www.homestarrunner.com/vcr_marzy.html
http://www.homestarrunner.com/toons.html
http://www.homestarrunner.com/games.html
http://www.homestarrunner.com/stinkogame/v7/stinkogame.html

The only one I've seen working but it links to pages that don't work:
http://www.homestarrunner.com/characters2.html

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

Most of the items are accessible via the H*R Wiki:
http://www.homestarrunner.com/main17.swf (source: http://hrwiki.org/wiki/Main_Page_17#External_Links )
http://www.homestarrunner.com/sbemail_compe.swf (source: http://hrwiki.org/wiki/Strong_Bad_Email#External_Links )
http://www.homestarrunner.com/characters.swf (source: http://hrwiki.org/wiki/Character_Videos#External_links )
http://www.homestarrunner.com/vcr_homsar.swf (source: http://hrwiki.org/wiki/Homsar%27s_Character_Video#External_Links )
http://www.homestarrunner.com/vcr_marzy.swf (source: http://hrwiki.org/wiki/Marzipan%27s_Character_Video#External_Links )
http://www.homestarrunner.com/tvguide.swf (source: http://hrwiki.org/wiki/TV_Time_Toons_Menu#External_Links )
http://www.homestarrunner.com/gamesmenu_new.swf (source: http://hrwiki.org/wiki/Scrolling_Shooter_Games_Menu#External_Links )
To download Stinkoman please follow the instructions here:
http://hrwiki.org/wiki/Stinkoman_20X6_Source_Files
Almost the entire site is linked here: 
http://hrwiki.org/wiki/User:Purple_Wrench/Homestar_Offsite/hsr-root

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page. (Most items fail to load properly or they play automatically but with issues)

Other:
* For Main Page 17, hover the mouse over the buttons to see different actions 
* For the Games Menu, move the mouse around to move the ship (eventually it can collect a "pill"), click on an enemy ship to select a game to play (doesn't work)
* For the Character Videos: clicking on any tape leads to the actual character video. Clicking "eject" reveals the Homsar video (these work)
* For the TV Guide: clicking on the buttons reveals different menus. Clicking on a title plays the toon (these don't work)

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [X] **Broken**: Lightspark shows something, but most of the file is not usable
- [X] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.3-804-gedf083bf Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: * Debian GNU/Linux 10 (buster)  (10.3)*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [X] Browser plugin for other browser: *Pale Moon (NPAPI)*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

The logs can be found here (one file is for testing stinkoman, the other has everything else):
https://github.com/stux2000/TUP_Releases/tree/master/_other/2020/20201225_lightspark_logs

---

### Description of your issue

I've been documenting my tests here: http://hrwiki.org/wiki/User:Stux/Flash2021
This issue can be linked to: https://github.com/lightspark/lightspark/issues/339
I currently am unable to test with Gnash due to this issue: https://askubuntu.com/questions/1293850/build-gnash-on-ubuntu-20-04

Here are my test results:
-try to compile and run latest trunk, see if AVM1 support has improved. (Done)
-Sadly, although there were improvements, they did not work as expected. At least the number of AVM1 errors were reduced.
-However, when playing video the sound was glitched: it started over and became out of sync with the video
-Most video has artifacts and did not display properly
-Main Menu, toons menu, games menu did not work. 
-Stinkoman did not work either (black screen after briefly showing "loading..." message)
-The Characters menu was the only thing that worked correctly (even the eject button worked!). 
-The Strong Bad Email menu loaded partially. 

Specific notes:
* Character videos (vcr_homsar.swf and vcr_marzy.swf):
  * The sound plays out of sync in both videos, it restarts several times in vcr_marzy.swf
  * There are ghosted artifacts in both videos (however the "VCR effect" grain is part of the original video)
* Games Menu:
  * Only one option is displayed, all others are missing 
  * The one remaining option cannot be clicked 
  * Moving the ship left and right does work, as does collecting the 'pill' that occasionally appears 
* Main Page 17:
  * Homestars face disappears after other animation
  * Hovering over each button is supposed to do 'something', only one of these ("are you asking for a challenge?") seems to work properly 
  * Sound mostly doesn't work except for the one item, but sound breaks when that one item ("are you asking for a challenge?") is played a second time
* Strong Bad Email Menu:
  * Mostly seems to work ("prrr" glitch near the end is a known glitch of the original video, reproducible in flash)
  * When loading from the website all items show up as "undefined" and nothing is selectable
* TV Guide:
  * AVM1 error 
* Stinkoman:
  * Only initial "Loading..." message is briefly displayed. Nothing else works 
  * (Ironically, v0.8.3 displayed the Videlectrix marquee intro, but stopped working afterwards

**Comment by dbluelle** [comment]
It seems that the last remaining issue ("Strong Bad Email Menu") was solved by one of the recent commits, so I'm closing this
