### ISSUE TITLE
Hero Fighter - segmentation fault

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#610]
[SWF](https://drive.google.com/file/d/1sP0U7bz2XWSgZrYW1Qrubd9ooRFXszM-/view?usp=sharing)
I think this was introduced by commit c84b8a13791c40fa7458fe543c862e3405a4e93d, although it didn't build for me, so I tested on e47825a550c38bddecfb7ce1e7a0247673a59aa4.

The terminal output just before crashing is this:
```
ERROR: Can't allocate large texture... Aborting
```

[Terminal output](https://github.com/lightspark/lightspark/files/5768783/hf.log)

[`-l 4` terminal output](https://github.com/lightspark/lightspark/files/5768788/hf-l4.zip)

**Comment by dbluelle** [comment]
I couldn't reproduce this, does it still occur with the current master?

**Comment by eiglow** [comment]
As of c5a676624f7db02448746ef382aaa5958a2caa70 I can't reproduce this anymore.
