### ISSUE TITLE
Run Adobe Captivate EXE files.

### ISSUE THREAD

**Issue by BenCrawford** [lightspark/lightspark#620]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [x ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

Will this product Install via the windows 64 bit exe installer and make the library visible for Adobe Captivate exe files to run? Adobe Captivate exe files still rely on flash and can still be published as exe files but requires flash to publish. We have a collection of training courses that are going away in the next month or 2 but still need to be usable as of right now. I installed this application and it seems that either A the library needed isnt there or B it isnt installing correctly where it may need these files to be available. Any help would be appreciated.

**Comment by dbluelle** [comment]
I close this as it is also discussed in https://github.com/lightspark/lightspark/discussions/622
