### ISSUE TITLE
having trouble installing

### ISSUE THREAD

**Issue by phantomDragon533** [lightspark/lightspark#641]
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [x] If none of the above apply, check this box.
--
- [x] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*
--
- [x] Browser plugin for Chrome or Chromium: *latest Chrome version*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [ ] Lightspark executable on the command line
--
I've been having trouble installing Lightspark, I have tried to figure out what to do after running the install program to install the plugin it self but I'm at a lost, what do I do next to install it into chrome?

**Comment by dbluelle** [comment]
this is already discussed in https://github.com/lightspark/lightspark/discussions/627
