### ISSUE TITLE
The World's Hardest Game - Only able to use one movement key at a time

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#643]
[SWF](https://github.com/lightspark/lightspark/files/5016584/the-worlds-hardest-g-1043.zip)
Testing on current master (19f270943897ef45e30d815fa3044bd03e61587b)

When in-game, it is impossible to move diagonally, because only the last pressed movement key seems to register, as if the previously held movement keys were let go, even though they weren't.

This video demonstrates my attempts to move diagonally.

https://user-images.githubusercontent.com/16441870/106698451-bcfb9600-6630-11eb-9451-8b4a385a0e37.mp4

**Comment by Geo25rey** [comment]
Also, in-game collision logic doesn't work
