### ISSUE TITLE
"Cannot initialize GLEW" with SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#645]
Tested on current master (19f270943897ef45e30d815fa3044bd03e61587b)
I used [this](https://github.com/lightspark/lightspark/files/5923998/Snake.zip) very small and simple game to test.

When starting lightspark using `SDL_VIDEODRIVER=wayland lightspark <file.swf>` in a Wayland session, there is the following error:
```
ERROR: Cannot initialize GLEW: cause Unknown error
ERROR: Exception in RenderThread, stopping rendering: Rendering: Cannot initialize GLEW!
```

I tested this in a KDE Plasma 5.21 Beta Wayland session.

**Comment by dbluelle** [comment]
That seems to be a bug in glew (see https://github.com/nigels-com/glew/issues/172).
As a workaround you can try to build lightspark using OpenGL-ES (cmake -DENABLE_GLES2=TRUE).
Currently glew is not used for OpenGL-ES, so it may work.

**Comment by eiglow** [comment]
I tried that, unfortunately it didn't work.
```
ERROR: Unable to initialize SDL:wayland not available
ERROR: SDL initialization failed, aborting
```

**Comment by Geo25rey** [comment]
I've been using [glew-egl-glx](https://aur.archlinux.org/packages/glew-egl-glx/) from the Arch User Repository and using SDL_VIDEODRIVER=wayland without any issues. 

This is an issue with glew not supporting Wayland (yet) in their main "glew" package. They do have a "glew-wayland" package, but it doesn't provide the "glew" package making it useless.
