### ISSUE TITLE
Snake - buttons not clickable

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#646]
Tested on current master (19f2709)
[SWF](https://github.com/lightspark/lightspark/files/5923998/Snake.zip)

The "Slug", "Worm", and "Python" buttons are not clickable as they are on Adobe flash.

[Terminal output with `-l 4`](https://github.com/lightspark/lightspark/files/5924052/snake-l4.log)

**Comment by huwdp** [comment]
Lots of games on spreadsheet here (https://docs.google.com/spreadsheets/d/164grNRLLLePg-MIdMbEQDwTwsl6FocYC_PMI052ThI8/edit?usp=sharing) have issues with pressing play buttons.

Similar issue: https://github.com/lightspark/lightspark/issues/672 but cannot click and hold down to shoot arrow
