### ISSUE TITLE
Don't Escape 2 - should use nearest-neighbor scaling for sprites

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#662]
Tested on current master (07e02db92482bcf187cec2df3015d39f076a9082)
[SWF](https://github.com/lightspark/lightspark/files/5963616/dont-escape-2-17657.zip)

(Screenshots are zoomed in for clarity)

On Adobe, the sprites shown correctly use nearest-neighbor scaling:
![image](https://user-images.githubusercontent.com/16441870/107612003-27e24800-6c95-11eb-9bb2-83f18610c529.png)

However, Lightspark appears to do linear scaling.
![image](https://user-images.githubusercontent.com/16441870/107612175-945d4700-6c95-11eb-9ef5-cb151c9d1e69.png)

**Comment by huwdp** [comment]
I think the same thing is happening for the pirate song in this comment here (https://github.com/lightspark/lightspark/issues/496#issuecomment-618207684)

**Comment by huwdp** [comment]
https://youtu.be/Uy37ssPOi3o

**Comment by huwdp** [comment]
So for Pirate song I went through commits and found that:

9591fe1f6a28d7555dced2333bca18cbafe2320f (works but with wrong filtering)
f6c4b2db70ed3a1e1cee516170434a10c167c0bb (segfault)
6151c6e01a3485440f12040c1fd52d0a1035ecde (segfault)
3ea36ecea04f8e1170443982eda9deabda3e6573 (works with correct filtering)

I have a suspicion that commit 9591fe1f caused the issue. I don't understand what the chunking and clamping is for so I can't fix this myself.
