### ISSUE TITLE
Flash site unable to load

### ISSUE THREAD

**Issue by kuberank** [lightspark/lightspark#665]
## In order to help us understand your issue, please follow the guide below

[x] I have installed "Lightspark-v0.8.4.1-Installer-win64" in my pc after that i checked my flash website not open still asking "To view this page ensure that Adobe Flash Player version 10.2.0 or greater is installed. " both chrome and firefox what needs to do please guide me.

---

### What is the purpose of your issue?
- [X ] Site Support Request: Lightspark does not work correctly on a specific website.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
Paste output here
```

#### What operating system are you are running on?

- [X] Windows  10

#### How are you are running Lightspark?

- [x ] Browser plugin for Chrome or Chromium: *<88.0.4324.150 >*
- [x ] Browser plugin for Waterfox: *<85.0.1>*

#### Which of these actions you have taken to help debug the problem?

- [x ] I attached a [screenshot](url
![refrence](https://user-images.githubusercontent.com/19552912/107766206-237f6300-6d59-11eb-8915-c7c024ad2047.PNG)
) of the problem to this issue

---

### If this issue is a *feature request*:

Identify the type of request:

- [ ] Support for a new OS: *<name the operating system here>*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

*Explanation of your issue in arbitrary form goes here.*

**Comment by huwdp** [comment]
I'll install Waterfox tomorrow and I'll see if I can get it working and add some notes to wiki on how to do it.

In regards to Chrome, that web browser no longer supports plugins like Lightspark. You can download swf files and run via command, so that's another option

**Comment by huwdp** [comment]
Give the link here (https://github.com/lightspark/lightspark/issues/613#issuecomment-761842776) a try but for Waterfox instead of Firefox. I haven't got it to work on my machine but I'm thinking it's due to me running Windows in a VM instead of on hardware itself. I can get the plugin to register in Waterfox but it does not display anything. Lightspark uses OpenGL and I'm not sure my VM can run it

**Comment by huwdp** [comment]
I haven't been able to get Lightspark working under Firefox or Chrome but I have under Pale Moon and Basilisk. Details here (https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser ).

**Comment by dbluelle** [comment]
I think we can close this
