### ISSUE TITLE
Hipland 3 unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#669]
Tested on current master (07e02db92482bcf187cec2df3015d39f076a9082)
[SWF](https://github.com/lightspark/lightspark/files/5986909/Hipland.3.zip)

Main error:
```
Error #1074: Illegal write to read-only property _url on MovieClip.
```

[Terminal output](https://github.com/lightspark/lightspark/files/5986918/hipland3.log)
[`-l 4` terminal output](https://github.com/lightspark/lightspark/files/5986917/hipland3-l4.log)

**Comment by huwdp** [comment]
Maybe same issue: https://github.com/lightspark/lightspark/issues/666

**Comment by eiglow** [comment]
I tested this on 07959bded1b48d4330b0c46676136eedc48a7d94 (commit before 6a572e6e854c4117e0e60a97bbf370108588018b) and there is no such error, so you're probably right.
