### ISSUE TITLE
Learn 2 Fly: Emperor Strikes Back - incorrect black covering

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#671]
[SWF](https://github.com/lightspark/lightspark/files/4259408/learn_2_fly_the_emperor_strikes_back.zip)
This occurs since 5e9768248d0888a57be743c9a94a200e473fe2cf or 0d1c72156de0dcdeb5a709a2937521fcb27bd3ea, I had to skip them when bisecting due to segfaults. I'm guessing it was introduced by the former.

Since then, Lightspark looks like this:
![image](https://user-images.githubusercontent.com/16441870/108044663-7a0adb00-7092-11eb-8ef6-0d813a8889de.png)

Adobe looks like this:
![image](https://user-images.githubusercontent.com/16441870/108044721-8b53e780-7092-11eb-8b37-bac44371bb55.png)

**Comment by Geo25rey** [comment]
I can reproduce this on the latest release, but when trying on the master branch version I can't reproduce this. Perhaps something already fixed it?

**Comment by eiglow** [comment]
Yeah, looks like 50a2e9ae42ba723ab4b2dc21a99851b08814d058 fixed it.
