### ISSUE TITLE
Consider updating pugixml

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#674]
There have been [many new versions](https://github.com/zeux/pugixml/releases) of pugixml since 1.6, often including performance/memory usage improvements. I'm not sure how much xml is typically used in swfs though, so I'm not sure how much impact this would have.

If/when updating pugixml, remember a25ad07e6bc72e134d34e0d36de1750280f55abf.

**Comment by dbluelle** [comment]
IMHO this would only have significant impact if the swf makes really heavy use of xml data.
However the XML/XMLList classes are also not very optimized at the moment, so there may also additional room for improvement.
But anybody feel free to create a pull request for a new version of pugixml.

**Comment by dbluelle** [comment]
I've pulled your PR, so we can close this.
