### ISSUE TITLE
Swords and Souls - misaligned text

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#683]
[SWF](https://github.com/lightspark/lightspark/files/4219029/swordssouls-17817.zip)
Tested on current master (99b2c706aa659c9786cf2acd9c48c84313faae2e)

Misaligned text in this fashion occurs all throughout this game, but I will focus on the example in the intro screen, that comes up first when starting the swf, after the initial loading is done.

Lightspark:
![image](https://user-images.githubusercontent.com/16441870/108851545-7815be80-7634-11eb-8719-bb70e58f6645.png)

Adobe:
![image](https://user-images.githubusercontent.com/16441870/108851603-88c63480-7634-11eb-825d-72e1957e3e80.png)

**Comment by huwdp** [comment]
dcdd0ea0e70ccf0acd2238d21fe6635300266021 commot may have fixed this. I'll test this out tomorrow

**Comment by eiglow** [comment]
I think that commit misaligned it in the other direction...
![Screenshot_20210228_113510](https://user-images.githubusercontent.com/16441870/109404759-0a152280-79b9-11eb-82d5-b91cf4a2381d.png)
