### ISSUE TITLE
Which browsers will continue support lightspark plugin?

### ISSUE THREAD

**Issue by inliquid** [lightspark/lightspark#684]
There is a following note in releases section:
> The currrent releases of Chrome and Firefox have removed support for the flash plugin completely, so the lightspark plugins will only work on older releases or alternative browsers.

So the question is: which browsers will still be able to run lightspark plugin to render flash?

**Comment by eiglow** [comment]
One browser I hear get recommended a bit is [Waterfox](https://www.waterfox.net/). I think a list of browsers should be added though.

**Comment by ReOne21** [comment]
Waterfox, probably Palemoon/Mypal and Basilisk

**Comment by Geo25rey** [comment]
Some alternatives are Falkon, Qutebrowser, and other QtWebEngine-based browsers. These web browsers provide a similar experience to the Chromium browsers while still supporting external plugins.

I'm not sure if Chromium itself supports external plugins like lightspark, but I have no reason to think it doesn't.

Note: Chromium is not the same thing as Google Chrome. Google Chrome does not support external plugins.

**Comment by huwdp** [comment]
See page here (https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser) for supported web browsers. Also please update the list if you can get Lightspark working in other web browsers.

**Comment by dbluelle** [comment]
I think we can close this
