### ISSUE TITLE
13 Days of Hell - std::bad_alloc issue

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#691]
A few games that I know of give an exception of "std::bad_alloc". These are 13 Days In Hell, 3D Ping Pong, Bubble Tanks, Dead Zed 2, Learn To Fly 2, Pandemic 2, Shadez 2, Bubble Tanks 2, Flashcraft Tower Defence and Doodle God 2.

In this case, I'll just concentrate on 13 Days In Hell as it throws exception straight away.

Steps to re-produce:
1. Download file included in issue.
2. Run 13 Days Of Hell in Lightspark and exception should appear straight away.

[13DaysInHell.zip](https://github.com/lightspark/lightspark/files/6057951/13DaysInHell.zip)

The number of games that work have gone up and I believe fixing this issue will make that number even higher.

**Comment by dbluelle** [comment]
I couldn't reproduce this issue.
I had a similar problem that I fixed yesterday in d194c9dd95c8eb3f042e94f2ceb1e3d21ecf9c48, so maybe you didn't have that commit included in your tests?

**Comment by huwdp** [comment]
Yes that's I was stuck on commit (9a223097ea6a15bb14f74836b7523d9ed63564cb). I'll redo the tests, thank you
