### ISSUE TITLE
latest 0.8.4.1 release fails to build on Mageia 7 (error: 'hit_count' was not declared in this scope)

### ISSUE THREAD

**Issue by david-geiger** [lightspark/lightspark#694]
hi,

I tried on Mageia 7 to build latest 0.8.4.1 release but it fails to build (while it build on Mageia 8) with:

`/home/iurt/rpmbuild/BUILD/lightspark-0.8.4.1/src/scripting/toplevel/toplevel.cpp: In member function 'void lightspark::SyntheticFunction::call(lightspark::asAtom&, lightspark::asAtom&, lightspark::asAtom*, uint32_t, bool, bool)':
/home/iurt/rpmbuild/BUILD/lightspark-0.8.4.1/src/scripting/toplevel/toplevel.cpp:386:69: error: 'hit_count' was not declared in this scope
  if(getSystemState()->useJit && mi->body->exceptions.size()==0 && ((hit_count>=jit_hit_threshold && codeStatus==method_body_info::OPTIMIZED) || getSystemState()->useInterpreter==false))
                                                                     ^~~~~~~~~
/home/iurt/rpmbuild/BUILD/lightspark-0.8.4.1/src/scripting/toplevel/toplevel.cpp:386:69: note: suggested alternative: 'ref_count'
  if(getSystemState()->useJit && mi->body->exceptions.size()==0 && ((hit_count>=jit_hit_threshold && codeStatus==method_body_info::OPTIMIZED) || getSystemState()->useInterpreter==false))
                                                                     ^~~~~~~~~
                                                                     ref_count
make[2]: *** [src/CMakeFiles/spark.dir/build.make:2315: src/CMakeFiles/spark.dir/scripting/toplevel/toplevel.cpp.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/lightspark-0.8.4.1/build'
make[2]: *** Waiting for unfinished jobs....`

Attached full build log:
[build.i586.0.20210302094908.log](https://github.com/lightspark/lightspark/files/6067920/build.i586.0.20210302094908.log)

**Comment by dbluelle** [comment]
Just for clarification:
You're building with the ENABLE_LLVM flag, which is unmaintained and broken for several years now.
I've fixed the so that it does compile, but the --enable-jit flag of the lightspark executable will definitely not work.
Unless somebody steps up and tries to fix this, it is better to compile without ENABLE_LLVM, especially when using a newer ( >7 ) llvm version.
