### ISSUE TITLE
8.3 version worked better than 8.4.1

### ISSUE THREAD

**Issue by filochard** [lightspark/lightspark#695]
## In order to help us understand your issue, please follow the guide below

---

### What is the purpose of your issue?
- [x ] Site Support Request: Lightspark does not work correctly on a specific website. (mine ! http://fildidier.free.fr/index.html on the panorama part)

I send you the link of a zip file to test one of the panoramas without having to use internet
http://dl.free.fr/bctUvZc0C
extract the zip in the proposed folder
click on the p08-murosenetosa.htm file to open it with Firefox
accept the flash plugin

#### What kind of failure is your issue?
- [ x] **Crash**:  sometimes The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [x ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.

#### Provide the Lightspark version
8.4.1 vs 8.3

#### What operating system are you are running on?
- [x ] Linux:  Mageia 8

#### How are you are running Lightspark?
- [x ] Browser plugin for other browser:  Firefox 78.8 ESR

### Description of your issue
The display is not smooth, the picture has horizontal white lines
the arrows allowing to zoom or to go to left or to right create saccades

**Comment by eiglow** [comment]
[Direct upload of swf](https://github.com/lightspark/lightspark/files/6096472/p08-murosenetosa_out.zip)

This is after using the left arrow for a bit:
![Screenshot_20210307_133458](https://user-images.githubusercontent.com/16441870/110227600-f1bd7e80-7f49-11eb-9bfa-d5418013a214.png)

**Comment by huwdp** [comment]
I'll git bisect through the code tomorrow and I'll try find what commit did this

**Comment by filochard** [comment]
Thanks for looking at it
Indeed my bug report was not clear
What I meant is : with version 8.4.1 I get the same distorded display as in your snapshot
With  8.3 version the display was  better : not distorded, after scrolling from left to right or reverse, but the pictures got some horizontal white lines,
 Besides that, when using the arrow it didn't scroll smoothly, and when using the zoom button it was not fluent...
Sometimes the buttons box was not displayed in the bottom of the screeen

PS It's better to use the htm file that calls the little javascript to read the swf file : the 3 of them need to be in the same directory

**Comment by filochard** [comment]
Nevertheless version 8.3 was not far to be as useable as flashplayer
Not the case with 8.4.1 (kind of a regression instead of an improvement)

Thanks for your job, that will prevent from disappear lots of work that had been done ... and are now like hieroglyph : they became un-understandable after having been a standard .

**Comment by dbluelle** [comment]
I've fixed the regression regarding the distorted display in https://github.com/lightspark/lightspark/commit/945687cdad8dbcdd4013fe0cd217341d09dba3cb, but I have not yet found a solution for the horizontal white lines...

**Comment by filochard** [comment]
Thanks for your work
I'm gonna try this

**Comment by filochard** [comment]
Hi 
So I tested the last git clone from today
It is indeed better than version 8.4.1 : quite the same as version 8.3 (no more regression)
But something disappeared : the possibility to use the mouse cursor to pan from left to right, or to use the scroll wheel to zoom

If you want test it you can use my photo site : http://fildidier.free.fr/index.html
you will see different problems depending of which pano you display : 
sometimes the buttons disappear 
sometimes they don't do what they are suppose to do (zoom instead of panning)
Sometimes the display remains grey (normally it's the preload that is grey when the picture is loading in the cache)
Sometimes its a garbage display
Sometimes the picture is totally distorted when panning

**Comment by filochard** [comment]
I spent hours to create those interactive panoramas displays... And since Adobe decided to leave the flash plugin it's unreadable !
I know I am not the only one who see his work destroyed .
My hope is that lightspark resuscitates all the sites that used Adobe Flash ... but I can imagine how hard it is to create such a substitute
