### ISSUE TITLE
Infectonator 2 - very low fps

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#698]
[SWF](https://github.com/lightspark/lightspark/files/4232200/Infectonator.2.swf.zip)
Tested on current master (d9e391616204edc271ac6389b92c3a78cd7311a1).

Seems to run at about 11-12 FPS, and as a result, the animations are very slow.

[Terminal output](https://github.com/lightspark/lightspark/files/6108667/inf2.log)

**Comment by huwdp** [comment]
11-12 FPS for me too. Seems that the FPS count stays like that no matter the machine.

**Comment by eiglow** [comment]
I don't think hardware matters much in this case, because I think lightspark is just running the game at an incorrect framerate.
