### ISSUE TITLE
Super Smash Flash 2: Cannot access a property or method of a null object reference.

### ISSUE THREAD

**Issue by James-Livesey** [lightspark/lightspark#702]
### What is the purpose of your issue?
- [x] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### Provide the complete URL of the page with the issue here:

https://www.mcleodgaming.com.gamecdn.online/files/theme/super-smash/game3.swf

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

N/A since game requires connection to CDN servers

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. Wait for full game to load (it may take a few minutes; there is also a black screen at the very start but the game does load) and navigate through menu, choosing characters and a level. (Choose first menu item for each just as a test.)
3. Just before the game was about to start, an error occurred.

#### What kind of failure is your issue?

- [x] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.4 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: *Debian GNU/Linux 10*
- [ ] Mac OS X:
- [ ] Other:

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium:
- [ ] Browser plugin for Waterfox:
- [x] Browser plugin for other browser: *Firefox Quantum ESR 68.12.0esr (64-bit)*
- [ ] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I attached a screen shot of the problem to this issue
- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable *N/A since game requires connection to CDN servers. Have tried but game detects it's running with no CDN connection*
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*) [Dump of last buffer lines from Firefox; unable to pipe the error messages to a file for some reason](https://pastebin.com/qrRW6nEb)

Screenshot (unfortunately low-res, but transcript is below):

![Screenshot image](https://i.ibb.co/fSgcLFD/image.png)

```
We're sorry, Lightspark encountered a yet unsupported Flash file
SWF file: https://www.mcleodgaming.com.gamecdn.online/files/theme/super-smash/game3.swf
Cause: TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
    at items_fla::capsule_mc_idle_4/frame470
    at Class/createHitBoxAnimation()
    at Class/prepOtherHitBoxStuff()
    at Class/startMatch()
    at com.mcleodgaming.ssf2.controllers::StageButton/startGame()
    at /()
Press Ctrl+C to copy this error to clipboard
```

**Comment by James-Livesey** [comment]
Similar to #282, however following those steps causes the game to think it's running in an unprivileged/cracked mode. It appears that the game must run in the browser for it to show the main menu.

**Comment by huwdp** [comment]
There have been a lot of fixes since version 0.8.4.(x) so this error is gone although the game is stuck at %5 on the progress screen, commit 23e7ed9fb. Run with ```lightspark game3.swf -s local-trusted```

Lots of errors in log such as ```ERROR: NET: LocalDownloader::execute: could not open local file: /home/huw/flash/data/DAT255.ssf``` so this might be another issue but I might be wrong.

**Comment by James-Livesey** [comment]
Same behaviour for me @huwdp! From what I have seen, SSF2 tries to download a bunch of game files which aren't part of the original SWF

Trying `lightspark -u https://supersmashflash2beta.com/ ssf2.swf` downloads these game files from a CDN but it gets stuck at 100%

This is also one I tried:
```bash
$ lightspark -u http://www.mcleodgaming.com.gameslol.net/SSF2/1032/ ssf2.swf
```

Here, it seems to get to 100%, and then it thinks it's in demo mode. Some weird DRM going on here! This is what it looks like:
![Woah Looks like you're trying to play the SSF2 Demo mcleodgaming.com](https://i.ibb.co/NjnMTrf/image.png)

The best I could get so far is running it in the browser. I tried with Chrome, but then went to Firefox since it's easier to configure with plugins. That's whne I could get through the menu and then eventually experience the crash

**Comment by James-Livesey** [comment]
If you want to test it out exactly like I did, try visiting in Firefox using Lightspark:
https://supersmashflash2beta.com/uploads/games/flash/super-smash-flash/

That's where I experienced the error, and I should imagine it's pretty reproducable

**Comment by dbluelle** [comment]
The problem is that the swf tries to download additional files, but the server always sends the same html page in return. The swf then tries to decompress that file and that obiously fails, as the data is not zip compressed stuff.
The url (e.g: "https://supersmashflash2beta.com/uploads/games/flash/super-smash-flash/data/DAT255.ssf") is always redirected to "https://supersmashflash2beta.com/" by the server.
I think we can't do anything unless someone knows which base url to use to find these files.

**Comment by huwdp** [comment]
I'd thought I'd link to this: https://www.mcleodgaming.com/2017/11/redirection-of-some-third-party-unauthorized-hosts. I can't read the text on the screen so not sure if the same text.

**Comment by James-Livesey** [comment]
> I'd thought I'd link to this: https://www.mcleodgaming.com/2017/11/redirection-of-some-third-party-unauthorized-hosts. I can't read the text on the screen so not sure if the same text.

From what I can see, it looks like similar text to what's shown in https://github.com/lightspark/lightspark/issues/702#issuecomment-798965951 but there are a few differences in the wording, such as 'the' appearing in my screenshot before the 'SSF2' bit (where it isn't there in the McLeodGaming screenshot), in addition to the word 'demo'.

I think these are different error messages but for the same general issue, though. I've been trying to find the official source for the .dat files that are downloaded to play SSF2 (seeing that SSF2 is prevalent on the MCLG website, the .dats must be somewhere...) but I've had no luck so far. If anybody can find the source paths for the .dats, that'd be great for us to try and test the game using a better root URL (passed by the `-u` param in Lightspark) as compared to the 404ing versions.

I think https://supersmashflash2beta.com is official, so it seems odd that the .dats would be taken down considering MCLG have instructions on how to play SSF2 post-Flash-death.

**Comment by dbluelle** [comment]
I got it working (with the latest commit) from command line with parameter `-u https://www.mcleodgaming.com.gamecdn.online/files/theme/super-smash/ `

**Comment by James-Livesey** [comment]
Great. Will do a few tests myself soon to see if the issue is all fixed!
