### ISSUE TITLE
Dead Zed 2 - scene background is black

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#707]
[SWF](https://github.com/lightspark/lightspark/files/4478618/deadzed2.zip) - Tested on latest master (23e7ed9fba4191864836ea9989a1392eedb0860d)

To get to this part in the swf, basically just progress through the menus until you get into the game itself:
1. Click the initial PLAY button, wait for the notdoppler intro to finish
2. Click PLAY
3. Click CONTINUE
4. Click CONTINUE

On Lightspark, the game looks like this:
![image](https://user-images.githubusercontent.com/16441870/111116505-05a25980-85b6-11eb-930c-d6bae6959735.png)

On Adobe, it looks like this:
![image](https://user-images.githubusercontent.com/16441870/111116560-1c48b080-85b6-11eb-89f8-39c3e45be56e.png)

**Comment by dbluelle** [comment]
This was not solved by that commit
