### ISSUE TITLE
Line Rider - instruction text is rendered incorrectly

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#708]
[SWF](https://github.com/lightspark/lightspark/files/5699906/Linerider.zip) - tested on latest master (bfbcc4c)

To get to this screen, click the Play button.

The left is Lightspark, the right is Adobe. Lightspark appears to wrap the text improperly, and all the letters on the "Continue" button are on top of each other. There's also a weird black box on the top left.

![image](https://user-images.githubusercontent.com/16441870/111641291-ecffa100-884c-11eb-9eba-ed13cc44d530.png)

**Comment by huwdp** [comment]
Similar thing with https://www.mcleodgaming.com.gamecdn.online/files/theme/super-smash/game3.swf. Text  overflows

**Comment by huwdp** [comment]
Similar issue with Pandemic 2
![image](https://user-images.githubusercontent.com/364976/111833655-64374280-88ea-11eb-9a32-1d78cff91dad.png)
