### ISSUE TITLE
will this be available for brave?

### ISSUE THREAD

**Issue by kaedon142** [lightspark/lightspark#723]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x] Feature request: a request for new features or support for new platforms *not sites or SWF files*.
- [x] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.
 
- [ ] Support for a new OS: *<name the operating system here>*
- [x] Support for a new browser: brave
- [ ] Support for embedding in an application: *<name the application here>*

Identify the subject of this issue: will this be available for brave?

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [x] Other subject matter not listed

**Comment by dbluelle** [comment]
AFAIK Brave uses the Chrome Webengine, so you have to try if the PPAPI plugin still works with it.
