### ISSUE TITLE
When will lightspark addone be available on addons.mozilla.com?

### ISSUE THREAD

**Issue by deadman616** [lightspark/lightspark#724]
I'm a Mozilla Firefox user and I play a lot Flash games from time to time, how long before lightspark will be available on addons.mozilla.com?

**Comment by huwdp** [comment]
Latest Firefox does not support plugins and Mozilla are moving away from them

**Comment by veso266** [comment]
I guess if this would be compiled to WebAsembly it would be possible (even to selfhost)

Although not sure how well it compares to ruffie

as for [CheerPX](https://medium.com/leaningtech/cheerpx-for-flash-now-generally-available-a20bc2a5eea6)....
if it would work so well, people would use it, but let me tell you.... it doesn't work, it cannot even play a game they showcased in their [demo](https://youtu.be/7JUs4c99-mo?t=1203), although it might be the version I have is broken or something (yes it is possible to obtain it if you know where to look :smile: ) not sure if I can put a demo up on how it works

**Comment by alexp-sssup** [comment]
> as for [CheerPX](https://medium.com/leaningtech/cheerpx-for-flash-now-generally-available-a20bc2a5eea6)....
> if it would work so well, people would use it, but let me tell you.... it doesn't work

CheerpX _does_ actually work, it is already being used internally by multiple companies. We are soon going to publish a public demo as well, it is taking longer than expecting due to licensing constraints with Adobe's Flash Plugin.

Happy to see that Lightspark (which I started) is still useful and improved after so many years, by the way.

**Comment by veso266** [comment]
It does?
Please put a public demo up, because I would love to see it work, I was so :cry: because mine demo wouldn't perform well (but I guess mine is broken)

**Comment by huwdp** [comment]
@veso266 Please see https://github.com/lightspark/lightspark/discussions/605
