### ISSUE TITLE
Firefox Plugin

### ISSUE THREAD

**Issue by CprogrammerIbrahim** [lightspark/lightspark#731]
Hello I use Ubunto 20.04 (Focal Fossa) and the latest version of Firefox. I installed Lightspark from here manually but I can not see it in the list of plugins when I checked. How to fix it?

**Comment by dbluelle** [comment]
Firefox removed flash support at the beginning of 2021, so lightspark probably won't work with the version shipped with Ubuntu.
Also issue https://github.com/lightspark/lightspark/issues/618 may be relevant if you build lightspark from source.

**Comment by huwdp** [comment]
I haven't been able to get Lightspark working under Firefox or Chrome but I have under Pale Moon and Basilisk. Details here (https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser ).

**Comment by dbluelle** [comment]
I think we can close this
