### ISSUE TITLE
Riven Elementary

### ISSUE THREAD

**Issue by ReNardier** [lightspark/lightspark#733]
this guy https://www.riumplus.com/contact/
as he explained here(nearly 9 years ago) https://youtu.be/XN5Ht3epf1M?t=2617
got a hold of this really old game made in shockwave, but because(as he explains in the video) there is a lot of trouble getting it to run on modern browsers/flash players... he sort of has kept the game to himself on that "real myst book" of his(and i would presume another copy on a thumb-drive for safekeeping... and i presume that only because i genuinely do not know how to feel at the prospect that the only copy is on that book)
do you think you guys could get in contact with him(through the contact methods on his page that i have linked) and try to make it work in lightspark... and hopefully convincing him to release it once and for all?
id really love for Riven Elementary to stop being located-but-inaccessible media(the less mysterious but equally frustrating cousin of lost media)

**Comment by riumplus** [comment]
Hi there! I found this looking through my website analytics at which pages were linking to my website.

I uploaded a full copy of Riven Elementary to my website last year; you can find it at [https://www.riumplus.com/riven-elementary/](https://www.riumplus.com/riven-elementary/) . Included is a projector designed to make it run standalone on modern versions of Windows as well as the original .dcr.

One potential issue for this project though - it's Shockwave, not Flash. But feel free to share, rehost, modify, or do whatever you want with the Riven Elementary files :)

**Comment by dbluelle** [comment]
As this is Shockwave, it is out of the scope of lightspark.
However it seems that scummvm has made some progress in implementing a "director" engine which supports these kind of Games, see https://forums.scummvm.org/viewtopic.php?t=16352&hilit=director .

**Comment by dbluelle** [comment]
I close it as not planned
