### ISSUE TITLE
Install lightspark in Mozila Firefox

### ISSUE THREAD

**Issue by swatwik-dev** [lightspark/lightspark#737]
I have installed the Lightspark-v0.8.4.1-Installer-win64.exe in my windows pc. After that to install the Lightspark I have created the directory 'appdata\Mozilla\plugins' in 'C:\Program Files\Mozilla Firefox'. After I have copied the following files.

libspark.dll
libspark.dll.a
lightspark.exe
nplightsparkplugin.dll

Now how can I see that the Lightspark plugin has been installed in the firefox. Please let me know the way for this.

Please help me.

**Comment by wyatt8740** [comment]
If you are on a recent firefox version, flash support in browser has been removed.

But if you are on an old version, you should make a folder under the 'Mozilla Firefox' directory and copy nplightsparkplugin.dll into it.

**Comment by swatwik-dev** [comment]
@wyatt8740 Thanks for the help.

I have installed the firefox version 83.0 and after that I put nplightsparkplugin.dll by creating the plugins folder.

But not worked. I am testing by this http://ultrasounds.com.  and showing like this.
![image](https://user-images.githubusercontent.com/84808121/120374324-0d60d700-c337-11eb-98b4-d8e6d1432859.png)

Please suggest to overcome the issue.

**Comment by huwdp** [comment]
I'll see if I can get this working on my pc tomorrow and if so I'll write some documentation.

Page here (https://github.com/lightspark/lightspark/discussions/627 ) has steps on how to get it working and where to put the dlls.

**Comment by swatwik-dev** [comment]
> I'll see if I can get this working on my pc tomorrow and if so I'll write some documentation.
> 
> Page here (#627 ) has steps on how to get it working and where to put the dlls.

I have tried already with #627. But not worked too. :( Please let me know if you are get this working in your pc. This will be great help to me. 

Thanks in advance!!.

**Comment by huwdp** [comment]
Did not get Lightspark working in Firefox. I did however get Lightspark working under Basilisk and Pale Moon. Guide here (https://github.com/lightspark/lightspark/wiki/Getting-Lightspark-up-and-running-in-Web-Browser). Please edit page if there is anything to add or fix.

**Comment by dbluelle** [comment]
I think we can close this
