### ISSUE TITLE
Command line interface feature 

### ISSUE THREAD

**Issue by WindowsNT** [lightspark/lightspark#738]
Instead of rendering, it would be nice if it is ablt to convert the swf to some readable format, for example a mp4, or even a rendering pipe of bitmaps. That way we can reuse it in applications that need to read SWF.

**Comment by dbluelle** [comment]
I think that is out of the scope of lightspark, at least it would (IMHO) be a _very_ big task to properly implement such a feature.
But feel free to implement it, if you like.
Maybe it's easier to just use some screen recording tool to capture the output of lightspark.

**Comment by WindowsNT** [comment]
I could make it by using Media Foundation to send to the file instead of writing to the screen. The idea is to automate it somehow.

However building the whole thing for Windows seems complex with all that dependencies around  - but I may try.
Best,
