### ISSUE TITLE
Pursuit of hat unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#750]
Tested on latest master (93b575a8dfd1efe60a7de6adeae4a3cd05b1942e)
[SWF](https://github.com/lightspark/lightspark/files/6638331/pursuit-of-hat-12550.zip)
```
Error #1024: Stack underflow occurred.
    at classes::Preloader/isUrl()
    at classes::Preloader/()
```
[Terminal output](https://github.com/lightspark/lightspark/files/6638342/poh.log)
[`-l 4` terminal output](https://github.com/lightspark/lightspark/files/6638343/poh-l4.log)

**Comment by dbluelle** [comment]
Just FYI: this needs to be run with `-u "http://www.armorgames.com"`, otherwise you only get a white rectangle.
