### ISSUE TITLE
Box2DFlashAS3 demo segfault

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#753]
Tested on latest master (93b575a8dfd1efe60a7de6adeae4a3cd05b1942e)
[SWF](https://github.com/lightspark/lightspark/files/6641825/main_demo_21a.zip)

I can reproduce the crash by clicking/dragging randomly within the window, I couldn't get any more specific steps than that.

[Backtrace](https://github.com/lightspark/lightspark/files/6641828/bt.log)

**Comment by huwdp** [comment]
![image](https://user-images.githubusercontent.com/364976/121772896-4a676d80-cb70-11eb-8d34-62058c1f619e.png)
It hits assert(false) in the switch statement as switch "type" value is bit different.
