### ISSUE TITLE
Johnny Upgrade unsupported

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#756]
[SWF](https://github.com/lightspark/lightspark/files/4244099/mochi_johnnyupgrade1.zip)
Tested on latest master (abcdc55e5b4f5bd136bf4eab676c992c8577c383)

Occurs during the Armor Games intro, after the initial ad loading splash.

```
Error #1034: Type Coercion failed: cannot convert Function to flash.display::DisplayObject.
    at global/()
    at global/()
    at Document/startGame()
    at Document/frame6()
```

[Terminal output](https://github.com/lightspark/lightspark/files/6656391/ju.log)
[`-l 4` terminal output](https://github.com/lightspark/lightspark/files/6656394/ju-l4.log)

**Comment by dbluelle** [comment]
I couldn't reproduce this, on my machine I only get the "Unhandled ActionScript exception" that you also get on Adobe.
When using command line parameter `-ne`, the swf works.

**Comment by eiglow** [comment]
Oh yeah, I forgot about `-ne`.
