### ISSUE TITLE
Dead Zed 2 - text not wrapping

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#759]
[SWF](https://github.com/lightspark/lightspark/files/4478618/deadzed2.zip)
Tested on latest master (74679ff8371bede738f24b21b71dca4ba858e8c3)

This is different to #749; in that issue, all of the text overlaps onto one line. Since that bug was fixed, the text no longer overlaps (newlines work properly), but it still doesn't wrap properly.

To reproduce:
1. Click "PLAY", wait for main menu to appear
2. In the main menu, click "PLAY".

On Lightspark, it looks like this:
![Screenshot_20210621_000456](https://user-images.githubusercontent.com/16441870/122678080-59ab8280-d224-11eb-881c-eaea6b61c296.png)

On Adobe, it looks like this:
![Screenshot_20210621_000608](https://user-images.githubusercontent.com/16441870/122678106-8069b900-d224-11eb-9e6c-15744dc5c3a4.png)

**Comment by dbluelle** [comment]
That's because that TextField uses wordwrap which is not implemented yet.
