### ISSUE TITLE
Commando 2 issues

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#762]
File: https://github.com/lightspark/lightspark/files/6058849/commando-2.zip
Lightspark commit: 6abe727
Steps to re-produce:
1. Download swf file.
2. Run "lightspark commando-2.swf". Possibly with -s local-with-networking.

---

**Issue 1:** 

https://github.com/lightspark/lightspark/blob/38229b07f31fc7d7766f6f3a87d7b0e889663128/src/scripting/flash/text/flashtext.cpp#L336

I tried to remove the exception and just have it so that it defaults to "none" if autoSize value is not in the TextFieldAutoSize list. I know this does not match the specification but I'd thought I'd try it anyway. Didn't go though with this because more issues came up later on.

**Issue 2:**
https://github.com/lightspark/lightspark/blob/38229b07f31fc7d7766f6f3a87d7b0e889663128/src/scripting/avm1_interpreter.cpp#L408
![image](https://user-images.githubusercontent.com/364976/122835382-23373b80-d2e8-11eb-92a7-0dae381b432d.png)
Looks like it trying to decrement an object that has already been deleted hence the weird values in screenshot.

**Comment by huwdp** [comment]
In debug mode, I can trigger the memory issue 90% of the time

**Comment by dbluelle** [comment]
The issues you mentioned are both fixed, however when starting the first mission, the collision detection seems to fail, I've not yet found the reason.

**Comment by huwdp** [comment]
Thank you so much for this. I wish I could help out more on the coding side. I'm trying to used to the code base.
