### ISSUE TITLE
Raindrop animation swf fails to render raindrops

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#763]
[SWF](https://github.com/lightspark/lightspark/files/6691119/f1094.zip)
Tested on latest master (38229b07f31fc7d7766f6f3a87d7b0e889663128)

On Lightspark, the animation doesn't work properly. In the terminal output, this error is printed repeatedly:
```
ERROR: AVM1:4294967295 0 ActionCloneSprite source clip not found: raindrop 0
```

**Comment by dbluelle** [comment]
The raindrops are still not properly rendered as they are MorphShapes which are not fully implemented yet.
However this swf is a nice simple example to keep in mind when implementing rendering of MorphShapes.
