### ISSUE TITLE
How to open standalone light Spark version on Windows 

### ISSUE THREAD

**Issue by MarcoXxX1** [lightspark/lightspark#767]
Hello
I have downloded light Spark Last version and install it on Windows 10
But I don't know how can I open it as standalone version to play swf because I don't want it as a plugin in chrome or firefox?

**Comment by eiglow** [comment]
You can run it with the command prompt. To play a file like that, you would type `lightspark.exe <file>`

I think you can also set it as the default file handler for swf files. I'll double check later, but off the top of my head, you right click a swf, choose Open With, and then choose another program. From there, select the lightspark exe.
