### ISSUE TITLE
Installing browser plugins on ubuntu?

### ISSUE THREAD

**Issue by Meganium97** [lightspark/lightspark#775]
Hey guys, so my use case for lightspark differs a bit so I have no use for playing swf outside of the browser. I am using ubuntu 21.04 with the latest version of chrome and was wondering how I would install the plugin. I just compiled and installed the latest source so I was wondering where to go from here? Thanks in advance.

**Comment by eiglow** [comment]
My understanding is that Chrome has removed support for plugins. I don't think Chromium has though, so maybe you could try that.

**Comment by huwdp** [comment]
It should be possible to get Lightspark to work under Pale-Moon and Balistik.

**Comment by huwdp** [comment]
I'll see if can get Lightspark working under Pale Moon. It should be possible as it's working for me under Windows.

**Comment by huwdp** [comment]
If you compile the project, copy liblightspark.so and liblightsparkplugin.so to your mozilla plugin folder.

```
sudo cp liblightspark.so /usr/lib/mozilla/plugins/liblightspark.so
sudo cp liblightsparkplugin.so /usr/lib/mozilla/plugins/liblightsparkplugin.so
```

I went here (https://www.y8.com/games/pathfinder_maze) for example and I can see Lightspark's menu if I right click on the game. I did however have to remove Flash that was already on my machine before I could get Lightspark to run in Pale-Moon.

**Comment by Meganium97** [comment]
> If you compile the project, copy liblightspark.so and liblightsparkplugin.so in your build folder to your mozilla plugin folder.
> 
> ```
> sudo cp liblightspark.so /usr/lib/mozilla/plugins/liblightspark.so
> sudo cp liblightsparkplugin.so /usr/lib/mozilla/plugins/liblightsparkplugin.so
> ```
> 
> I went here (https://www.y8.com/games/pathfinder_maze) for example and I can see Lightspark's menu if I right click on the game. I did however have to remove Flash that was already on my machine before I could get Lightspark to run in Pale-Moon.

Where would this be for a default installation of palemoon?

**Comment by huwdp** [comment]
Pale Moon checks the default Firefox location for plugins so the "/usr/lib/mozilla/plugins/" for me.

If you go to Firefox and Pale Moon, go to url bar and type in "about:config". There you'll see further details such as where your profile is stored, where your plugins are, etc.
