### ISSUE TITLE
Massive Memory Leak after Incorrectly Scaling Morphshape

### ISSUE THREAD

**Issue by jhwgh1968** [lightspark/lightspark#782]
### What is the purpose of your issue?
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

I have created a testing file to reproduce the issue.

It used to be very NSFW flash file (as you can tell if you decompile it) but I have deleted almost all of the visual assets. Just don't use your imagination too much.

[morphshape_leak.zip](https://github.com/lightspark/lightspark/files/6760187/morphshape_leak.zip)

#### Provide the complete set of instructions required to reproduce the problem:

1. Open the file on the lightspark command line on desktop.
2. A list of errors come up: `Exception while parsing Alpha data in DefineBitsJPEG3`. *This is expected due to the asset deletion.*
2. A mostly-black screen appears. *This is expected due to the asset deletion.*
3. Click on the "eee" button.

#### What kind of failure is your issue?

Incorrect rendering and a serious memory leak.

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.4-472-g4a99d64c Copyright 2009-2013 Alessandro Pignotti and others
```

Current git master, dated July 3rd.

#### What operating system are you are running on?

- [x] Linux: Arch Linux

#### How are you are running Lightspark?

- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line, but there is nothing in the logs that is useful.

---

### Description of your issue

On Adobe Flash Player, a series of shapes are rendered and morphed, rotating and translating them across the screen. It plays correctly.

On lightspark, the morphed shapes scale upwards in size for some reason, eventually filling the screen. Once the canvas size exceeds the rendering area (or perhaps a limit of the GPU, I can't tell) the buffer then leaks.

This results in several MB per second of memory leakage, and completely incorrect visuals.

This is a bug I noticed several years ago as part of an archiving project. Back then, lightspark crashed completely. The effects have been mitigated more and more across releases, but it's still here. That suggests it is a really subtle bug, and would remain unfixed forever if I didn't open an issue.

After all this time, I finally learned enough about Flash to create this testing file, allowing me to submit this without risking violation of the GH ToS -- or bad feelings from anyone who has to investigate it.

**Comment by huwdp** [comment]
```
==45169== HEAP SUMMARY:
==45169==     in use at exit: 22,678,727 bytes in 68,396 blocks
==45169==   total heap usage: 1,356,930 allocs, 1,288,534 frees, 223,037,115 bytes allocated
==45169== 
==45169== LEAK SUMMARY:
==45169==    definitely lost: 1,998,737 bytes in 9,074 blocks
==45169==    indirectly lost: 16,592,344 bytes in 55,142 blocks
==45169==      possibly lost: 3,728,128 bytes in 99 blocks
==45169==    still reachable: 359,518 bytes in 4,081 blocks
==45169==                       of which reachable via heuristic:
==45169==                         newarray           : 1,536 bytes in 16 blocks
```
I ran this file under Valgrind and found the above. I'll see if I can generate a file for everyone to examine.

Version: 055c96bb45e9819a8f016b9a4a647112846b07af

**Comment by jhwgh1968** [comment]
I had trouble running it in valgrind, because it was too slow. I used [heaptrack](https://github.com/KDE/heaptrack) on it, and got a pretty nice graph. 

My current theory after looking at this myself is that the leak is really just a side effect. The question I have is: why is the canvas expanding in the first place? Floating point round off? Randomness in the calculation of the motion?

I think there is something wrong with the morph shape algorithm.
