### ISSUE TITLE
Error #1063: Argument count mismatch on...

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#784]
Common issue with a lot of games so I thought I'd post this here as a fix for this would probably allow loads of other games to work too hopefully.

I'm sure I've seen more of these errors with other games but I have not noted them down. I will note them next time though. Latest version of Lightspark is running games really well and is very impressive :)

```
Error #1063: Argument count mismatch on gfx::BirdBG. Expected 2, got 0.
```

---

**Dino** [dinorun.zip](https://github.com/lightspark/lightspark/files/6780467/dinorun.zip)

---

**Raze** 
[Raze.zip](https://github.com/lightspark/lightspark/files/6780472/Raze.zip)
```
Error #1063: Argument count mismatch on Menu. Expected 2, got 0.
```

Steps to reproduce:
1. Press Play.

**Comment by dbluelle** [comment]
dinorun has to be run with parameter `-ne`
