### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#787]
[Here](https://github.com/lightspark/lightspark/files/6819482/lightspark-build.zip) is the terminal output from my attempt to build

**Comment by eiglow** [comment]
I only got this on my laptop though, not my desktop (it builds successfully on my desktop), so maybe this is more of a tech support ticket than a real issue

**Comment by dbluelle** [comment]
Hmm, it seems to have compiled everything but linking it all together fails.
Maybe there are some leftovers from a previous build, so try building from an empty build directory.
If that doesn't help, please post the output of the cmake step in an empty build directory and the contents of <build-dir>/src/CMakeFiles/spark.dir/link.txt.

**Comment by eiglow** [comment]
Trying again from an empty build directory worked, thanks.
