### ISSUE TITLE
Johnny Upgrade - stuck after clicking New Game

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#793]
[SWF](https://github.com/lightspark/lightspark/files/4244099/mochi_johnnyupgrade1.zip)
Tested on latest master (0f1bc7887021705746d41537883b4ea8277e62b9)

This game must be run with `-ne`.

To reproduce, wait until the main menu appears, then click "NEW GAME". The game then gets stuck here:

![Screenshot_20210807_145728](https://user-images.githubusercontent.com/16441870/128589193-f80bfe87-1903-4dce-a9f2-32023956590a.png)

[`-l 4` terminal output](https://github.com/lightspark/lightspark/files/6948626/johnny-l4.zip)

**Comment by dbluelle** [comment]
mistakenly closed
