### ISSUE TITLE
Johnny Upgrade - segfault when clicking "High Scores"

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#794]
[SWF](https://github.com/lightspark/lightspark/files/4244099/mochi_johnnyupgrade1.zip)
Tested on latest master (0f1bc7887021705746d41537883b4ea8277e62b9)

This game must be run with `-ne`.

This is the "HIGH SCORES" button in the main menu, to the right of "NEW GAME". Just wait for the intro animations to pass, and it will appear.

[gdb.txt](https://github.com/lightspark/lightspark/files/6948672/gdb.txt)

**Comment by dbluelle** [comment]
fixed in https://github.com/lightspark/lightspark/commit/1b2e0c29a8e809c7efd2da89522d830ee4da91e6
