### ISSUE TITLE
Text rendering regression: text on buttons not positioned correctly; all stacked in top left corner of screen since June

### ISSUE THREAD

**Issue by dragontamer8740** [lightspark/lightspark#809]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:
[Warning: NSFW flash file](http://swfchan.com/34/165499/?Nimin+Fetish+Fantasy+v0.975o1.swf) (no images, though; text only)

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
[Warning: NSFW flash file](http://swfchan.com/34/165499/?Nimin+Fetish+Fantasy+v0.975o1.swf)

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. Game renders text at incorrect coordinates on initial screen.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

It's git master.
```
INFO: Lightspark version 0.8.5-1207-g498f78d1 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: Debian sid
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

Sometime after May 25 of this year and before June 29, text stopped rendering inside of the button frames in the linked flash.

I have attached screenshots of the game in lightspark at git `gb762e2ad` (25 May 2021), `g48506cbc` (29 June 2021), and `g498f78d1` (today's git master, 25 September 2021). Also attached is a screenshot from Adobe's player, for reference.

25 May 2021 (`gb762e2ad`):

![lightspark_20210525_gb762e2ad](https://user-images.githubusercontent.com/6090083/134783658-64e981a9-e9d1-4c5e-94cf-c6c455972e95.png)

29 June 2021 (`g48506cbc`):

![lightspark_20210629_g48506cbc](https://user-images.githubusercontent.com/6090083/134783665-06050abb-04f3-4bd9-8d26-cd8008bd5833.png)

25 September 2021 (`g498f78d1`):

![lightspark_20210925_g498f78d1](https://user-images.githubusercontent.com/6090083/134783684-41325776-5ce7-4cdc-ae26-d12e6aa72b17.png)

Adobe Flash Player 11:

![lightspark_flashplayer11](https://user-images.githubusercontent.com/6090083/134783699-099c7afb-55db-4f8b-ab24-3d2f44bed36f.png)

There is partial source code for this flash on github, but the author omitted the .FLA file, regrettably.

**Comment by dbluelle** [comment]
This seems to be fixed by one of the latest commits
