### ISSUE TITLE
Insectonator - Smith and Wesson gun does not work properly

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#821]
[SWF](https://github.com/lightspark/lightspark/files/7233936/swf.zip)
Tested on latest master (a270428a66946f62e7f70bf89836d38cbcc998fe)

Before the second level, you unlock the Smith and Wesson gun. When using it in the level, no bullet impacts appear, and the gun cannot be used. It appears to shoot, but no sound plays either. However, if you switch back to the Rock weapon, the Rock works fine, its just the gun that is broken.

**Comment by dbluelle** [comment]
This seems to be fixed by one of the latest commits, so I'm closing this
