### ISSUE TITLE
QWOP - Player limbs look kind of wrong

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#822]
[SWF](https://github.com/lightspark/lightspark/files/5316469/qwop.zip)
This occurs since commit 05d8e9c3701416add27377b125c39a86c26dd2df.

Maybe this is more correct than it was before, and its just due to the missing filters. Either way, the incorrect rendering is more obvious since that commit.

Lightspark:

![image](https://user-images.githubusercontent.com/16441870/135737064-afe19d82-7355-4967-b63b-419dd09323de.png)

Adobe:

![image](https://user-images.githubusercontent.com/16441870/135737073-815d1ce6-9089-4d12-93b3-08ad5ab7e23b.png)

**Comment by GordonFreakman** [comment]
an attempt at replicating the bevel gradient effect

**Comment by eiglow** [comment]
Tested at 78ae64af2a5b68ca0462757db3d514a37ff2c6b8:

![image](https://user-images.githubusercontent.com/16441870/221385871-b9f8e308-36f8-4f9a-af28-9c2ed0fb1e36.png)
