### ISSUE TITLE
Incorrect work with a lot. of vector graphics.

### ISSUE THREAD

**Issue by serfcity** [lightspark/lightspark#824]
Once I try open http://flash.neonarod.com/flash/insavt_anim.swf (on page flash.neonarod.com) and vector graphicks work incorrect. (It isn't work)

Can you patch plugin?)

**Comment by eiglow** [comment]
For convenience, and backup if the link dies, 
[here](https://github.com/lightspark/lightspark/files/7451161/insavt_anim.zip) is the swf

Seems like some of the sprites render incorrectly.

Lightspark:

![image](https://user-images.githubusercontent.com/16441870/139631732-7cceafd9-6b5b-4a97-8d15-372205703ecd.png)

Adobe:

![image](https://user-images.githubusercontent.com/16441870/139631765-be80bfa1-f484-47a0-a667-350108d5f52a.png)
