### ISSUE TITLE
Horse Isle - Segfault while typing in login form

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#838]
[SWF](https://github.com/lightspark/lightspark/files/7405140/horseisle.zip)
Tested on latest master (8d5beed5b2cb656701ecd4fb88ddfbb2337f2a2b)

To reproduce, type some characters into the login form.

After a few characters are typed, Lightspark crashes.

[Backtrace](https://github.com/lightspark/lightspark/files/7493352/gdb.txt)

**Comment by huwdp** [comment]
I can re-produce the same issue if I type really fast. If I do it slow then it works fine.

**Comment by huwdp** [comment]
```terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::replace: __pos (which is 10) > this->size() (which is 9)
```
