### ISSUE TITLE
Music not looping

### ISSUE THREAD

**Issue by Twilight774** [lightspark/lightspark#842]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file
http://eye.swfchan.com/flash.asp?id=171840&n=loops.swf
http://eye.swfchan.com/flash.asp?id=195152&n=looops.swf
http://eye.swfchan.com/flash.asp?id=195511&n=loooops.swf

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. Listen
3. You can click and change music loop
4. No music is looping

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
version 0.8.5-1256-gb7df5196 
```
#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)
With this option and browser open this swf make my pc freeze for few minutes
[trace3.txt](https://github.com/lightspark/lightspark/files/7551128/trace3.txt)

**Comment by huwdp** [comment]
[loooops.zip](https://github.com/lightspark/lightspark/files/7577666/loooops.zip)
[looops.zip](https://github.com/lightspark/lightspark/files/7577668/looops.zip)
[loops.zip](https://github.com/lightspark/lightspark/files/7577669/loops.zip)
Files attached
