### ISSUE TITLE
How can I use lightspark on ninja kiwi archive?

### ISSUE THREAD

**Issue by MaxBr5** [lightspark/lightspark#846]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x] Question, Comment, or Suggestion

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

URL of page

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file

#### Provide the complete set of instructions required to reproduce the problem:
1. Load the page.
First, download the ninja kiwi archive
2. *Insert second action here*
Paste the lightspark installation directory into C:\Users\your_user\AppData\Roaming\Ninja Kiwi Archive
3. *Insert third action, and so on*
And then what? Nothing happens
#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:
INFO: Lightspark version 0.8.4-git Copyright 2009-2013 Alessandro Pignotti and others
```
Paste output here
INFO: Lightspark version 0.8.4-git Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [x] Windows 7, 8 or 10
#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [x] Browser plugin for other browser: *<Ninja Kiwi Archive>*

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### If this issue is a *feature request*:

Identify the type of request:

- [ ] Support for a new OS: *<name the operating system here>*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [x] The documentation of how to use Lightspark, including the wiki

---

### Description of your issue
I have difficulty setting it up on ninja kiwi archive, which needs a flash player implementation.
*Explanation of your issue in arbitrary form goes here.*
I have difficulty setting it up on ninja kiwi archive, which needs a flash player implementation.

**Comment by huwdp** [comment]
By this comment here (https://steamcommunity.com/id/HELPINEEDACUSTOMURL/recommended/1275350/), I doubt you can use Lightspark with this "archive". If you can download the swf files via your internet browser then you can play it with Lightspark, I know that some of the games do work with Lightspark if you can get the swf files.
