### ISSUE TITLE
Using a redis server to load data crashes Lightspark standalone app

### ISSUE THREAD

**Issue by mypinballs** [lightspark/lightspark#851]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [x ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

URL of page

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. *Insert second action here*
3. *Insert third action, and so on*

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [x ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
0.8.5
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x ] Linux: *<ARM, Rpi4 Buster>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [ x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### If this issue is a *feature request*:

Identify the type of request:

- [ ] Support for a new OS: *<name the operating system here>*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

Trying to use Lightspark to replace the old x86 linux flasher player 11.2 on linux to run the graphics engine for a pinball project we are working on updating using a rpi4 (arm) running buster . The reason to use Lightspark is because the original flash player is only for x86 linux. The original system used a redis server to send data to a main flash swf file that then loaded other flash swf files and passed data from the game code to it. When running this using lightspark the standalone app crashes.

I launch the app using: lightspark -s local-with-networking

adding -l 4 give the following attached log file, also attached is a filter not_implemented search of the log
[log.txt](https://github.com/lightspark/lightspark/files/7577205/log.txt)
[not_implemented.txt](https://github.com/lightspark/lightspark/files/7577206/not_implemented.txt)

What I would like to know is if this problem is because of missing support for some libraries, or if I am doing something wrong getting the local network connection to work with Lightspark or something else. If to do with things not yet support an idea of the timeline to add would be useful.

**Comment by dbluelle** [comment]
It seems that the swf file tries to connect to the redis server on `127.0.0.1:6379`, but doesn't get an answer. I assume your server is running on localhost and listening at port 6379?
It may be the same issue as https://github.com/lightspark/lightspark/issues/831#issuecomment-963144463 .
Please upload the swf file, because otherwise it's very hard to debug this.

**Comment by mypinballs** [comment]
Thanks for reply. Link to the swf is here:

https://www.dropbox.com/s/94htfi4oiz638yu/mgxbase_r4b.swf?dl=0 (available for 1 week)

Some more info after looking at the redis server. It is setup to run on 127.0.0.1 and port 6379. Here is an except of the log showing that the redis sever accepts the swf connection.

```
1731:M 25 Nov 2021 19:07:42.959 - 0 clients connected (0 replicas), 1106692 bytes in use
1731:M 25 Nov 2021 19:07:47.976 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:07:47.978 - 0 clients connected (0 replicas), 1106692 bytes in use
1731:M 25 Nov 2021 19:07:52.996 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:07:52.998 - 0 clients connected (0 replicas), 1106692 bytes in use
1731:M 25 Nov 2021 19:07:57.041 - Accepted 127.0.0.1:56300
1731:M 25 Nov 2021 19:07:58.016 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:07:58.016 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:03.031 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:03.031 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:08.053 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:08.053 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:13.069 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:13.069 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:18.086 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:18.087 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:23.103 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:23.103 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:28.119 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:28.120 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:33.136 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:33.137 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:38.151 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:38.151 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:43.166 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:43.166 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:48.182 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:48.183 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:53.199 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:53.199 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:08:58.214 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:08:58.214 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:03.230 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:03.230 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:08.249 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:08.249 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:13.266 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:13.268 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:18.284 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:18.286 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:23.302 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:23.306 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:28.321 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:28.323 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:33.337 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:33.337 - 1 clients connected (0 replicas), 1123756 bytes in use
1731:M 25 Nov 2021 19:09:38.353 - DB 0: 4 keys (0 volatile) in 4 slots HT.
1731:M 25 Nov 2021 19:09:38.355 - 1 clients connected (0 replicas), 1123756 bytes in use
```

I also confirmed that the swf isn't 'crashed' in the pure sense of it but hanging waiting for something. I confirmed it unfroze if I stopped the Redis server, but of course it doesn't do anything, so something is halting the comms process

**Comment by dbluelle** [comment]
The main problem is that in order to check if the connection to the redis server is allowed, we have to download a "Socket policy file" from the server. Adobe first tries port 843 and then falls back to the server socket port "127.0.0.1:6379". As redis doesn't know how to handle such a request, the client doesn't get a response and freezes.
If I remove the code for downloading that file from lightspark, the connection works and lightspark starts communicating with the redis server.
So you have to setup a server that provides a valid socket policy file on localhost:843.
Maybe we should add a command line argument to ignore that check or provide a socket policy file from the local filesystem.

**Comment by mypinballs** [comment]
Thanks for the reply. An argument to ignore this check would be useful as both systems are running on the same machine locally, the redis server is just a middleman to allow data transfer from game code to display engine so security isn't a concern here. 

Also, what is different here from the original flash version as that worked fine using this setup. the version of flash I used was an old one to 11.2, as that was the last version to support 32 bit linux.

**Comment by dbluelle** [comment]
I've made a commit to lightspark so that socket connections on the local machine are working without a policy file when using the command line parameter `-s local-trusted`.
The documentation from adobe is not very clear on how to handle this case, so I think this is the best solution for now.

**Comment by mypinballs** [comment]
Tested using the latest build and the `-s local-trusted` and the communication now works. More issues though that I will log separately
