### ISSUE TITLE
Cannot install required packages for building [Debian]

### ISSUE THREAD

**Issue by MangyCat** [lightspark/lightspark#852]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [x] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---
### If this issue is a *feature request*:

Identify the type of request:

- [x] Support for a new OS: *Debian Sid*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [x] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [x] Other subject matter not listed

---

### Description of your issue

so i used that command to install the required development libraries for building and i get this error
full output
[link](https://pastebin.com/cvx9R8vZ)

the first things i tried was installing those packages but specifying the version and this happens
```
Package libavutil-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libavutil-dev:i386

E: Version '7:4.3.2-0+deb11u2' for 'libavutil-dev' was not found

```

libavresample
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libavresample4 : Depends: libavutil56 (= 7:4.3.2-0+deb11u2) but 7:4.4.1-2 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by dbluelle** [comment]
You need to install the development package for libswresample, not libavresample.
The readme had some misleading info, which was recently corrected.
