### ISSUE TITLE
Bloons TD 3 - Explosion sounds from Cannon are doubled

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#856]
[SWF](https://github.com/lightspark/lightspark/files/4478581/bloonstd3.zip)
Tested on latest master (b3b44d2b5c65f46b460dbd2af784a1a3030894ee)

To reproduce:
1. Choose a map and difficulty
2. Choose the Cannon (bomb icon) and place it somewhere on the track
3. Click "Start Round"

For me, the first two explosions sound normal. But after the third explosion, they start to sound doubled-up.

**Comment by dbluelle** [comment]
Seems to be fixed by one of the latest commits, so I close this
