### ISSUE TITLE
Burnout Interactive Map not working

### ISSUE THREAD

**Issue by maddes-b** [lightspark/lightspark#881]
### What is the purpose of your issue?
- [X] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:

http://www.senocular.com/burnout/

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [X] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-git Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [X] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [ ] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [X] Browser plugin for other browser: Pale Moon 29.4.3
- [ ] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

Interactive map not working, looks like Lightspark wants to display it as a movie.

**Comment by dbluelle** [comment]
This needs to be run with parameter `-u http://www.senocular.com/burnout/` to work.

**Comment by maddes-b** [comment]
Still cannot get it to run either via standalone nor via Pale Moon plugin.
I only installed Lightspark, then installed Pale Moon and copied the 2 files to the Pale Moon's plugins folder. Am I missing something?

That's what I get in the console when running via standalone as admin. Lightspark windows shows only UI and no map.
While in Pale Moon it stay empty (white).

```
"C:\Program Files\Lightspark\lightspark.exe" -u http://www.senocular.com/burnout/ burnout_paradise_interactive_map.swf
INFO: Lightspark version 0.8.5-git Copyright 2009-2013 Alessandro Pignotti and others
INFO: RenderThread this=0x2aed840
INFO: Creating input thread
INFO: Switching to remote sandbox because of remote url
ERROR: Could not read registry key value SOFTWARE\MozillaPlugins\@lightspark.github.com/Lightspark;version=1\GnashPath
ERROR: Could not find gnash in C:\Program Files\Lightspark
INFO: Running in remote sandbox
INFO: zlib compressed SWF file: Version 7
INFO: FrameRate 24
INFO: Creating VM
INFO: SWF Metadata:
        :
        :
        :
INFO: Fragment shader compilation WARNING: 0:5: '' :  #version directive missing


INFO: Vertex shader compilation

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Kozuka Gothic Pro R Not-Rotated 11px", falling back to "Sans Not-Rotated 11px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Kozuka Gothic Pro R Not-Rotated 14px", falling back to "Sans Not-Rotated 14px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "_typewriter Not-Rotated 12px", falling back to "Sans Not-Rotated 12px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Sans Not-Rotated 12px", falling back to "Sans Not-Rotated 12px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Sans Not-Rotated 14px", falling back to "Sans Not-Rotated 14px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Arial Not-Rotated 12px", falling back to "Sans Not-Rotated 12px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Sans Not-Rotated 11px", falling back to "Sans Not-Rotated 11px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;35mCRITICAL←[0m **: pango_font_description_set_size: assertion 'size >= 0' failed

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: couldn't load font "Arial Not-Rotated 11px", falling back to "Sans Not-Rotated 11px", expect ugly output.

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!

(lightspark.exe:7480): Pango-←[1;33mWARNING←[0m **: All font fallbacks failed!!!!
INFO: FPS: 12 0
INFO: FPS: 24 0
INFO: FPS: 23 0
INFO: FPS: 24 0
INFO: FPS: 23 0
INFO: FPS: 23 0
INFO: FPS: 24 0
INFO: FPS: 23 0
INFO: FPS: 24 0
INFO: FPS: 23 0
INFO: FPS: 23 0
INFO: FPS: 24 0
INFO: FPS: 23 0
INFO: FPS: 23 0
INFO: FPS: 25 0
INFO: FPS: 23 0
...
```
![image](https://user-images.githubusercontent.com/565223/174675626-b7c63ec4-edad-489b-b53a-202b725c42df.png)

![image](https://user-images.githubusercontent.com/565223/174675718-c6560da6-f160-4208-a3e5-2549753f921d.png)

**Comment by maddes-b** [comment]
This was tested with release 0.8.5 from July/2021.
Will check how to setup a build environment.
Sorry for the noise.
