### ISSUE TITLE
Aimbooster - Unsupported error

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#886]
[SWF](https://github.com/lightspark/lightspark/files/5316392/AimBooster.zip)
Occurs since f7964bf80eceee3edef2612df00e988f606d3d98.

To reproduce, click "Challenge".

```
Cause: std::bad_alloc
```

**Comment by Fenveireth** [comment]
Ignoring those NaN matrices dodges the problem again, but it does not seem right
What are those nans doing here ?

**Comment by dbluelle** [comment]
I've bisected this issue and it's https://github.com/lightspark/lightspark/commit/f7964bf80eceee3edef2612df00e988f606d3d98 that causes this.
The NaN matrices are "normal", they also appear when the swf file works (the swf file creates matrices with scaling 0 wich leads to NaN entires later on).
@Fenveireth can you take another look at your commit and implement special handling for NaN matrix entries?
