### ISSUE TITLE
(Red Ball) Camera doesn't move

### ISSUE THREAD

**Issue by guest123guest** [lightspark/lightspark#889]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [x] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---
#### Provide the complete URL of the page with the issue here:

This isn't a website, but rather a game that can be downloaded from here: https://www.speedrun.com/redball1/resources

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

https://drive.google.com/file/d/1dvM7VoIdnX9sEo7OB6J7ybNcZG_ZrCpp/view?usp=sharing

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the game. (Should be called "Red Ball - Definitive Edition.swf" within the archive)
2. Click play
3. Click on the first level
4. Try moving, the camera won't follow you.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1342-g92f36a8f Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: Devuan 4 (chimaera)
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

Camera doesn't follow the player in the game "Red Ball".
![Screenshot_2022-01-12_20-23-39](https://user-images.githubusercontent.com/37600325/149255327-2961e79a-6bb9-47b3-aebc-973e5856c6e2.png)

**Comment by eiglow** [comment]
Thanks for the bug report.

For conveniece, since the archive is quite large, I will attach only the game that this bug report is about.

[Red Ball - Definitive Edition.zip](https://github.com/lightspark/lightspark/files/7859761/Red.Ball.-.Definitive.Edition.zip)

I could reproduce this on latest git master (92f36a8f01ae792b3c0c5e62debf70d68a6722ab).
