### ISSUE TITLE
Package 'SDL2_mixer', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by Ultrabenosaurus** [lightspark/lightspark#897]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [x] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

N/A

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

N/A

#### Provide the complete set of instructions required to reproduce the problem:

1. Download latest 0.8.5 source tar.gz
2. Extract archive
3. Open terminal to location
4. Run `sudo ./build.sh`
5. Error in build process

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [x] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``: N/A (cannot run lightspark but downloaded source is 0.8.5)

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: *<specify distro and version here, such as Ubuntu 18.04>*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

OS: Manjaro Linux x86_64 
Kernel: 5.10.93-1-MANJARO 
Shell: bash 5.1.16 
DE: Plasma 5.23.5 
WM: KWin

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

While trying to build lightspark 0.8.5 from source `sdl2` is found but module `SDL2_mixer` is not, causing the build to fail. I've looked at various results across Google and DDG but with almost no experience building from source I cannot see a solution among them. 

```
~/Downloads/lightspark-0.8.5: sudo ./build.sh
[sudo] password for ultrab: 
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test GCC_IS_4_6
-- Performing Test GCC_IS_4_6 - Success
-- Gnash not found
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found Freetype: /usr/lib/libfreetype.so  
-- Found OpenGL: /usr/lib/libOpenGL.so   
-- Found GLEW: /usr/lib/libGLEW.so  
-- Found PCRE: /usr/lib/libpcre.so  
-- Found JPEG: /usr/lib/libjpeg.so (found version "80") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.37") 
-- Checking for module 'liblzma'
--   Found liblzma, version 5.2.5
-- Checking for modules 'cairo;pangocairo'
--   Found cairo, version 1.17.4
--   Found pangocairo, version 1.50.3
-- Checking for modules 'libavcodec;libavutil;libavformat'
--   Found libavcodec, version 58.134.100
--   Found libavutil, version 56.70.100
--   Found libavformat, version 58.76.100
-- Checking for module 'libswresample'
--   Found libswresample, version 3.9.100
-- Looking for avcodec_decode_video2
-- Looking for avcodec_decode_video2 - found
-- Looking for avcodec_decode_audio3
-- Looking for avcodec_decode_audio3 - not found
-- Looking for avcodec_decode_audio4
-- Looking for avcodec_decode_audio4 - found
-- Looking for avio_alloc_context
-- Looking for avio_alloc_context - found
-- Looking for avcodec_alloc_context3
-- Looking for avcodec_alloc_context3 - found
-- Looking for avcodec_open2
-- Looking for avcodec_open2 - found
-- Looking for avformat_close_input
-- Looking for avformat_close_input - found
-- Looking for avformat_find_stream_info
-- Looking for avformat_find_stream_info - found
-- Looking for av_frame_alloc
-- Looking for av_frame_alloc - found
-- Looking for av_frame_unref
-- Looking for av_frame_unref - found
-- Looking for av_packet_unref
-- Looking for av_packet_unref - found
-- Looking for avcodec_send_packet
-- Looking for avcodec_send_packet - found
-- Looking for avcodec_receive_frame
-- Looking for avcodec_receive_frame - found
-- Looking for av_frame_get_sample_rate
-- Looking for av_frame_get_sample_rate - found
-- Performing Test HAVE_AVCODECID
-- Performing Test HAVE_AVCODECID - Success
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.70.2
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.20
-- Checking for module 'SDL2_mixer'
--   Package 'SDL2_mixer', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:392 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/ultrab/Downloads/lightspark-0.8.5/obj-release/CMakeFiles/CMakeOutput.log".
See also "/home/ultrab/Downloads/lightspark-0.8.5/obj-release/CMakeFiles/CMakeError.log".
```

**Comment by eiglow** [comment]
I've never used Manjaro before but I think it uses pamac. Can you try this?
```
pamac install sdl2_mixer
```

**Comment by Ultrabenosaurus** [comment]
@eiglow I tried that, but in my Dunning-Kruger cleverness I swapped the underscore for a hyphen because _obviously_ that's how all Linux packages work. 

Funnily enough, `pamac` installs it when I use an underscore...  :facepalm: 

The build has now completed successfully and it runs, only to discover that Lightspark doesn't yet support the game I wanted to play. 

```
SWF file: file:///home/ultrab/Downloads/Nv2/Nv2-Linux.swf
ArgumentError: Function applied to wrong object
    at audiovisual.entitygraphics::EntityGraphics_Ninja/UpdateState()
    at audiovisual::GraphicsManager/Render()
    at com.metanet::App_MultiPurpose/tickSimulator()
    at com.metanet::App_MultiPurpose/continueReplay()
    at com.metanet::App_MultiPurpose/tickReplayInProgress()
    at com.metanet::App_MultiPurpose/tickReplay()
    at com.metanet::App_MultiPurpose/tick()
    at NMediator/handleEnterFrame()
    at org.robotlegs.base::EventMap/routeEventToListener()
    at N/()
```

https://www.thewayoftheninja.org/n.html

**Comment by eiglow** [comment]
> I tried that, but in my Dunning-Kruger cleverness I swapped the underscore for a hyphen because _obviously_ that's how all Linux packages work.
> 
> Funnily enough, `pamac` installs it when I use an underscore...

To be fair, it is quite unusual for a package name to use underscores, I think I've made similar mistakes like that in the past.

Anyway, I can also reproduce that issue. I will open a separate ticket for it: #898

**Comment by Ultrabenosaurus** [comment]
Thank you.
