### ISSUE TITLE
ubuntu 20.04 installing issue

### ISSUE THREAD

**Issue by aL1NaZ4R** [lightspark/lightspark#904]
Hello, i have linux ubuntu 20.04 and tried to install lightspark
i runned that command was noted in README.md 
`sudo apt install git gcc g++ nasm cmake gettext libcurl4-gnutls-dev libsdl2-mixer-dev libsdl2-dev libpango1.0-dev libcairo2-dev libavcodec-dev libswresample-dev libglew-dev librtmp-dev libjpeg-dev libavformat-dev liblzma-dev`
but there is no shockwave flash in firefox, also nothing happens in pale moon

**Comment by dbluelle** [comment]
That command only installs the requirements neccessary to _build_ lightspark from source. You have to follow the rest of the readme to actually get a working lightspark binary.

**Comment by aL1NaZ4R** [comment]
> That command only installs the requirements neccessary to _build_ lightspark from source. You have to follow the rest of the readme to actually get a working lightspark binary.

ok thanks
