### ISSUE TITLE
Hexagon segfaults on startup

### ISSUE THREAD

**Issue by arthomnix** [lightspark/lightspark#908]
### What is the purpose of your issue?
- [x] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:
[https://terrycavanaghgames.com/hexagon/](https://terrycavanaghgames.com/hexagon/)
#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

[https://terrycavanaghgames.com/hexagon/hexagon.swf](https://terrycavanaghgames.com/hexagon/hexagon.swf)
(needs to be run with `-u https://terrycavanaghgames.com/hexagon/hexagon.swf`)

#### Provide the complete set of instructions required to reproduce the problem:

1. Download SWF file
2. Run with `lightspark -u https://terrycavanaghgames.com/hexagon/hexagon.swf hexagon.swf`

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [x] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1419-g7ca16ee1 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: Arch Linux (up to date as of 06/03/2022, zen kernel)
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I attached a screen shot of the problem to this issue
- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue

Trying to run the [Hexagon SWF](https://terrycavanaghgames.com/hexagon/hexagon.swf) via Lightspark on the command line results in a window with three white rectangles appearing for a couple of seconds (see screenshot) and then a segfault.

Screenshot from just before crash:
![image](https://user-images.githubusercontent.com/35371030/156932434-74e8c2f1-3923-4f30-8810-73b80a274075.png)

Backtrace from GDB:
```
(gdb) bt
#0  0x00007ffff52c679f in av_frame_move_ref () at /usr/lib/libavutil.so.57
#1  0x00007ffff5701a4d in avcodec_receive_frame () at /usr/lib/libavcodec.so.59
#2  0x00007ffff7449c53 in lightspark::FFMpegAudioDecoder::decodePacket(AVPacket*, unsigned int) (this=0x7fffc800a7f0, pkt=0x7fffd77fce80, time=0) at /home/arthomnix/git/lightspark/src/backends/decoder.cpp:1091
#3  0x00007ffff744b389 in lightspark::FFMpegStreamDecoder::decodeNextFrame() (this=0x7fffc8000f40) at /home/arthomnix/git/lightspark/src/backends/decoder.cpp:1488
#4  0x00007ffff79eb2c9 in lightspark::SoundChannel::playStream() (this=0x7fff085d1bd0) at /home/arthomnix/git/lightspark/src/scripting/flash/media/flashmedia.cpp:980
#5  0x00007ffff79eae1d in lightspark::SoundChannel::execute() (this=0x7fff085d1bd0) at /home/arthomnix/git/lightspark/src/scripting/flash/media/flashmedia.cpp:936
#6  0x00007ffff7432d53 in lightspark::ThreadPool::job_worker(void*) (d=0x555555f30878) at /home/arthomnix/git/lightspark/src/thread_pool.cpp:109
#7  0x00007ffff7190e99 in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007ffff6b765c2 in start_thread () at /usr/lib/libc.so.6
#9  0x00007ffff6bfb584 in clone () at /usr/lib/libc.so.6
```
`lightspark -u https://terrycavanaghgames.com/hexagon/hexagon.swf hexagon.swf -l 4`:
[lightspark.log.gz](https://github.com/lightspark/lightspark/files/8192986/lightspark.log.gz)

**Comment by dbluelle** [comment]
Hmm, I couldn't reproduce this with the current git version, maybe one of the recent commits has already fixed this.
However the sounds and graphics are not correct.

**Comment by poudink** [comment]
I get the same result. This could be related to https://github.com/lightspark/lightspark/issues/931

**Comment by poudink** [comment]
Indeed, I no longer get this issue now that #931 has been fixed.

**Comment by arthomnix** [comment]
Works again for me now (although still with graphical issues).
