### ISSUE TITLE
Bloons Tower Defence 4 - regression

### ISSUE THREAD

**Issue by huwdp** [lightspark/lightspark#916]
https://github.com/lightspark/lightspark/files/4052144/bloons_tower_defense_4.zip

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
zsh: abort      sudo lightspark bloons_tower_defense_4.swf
```

Run file and the error will appear.

Commit: 20cf8ce1b9c4eea8446f73eb4a762ac6f2de4eb5
Git bisect coming up in near future.

**Comment by dbluelle** [comment]
I couldn't reproduce this, maybe it's already solved by one of the latest commits.

**Comment by huwdp** [comment]
It happens for me. It does so after loading an ad so maybe it's the ad doing it

**Comment by dbluelle** [comment]
I could reproduce it, it only crashed if you don't have any SharedObjects saved for the game...
