### ISSUE TITLE
Super Mario 63 Doesn't Load [Regression]

### ISSUE THREAD

**Issue by poudink** [lightspark/lightspark#924]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### Provide the complete URL of the page with the issue here:

URL of page: https://web.archive.org/web/20211122160505/http://runouw.com/games/sm63/

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file: [Super Mario 63.zip](https://github.com/lightspark/lightspark/files/8266408/Super.Mario.63.zip)

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the game.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [X] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1433-g20cf8ce1 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: *Fedora 35*
- [ ] Mac OS X
- [ ] Other

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [X] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue

Dunno where to find log files, sorry. Will attach one if I find it. Anyway, the loading screen never ends. Mario is normally supposed to collect 100 coins, after which the player will be able to progress past the loading screen. Here, coins start incrementing very fast without stopping at 100 right after touching the first coin. The coins don't disappear when collected and produce no sound effect. This is a regression from the latest release (0.8.5), where coins would disappear when collected and would produce a sound effect (which seemed to severely lag the game, but worked). The coin counter also incremented correctly, but coins stopped appearing before reaching 100 so the loading screen still couldn't be passed. Another issue from this latest version that didn't happen in the latest release is that Mario now permanently stops moving after hitting a block. Worth noting that the Ruffle project is able to play the game properly.
![image](https://user-images.githubusercontent.com/29778535/158646849-8c321a95-eab1-4355-83dc-de2d66295947.png)
Bisect coming soon if I don't forget.

**Comment by poudink** [comment]
33522e4996bbfbf77ad0aa395e60315b249e346f's the culprit. While bisecting I found that there were versions between 0.8.5 and master that did get past the loading screen. Haven't yet found the commit for that regression.

**Comment by poudink** [comment]
The crash when clicking anywhere seems to be gone as of latest commit, but you still cannot progress because the skip button still never appears.

**Comment by poudink** [comment]
There seems to have been a bit of a regression. Now, the game crashes right after Mario first hits a block in the loading screen. Not totally sure whether that was caused by a recent commit or my switch to EndeavourOS, however.

**Comment by poudink** [comment]
sorry but that made it even worse at least on my end. now it crashes the moment mario touches a coin.

**Comment by dbluelle** [comment]
I couldn't reproduce the crash but I fixed several audio and multithreading issues, maybe that fixes this, too.
