### ISSUE TITLE
Regression on 885373328a666723c2e71aaa26bbb42ac9c9ce72

### ISSUE THREAD

**Issue by JousterL** [lightspark/lightspark#934]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

http://d.furaffinity.net/art/jousterl/1405946010/1405946010.jousterl_1405925576.jasonafex_scappo_slime_girl_jasonafex.swf (NSFW)

#### Provide the complete set of instructions required to reproduce the problem:

1. Compile any commit after 9c9ce72
2. Attempt to load flash.
3. Observe segfault.
4. Comment out line 882 in /src/backends/decoder.cpp, recompile
5. Attempt to load flash
6. Observe working flash.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [X] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

INFO: Lightspark version 0.8.5-1458-g5335d1d6 Copyright 2009-2013 Alessandro Pignotti and others

```
INFO: Lightspark version 0.8.5-1458-g5335d1d6 Copyright 2009-2013 Alessandro Pignotti and others
INFO: RenderThread this=0x5614ad6464c0
INFO: Creating input thread
INFO: Running in local-with-filesystem sandbox
INFO: zlib compressed SWF file: Version 11
INFO: FrameRate 60
INFO: Creating VM
INFO: SWF Metadata:
	:		
	:		
	:		
INFO: Fragment shader compilation 
INFO: Vertex shader compilation 
INFO: Window resized to 1382x1110
INFO: VIDEO DEC: Video frame size 208x208
[mp3 @ 0x7f7bd4fbe140] invalid concatenated file detected - using bitrate for duration
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
INFO: AUDIO DEC: Audio sample rate 44100
INFO: AUDIO DEC: Audio channels 2
Segmentation fault (core dumped)

```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: Ubuntu 21.10
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)
[out.txt](https://github.com/lightspark/lightspark/files/8497255/out.txt)

### Description of your issue

Attempting to launch the latest build immediately crashes with a segfault after drawing a little of the starting screen. Commenting out a specific line of the FFMpegAudioDecoder Destructor function restores functionality.
```
#if (defined HAVE_AVCODEC_SEND_PACKET && defined HAVE_AVCODEC_RECEIVE_FRAME)
        //av_frame_free(&frameIn);
#endif
```

**Comment by dbluelle** [comment]
I couldn't reproduce this but I assume it's the same problem as https://github.com/lightspark/lightspark/issues/935

**Comment by JousterL** [comment]
Confirmed that the new build off cd8328d resolves the issue.
