### ISSUE TITLE
[Regression?] Puzzle Bobble now just crashes before the Taito logo can show.

### ISSUE THREAD

**Issue by guest123guest** [lightspark/lightspark#935]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [x] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

https://archive.org/details/puzzle_swf

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

https://archive.org/download/puzzle_swf/puzzle.swf

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. The game just crashes.

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [x] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1474-g6dc7a109 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: Devuan 4
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

### Description of your issue

Now the flash port of Puzzle Bobble simply crashes upon startup.
[puzzle.log](https://github.com/lightspark/lightspark/files/8497270/puzzle.log)

**Comment by guest123guest** [comment]
This might also be an issue on my end, I'm currently doing a clean compile of Lightspark to see if it can fix anything.

**Comment by huwdp** [comment]
Do you know what version it worked on last? I recommend using git bisect to find the broken commit if you know when it worked last

**Comment by dbluelle** [comment]
It seems that the latest sound patch broke support for older ffmpeg versions (< 5.0). 
I've just committed a fix, but I couldn't test it because I don't have an appropriate setup.
Please test it and report back.

**Comment by guest123guest** [comment]
It seems to work now, though I might make another issue about a graphics-related issue.
