### ISSUE TITLE
Run3 Crash

### ISSUE THREAD

**Issue by poudink** [lightspark/lightspark#945]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [X] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

[URL of file](https://www.speedrun.com/resourceasset/1f4e9)

#### Provide the complete set of instructions required to reproduce the problem:

1. Launch the game.

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1482-g5e6d5855 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: *EndeavourOS*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [X] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
Doesn't happen with every version of the game. The one from https://github.com/lightspark/lightspark/issues/508 doesn't have the issue. May have been introduced in a later version.
Error:
```
SWF file: file:///run/media/poudink/hdd/Documents/Flash Player/run3.swf
std::bad_alloc
```
Backtrace: [backtrace.log](https://github.com/lightspark/lightspark/files/8543470/backtrace.log)
Log: [log.txt](https://github.com/lightspark/lightspark/files/8543465/log.txt)

**Comment by poudink** [comment]
Not fixed for me. Still crashes with the exact same error:
```
SWF file: file:///run/media/poudink/hdd/Documents/Flash Player/run3v1.swf
std::bad_alloc
```
Actually, though this may be a different issue entirely, it seems like there's even been some sort of regression. I can longer play the version from https://github.com/lightspark/lightspark/issues/508.
I get the following error:
```
SWF file: file:///run/media/poudink/hdd/Documents/Flash Player/run3v0.swf
ArgumentError: Error #1034: Error #1034: Type Coercion failed: cannot convert String to ?.
    at com.player03.run3.achievement::-_--___----_/()
    at com.player03.run3.achievement::Achievement/-_-_-__---__()
    at com.player03.run3.achievement::Achievements/-___--_-__-_()
    at com.player03.run3.achievement::Achievements/()
    at com.player03.run3.achievement::Achievements/()
    at Class/----__---()
    at com.player03.run3.character::-_-____-___-/---_--___-()
    at com.player03.run3.menu::----_-_-_-_/-_--_-----__()
    at com.player03.run3.menu::----_-_-_-_/()
    at com.player03.run3.menu::----_-_-_-_/()
    at com.player03.run3.menu::-______--__/addCharacterUpgrade()
    at com.player03.run3.menu::-______--__/-___--_-__-_()
    at com.player03.run3.menu::-______--__/()
    at com.player03.run3.menu::-______--__/()
    at com.player03.run3.menu::-_--_--_---/()
    at com.player03.run3::Main/init2()
    at Class/-__-_----_--()
```
Or, if launching with -ne, a black screen with the following getting spammed in the log:
```
ERROR: trying to get variable on null:[ns:] ----_-_-_-
INFO: throwing exception:0x55985cc23520 id:1009 Error #1009: Cannot access a property or method of a null object reference.
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
INFO: dynamic cast:TypeError
ERROR: Unhandled ActionScript exception in VM TypeError: Error #1009: Error #1009: Cannot access a property or method of a null object reference.
    at /update()
    at com.player03.run3::Main/update()
    at com.player03.run3::Main/onEnterFrame()
```

**Comment by dbluelle** [comment]
OK, the crash is now fixed (again).
I've also fixed the exception on the older version, but unfortunately there is another exception popping up now...

**Comment by poudink** [comment]
Yep, it works now. No longer have any exceptions with the older version, either. There's an error message, but that's only if you don't give it enough permissions (needs -s local-with-networking)
