### ISSUE TITLE
[Adobe Air] Samorost Crash

### ISSUE THREAD

**Issue by poudink** [lightspark/lightspark#950]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

[itch.io (free)](https://amanitadesign.itch.io/samorost-1?ac=Q8uS8a4hVvG)

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the game.

#### What kind of failure is your issue?

- [X] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
INFO: Lightspark version 0.8.5-1489-g8c0d5646 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [X] Linux: *EndeavourOS*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [X] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [X] I have reproduced the problem using the Lightspark command line executable
- [X] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue

The swf file is in the Data folder. Running with --air doesn't make a difference.
Error:
```
SWF file: file:///run/media/poudink/hdd/Documents/Wine/Samorost/Data/Main.swf
ReferenceError: Error #1065: Error #1065: Variable DatagramSocket is not defined.
    at Class/()
    at global/()
```
Log: [LogAir.txt](https://github.com/lightspark/lightspark/files/8568251/LogAir.txt)

**Comment by dbluelle** [comment]
It kind of works now, but the graphics are not correct.
Also you have to use the new command line argument so that the steam api interface is loaded:
`lightspark --load-extension META-INF/AIR/extensions/com.amanitadesign.ANESteam/library.swf --air Data/Main.swf`
(This only loads the steam extension, but doesn't call into the native steam dlls)
