### ISSUE TITLE
FRESteamWorks not supported?

### ISSUE THREAD

**Issue by Techwizz-somboo** [lightspark/lightspark#951]
## In order to help us understand your issue, please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [x] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

URL of page
https://store.steampowered.com/app/1089980/The_Henry_Stickmin_Collection/
#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file
https://store.steampowered.com/app/1089980/The_Henry_Stickmin_Collection/
#### Provide the complete set of instructions required to reproduce the problem:

1. Launch Henry.swf with lightspark.

#### What kind of failure is your issue?

- [x] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``: 

```
INFO: Lightspark version 0.8.5-1489-g8c0d5646 Copyright 2009-2013 Alessandro Pignotti and others
```

#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: Arch Linux
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

#### How are you are running Lightspark?

- [ ] Browser plugin for Chrome or Chromium: *<specify Chromium version here>*
- [ ] Browser plugin for Waterfox: *<specify Waterfox version here>*
- [ ] Browser plugin for other browser: *<specify browser and version here>*
- [x] Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [x] I attached a screen shot of the problem to this issue
- [x] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### If this issue is a *feature request*:

Identify the type of request:

- [ ] Support for a new OS: *<name the operating system here>*
- [ ] Support for a new browser: *<name the operating system here>*
- [ ] Support for embedding in an application: *<name the application here>*

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

```
INFO: throwing exception:0x562c8d80e520 id:1065 Error #1065: Variable FRESteamWorks is not defined.
INFO: throwing exception:0x562c8d80e520 id:1065 Error #1065: Variable File is not defined.
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1065: Error #1065: Variable File is not defined.
INFO: dynamic cast:ReferenceError
ERROR: Unhandled ActionScript exception in VM ReferenceError: Error #1065: Error #1065: Variable File is not defined.
    at com.innersloth.henry.Bios::BiosMain/LoadFromDisk()
    at com.innersloth.henry.Bios::BiosMain/()
    at com.innersloth.henry::Main/()

INFO: ~RenderThread this=0x562c8e22e6c0
```

https://github.com/Ventero/FRESteamWorks
Henry Stickmin steam release relies on FRESteamWorks for Flash. 
Lightspark also doesn't support flash.filesystem.File it seems?
![Screenshot from 2022-04-28 19-23-05](https://user-images.githubusercontent.com/44146804/165871854-a0c0566e-d20b-4a7a-abf4-55eecd59c652.png)
[l4.zip](https://github.com/lightspark/lightspark/files/8587574/l4.zip)

**Comment by dbluelle** [comment]
The flash.filesystem APIs are only available in Adobe AIR applications, so you have to start lightspark with the --air command line argument. Also I assume this uses the same extension mechanism as Samorost1 (see https://github.com/lightspark/lightspark/issues/950 ), so you also have to load the extension via the new command line argument --load-extension

**Comment by Techwizz-somboo** [comment]
Hey, 
Thanks. That does indeed fix my steam related problems but I still get "Property url not found on flash.filesystem::File and there is no default value."

Thanks again!

**Comment by dbluelle** [comment]
I've implemented the url property on flash.filesystem.File, but it's not really tested, so I don't know if it works...

**Comment by dbluelle** [comment]
We now have (more or less) complete support for the steamworks native extension, so I'm closing this.
If you still have problems with flash.filesystem.File, please open a new issue.

**Comment by Techwizz-somboo** [comment]
Cool, I'll give it a test when I get some time. Thank you.
