### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by oEjk** [lightspark/lightspark#954]
## In order to help us understand your issue, please follow the guide below

Sure no problem. But I am having a build issue.

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes `[ ]` relevant to your issue (like this: `[x]`)
- Please fill in the sections relevant to your issue and delete the rest.
- Use the *Preview* tab to see what your issue will actually look like

---

### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [ ] Question, Comment, or Suggestion
- [x] If none of the above apply, check this box.

---

### The following sections should be filled in based on the purpose listed above. Erase any section (the contents between triple ---) that does not apply.

---

#### Provide the complete URL of the page with the issue here:

URL of page

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:

URL of file

#### Provide the complete set of instructions required to reproduce the problem:

1. Load the page.
2. *Insert second action here*
3. *Insert third action, and so on*

#### What kind of failure is your issue?

- [ ] **Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered an as yet unsupported Flash file``
- [ ] **Crash**: The window disappears or your browser crashes with a message such as ``A tab has crashed``
- [ ] **Broken**: Lightspark shows something, but most of the file is not usable
- [ ] **Glitch**: Lightspark shows something and most of the file is usable, but things are missing or wrong compared to official Flash.
- [ ] **Performance**: Lightspark runs slow or uses lots of memory trying to play the file

#### Provide the Lightspark version

Output of ``lightspark -v``:

wont build, cannot do this

#### What operating system are you are running on?

- [x] Linux: Artix LXQt OpenRc

#### How are you are running Lightspark?

- [ ] Lightspark executable on the command line
but it wont build

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [ ] I have reproduced the problem using the Lightspark command line executable
- [ ] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [ ] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

None of those.

### Description of your issue

*Explanation of your issue in arbitrary form goes here.*

I did this...

./build.sh
-- Gnash not found
-- The ASM-NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Checking for module 'librtmp'
--   Found librtmp, version v2.4
-- Looking for C++ include atomic
-- Looking for C++ include atomic - found
-- Checking for module 'x11'
--   Found x11, version 1.8
-- Configuring done
-- Generating done
-- Build files have been written to: /lightspark-0.8.5/obj-release
Scanning dependencies of target spark
[  1%] Generating fr.gmo
[  2%] Generating pl.gmo
[  2%] Generating zh_CN.gmo
[  2%] Building CXX object src/CMakeFiles/spark.dir/allclasses.cpp.o
[  3%] Building CXX object src/CMakeFiles/spark.dir/compat.cpp.o
[  3%] Building CXX object src/CMakeFiles/spark.dir/asobject.cpp.o
[  3%] Built target translations
[  3%] Building CXX object src/CMakeFiles/spark.dir/logger.cpp.o
[  4%] Building CXX object src/CMakeFiles/spark.dir/memory_support.cpp.o
[  4%] Building CXX object src/CMakeFiles/spark.dir/swf.cpp.o
[  5%] Building CXX object src/CMakeFiles/spark.dir/swftypes.cpp.o
[  5%] Building CXX object src/CMakeFiles/spark.dir/thread_pool.cpp.o
[  5%] Building CXX object src/CMakeFiles/spark.dir/threading.cpp.o
[  6%] Building CXX object src/CMakeFiles/spark.dir/timer.cpp.o
[  6%] Building CXX object src/CMakeFiles/spark.dir/tiny_string.cpp.o
[  6%] Building CXX object src/CMakeFiles/spark.dir/errorconstants.cpp.o
[  7%] Building CXX object src/CMakeFiles/spark.dir/backends/audio.cpp.o
[  7%] Building CXX object src/CMakeFiles/spark.dir/backends/builtindecoder.cpp.o
[  8%] Building CXX object src/CMakeFiles/spark.dir/backends/config.cpp.o
[  8%] Building CXX object src/CMakeFiles/spark.dir/backends/currency.cpp.o
[  8%] Building CXX object src/CMakeFiles/spark.dir/backends/decoder.cpp.o
[  9%] Building CXX object src/CMakeFiles/spark.dir/backends/extscriptobject.cpp.o
[  9%] Building CXX object src/CMakeFiles/spark.dir/backends/geometry.cpp.o
[ 10%] Building CXX object src/CMakeFiles/spark.dir/backends/graphics.cpp.o
/lightspark-0.8.5/src/backends/decoder.cpp: In member function ‘virtual void lightspark::FFMpegVideoDecoder::switchCodec(lightspark::LS_VIDEO_CODEC, uint8_t*, uint32_t, double)’:
/lightspark-0.8.5/src/backends/decoder.cpp:164:43: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  164 |                 codec=avcodec_find_decoder(FFMPEGcodecId);
      |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                           |
      |                                           const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp:172:43: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  172 |                 codec=avcodec_find_decoder(FFMPEGcodecId);
      |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                           |
      |                                           const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp:183:43: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  183 |                 codec=avcodec_find_decoder(FFMPEGcodecId);
      |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                           |
      |                                           const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp:194:43: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  194 |                 codec=avcodec_find_decoder(FFMPEGcodecId);
      |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                           |
      |                                           const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp: In constructor ‘lightspark::FFMpegVideoDecoder::FFMpegVideoDecoder(AVCodecParameters*, double)’:
/lightspark-0.8.5/src/backends/decoder.cpp:245:44: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  245 |         AVCodec* codec=avcodec_find_decoder(codecPar->codec_id);
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp: In member function ‘virtual void lightspark::FFMpegAudioDecoder::switchCodec(lightspark::LS_AUDIO_CODEC, uint8_t*, uint32_t)’:
/lightspark-0.8.5/src/backends/decoder.cpp:736:44: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  736 |         AVCodec* codec=avcodec_find_decoder(LSToFFMpegCodec(audioCodec));
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp: In constructor ‘lightspark::FFMpegAudioDecoder::FFMpegAudioDecoder(lightspark::EngineData*, lightspark::LS_AUDIO_CODEC, int, int, bool)’:
/lightspark-0.8.5/src/backends/decoder.cpp:772:44: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  772 |         AVCodec* codec=avcodec_find_decoder(codecId);
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                            |
      |                                            const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp: In constructor ‘lightspark::FFMpegAudioDecoder::FFMpegAudioDecoder(lightspark::EngineData*, AVCodecParameters*)’:
/lightspark-0.8.5/src/backends/decoder.cpp:811:44: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  811 |         AVCodec* codec=avcodec_find_decoder(codecPar->codec_id);
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            const AVCodec*
/lightspark-0.8.5/src/backends/decoder.cpp: In member function ‘virtual uint32_t lightspark::FFMpegAudioDecoder::decodeData(uint8_t*, int32_t, uint32_t)’:
/lightspark-0.8.5/src/backends/decoder.cpp:948:24: error: ‘frameIn’ was not declared in this scope
  948 |         av_frame_unref(frameIn);
      |                        ^~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp:964:35: error: ‘resampleFrameToS16’ was not declared in this scope
  964 |                         int len = resampleFrameToS16(curTail);
      |                                   ^~~~~~~~~~~~~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp: In member function ‘uint32_t lightspark::FFMpegAudioDecoder::decodePacket(AVPacket*, uint32_t)’:
/lightspark-0.8.5/src/backends/decoder.cpp:1070:24: error: ‘frameIn’ was not declared in this scope
 1070 |         av_frame_unref(frameIn);
      |                        ^~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp:1084:35: error: ‘resampleFrameToS16’ was not declared in this scope
 1084 |                         int len = resampleFrameToS16(curTail);
      |                                   ^~~~~~~~~~~~~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp: At global scope:
/lightspark-0.8.5/src/backends/decoder.cpp:1148:5: error: no declaration matches ‘int lightspark::FFMpegAudioDecoder::resampleFrameToS16(lightspark::AudioDecoder::FrameSamples&)’
 1148 | int FFMpegAudioDecoder::resampleFrameToS16(FrameSamples& curTail)
      |     ^~~~~~~~~~~~~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp:1148:5: note: no functions named ‘int lightspark::FFMpegAudioDecoder::resampleFrameToS16(lightspark::AudioDecoder::FrameSamples&)’
In file included from /lightspark-0.8.5/src/backends/audio.h:25,
                 from /lightspark-0.8.5/src/backends/decoder.cpp:23:
/lightspark-0.8.5/src/backends/decoder.h:355:7: note: ‘class lightspark::FFMpegAudioDecoder’ defined here
  355 | class FFMpegAudioDecoder: public AudioDecoder
      |       ^~~~~~~~~~~~~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp:1148:44: error: ‘class lightspark::AudioDecoder::FrameSamples’ is protected within this context
 1148 | int FFMpegAudioDecoder::resampleFrameToS16(FrameSamples& curTail)
      |                                            ^~~~~~~~~~~~
In file included from /lightspark-0.8.5/src/backends/audio.h:25,
                 from /lightspark-0.8.5/src/backends/decoder.cpp:23:
/lightspark-0.8.5/src/backends/decoder.h:275:15: note: declared protected here
  275 |         class FrameSamples
      |               ^~~~~~~~~~~~
/lightspark-0.8.5/src/backends/decoder.cpp: In constructor ‘lightspark::FFMpegStreamDecoder::FFMpegStreamDecoder(lightspark::NetStream*, lightspark::EngineData*, std::istream&, lightspark::AudioFormat*, int)’:
/lightspark-0.8.5/src/backends/decoder.cpp:1279:59: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
 1279 |                                 fmt = av_find_input_format("mp3");
      |                                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                                           |
      |                                                           const AVInputFormat*
/lightspark-0.8.5/src/backends/decoder.cpp:1282:59: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
 1282 |                                 fmt = av_find_input_format("aac");
      |                                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                                           |
      |                                                           const AVInputFormat*
/lightspark-0.8.5/src/backends/decoder.cpp:1286:59: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
 1286 |                                 fmt = av_find_input_format("s16le");
      |                                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                                           |
      |                                                           const AVInputFormat*
/lightspark-0.8.5/src/backends/decoder.cpp:1289:59: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
 1289 |                                 fmt = av_find_input_format("f32be");
      |                                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                                           |
      |                                                           const AVInputFormat*
/lightspark-0.8.5/src/backends/decoder.cpp:1316:42: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
 1316 |                 fmt=av_probe_input_format(&probeData,1);
      |                     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |                                          |
      |                                          const AVInputFormat*
make[2]: *** [src/CMakeFiles/spark.dir/build.make:300: src/CMakeFiles/spark.dir/backends/decoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:190: src/CMakeFiles/spark.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

Please advise

**Comment by dbluelle** [comment]
It seems that cmake didn't properly detect ffmpeg.
Please remove the build directory (obj-release), execute build.sh again and post the output.

**Comment by Techwizz-somboo** [comment]
Along with that, make sure you have ffmpeg installed.

**Comment by thesamesam** [comment]
This looks like more of an ffmpeg 5 issue.

**Comment by dbluelle** [comment]
This looks like it's the same problem as https://github.com/lightspark/lightspark/issues/843, so it may have already been fixed.
I assume you're not using the latest git to build lightspark?
Please try to build from the latest git and report if the problem still exits.

**Comment by oEjk** [comment]
pulled and built 21 days ago?
#843 was closed Nov2021?

**Comment by dbluelle** [comment]
OK, maybe you accidentally cloned the repository from tag 0.8.5 the first time...
However I think we can close this now.
