### ISSUE TITLE
Fedora 36 "Rendering: Cannot initialize GLEW!" error

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#958]
On Fedora 36, compiled freshly from git master (ecc1a1f30881f7954b6110ad4240153bc7d64fbe at the time of writing), it fails to run any SWF file, as far as I can tell.

![image](https://user-images.githubusercontent.com/16441870/169778259-32e68052-1a62-4ffd-b8de-332e23f75212.png)

The relevant terminal output doesn't seem very useful. (excerpt from running [qwop](https://github.com/lightspark/lightspark/files/5316469/qwop.zip))
```
ERROR: Cannot initialize GLEW: cause Unknown error
```

There were a couple of compile warnings that seem unrelated to this error, but here is the output of `./build.sh` anyway: [build.log](https://github.com/lightspark/lightspark/files/8752876/build.log)

I tried deleting `obj-release` and `obj-build` before running `build.sh`.

I have `glew`, `glew-devel`, and `libGLEW` packages installed.

**Comment by dbluelle** [comment]
Hmm, the build.log looks ok, so I don't know what causes this.
AFAIK Fedora uses Wayland by default maybe lightspark still has problems with Wayland...

**Comment by eiglow** [comment]
I doubt that is the issue. I have been using Lightspark on Wayland for months, but this problem has only occurred recently.

I recently upgraded to Fedora 36, which could be the issue. I'll do some experimentation in a VM.

**Comment by huwdp** [comment]
I use Wayland, and Lightspark works great

**Comment by dbluelle** [comment]
Does lightspark work if you just ignore the error by removing the `throw RunTimeException("Rendering: Cannot initialize GLEW!");` line from engineutils.cpp?

As a workaround you can try to build with -DENABLE_GLES2, that would lead to not using glew at all (but that doesn't really fix the issue).

**Comment by eiglow** [comment]
Seems like it is Wayland-related. On a Fedora 35 and a Fedora 36 machine, this error occurs on the Plasma Wayland session, but not on the Plasma X11 session.

**Comment by dbluelle** [comment]
Hmm, that's strange.
Did you set the SDL_VIDEODRIVER environment variable to "wayland" when testing on Wayland?
If not, there will be an error,  but IMHO it should be something like "No GLX display" instead of "cause Unknown error"...
So maybe something is wrong with your glew install.
Please replace the line 
`LOG(LOG_ERROR,"Cannot initialize GLEW: cause " << glewGetErrorString(err)); `
with
`LOG(LOG_ERROR,"Cannot initialize GLEW: cause " << err << " "<< glewGetErrorString(err)); `
in engineutils.cpp and post the output.
That way we can see which error code is generated by glewInit.

**Comment by eiglow** [comment]
Looks like `SDL_VIDEODRIVER=wayland lightspark <file>` does work properly. I guess I should put this in my `.bashrc` or something?

With that change, the log says:
```
ERROR: Cannot initialize GLEW: cause 4 Unknown error
```

**Comment by dbluelle** [comment]
I think we can close this.
