### ISSUE TITLE
HiDPI support in X11

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#965]
On X11, many apps scale themselves according to the global scale.

However, Lightspark seems to always behave as if the global scale is 1. This makes Lightspark very small on devices with high pixel density (for example, my 13-inch laptop with a 3456x2160 display), regardless of the chosen scale.

Maybe SDL has a way of easily grabbing the global scale?

I haven't tested this on wayland yet.

**Comment by dbluelle** [comment]
Unfortunately I don't have any HiDPI display available, so I can't do any testing...
SDL has the `SDL_WINDOW_ALLOW_HIGHDPI` flag when creating a window, maybe that already does the trick.
You can test it by replacing
`SDL_Window* window = SDL_CreateWindow("Lightspark",SDL_WINDOWPOS_UNDEFINED,SDL_WINDOWPOS_UNDEFINED,w,h,SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);`
with 
`SDL_Window* window = SDL_CreateWindow("Lightspark",SDL_WINDOWPOS_UNDEFINED,SDL_WINDOWPOS_UNDEFINED,w,h,SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);`
in main.cpp, line 108.

**Comment by eiglow** [comment]
That didn't seem to make much difference, but maybe its still necessary.

Maybe we need to multiply the `reqWidth` and `reqHeight` inside `SystemState::delayedCreation` in `swf.cpp` by the scale factor?

I have no idea what `SDL_WINDOW_ALLOW_HIGHDPI` is actually supposed to do. However, replacing
```
sys->engineData->showWindow(reqWidth, reqHeight);
```
with
```
sys->engineData->showWindow(reqWidth * 1.5, reqHeight * 1.5);
```
makes things look better on my laptop. The challenge here could be actually getting the right scale factor, I couldn't find a way to do it easily though SDL on X11.

**Comment by dbluelle** [comment]
Hmm, maybe we should add an environment variable (and/or a command line parameter) for the default initial scaling factor. 
It seems there are several applications that solve this that way (see https://wiki.archlinux.org/title/HiDPI).
That way you can set a scaling factor even if you don't have a HiDPI monitor.
