### ISSUE TITLE
Consider new release for ffmpeg 5 fixes

### ISSUE THREAD

**Issue by thesamesam** [lightspark/lightspark#986]
### What is the purpose of your issue?
- [ ] Site Support Request: Lightspark does not work correctly on a specific website.
- [ ] Bug: Lightspark has the same problem across multiple websites or SWF files.
- [ ] Feature request: a request for new features or support for new platforms, *not sites or SWF files*.
- [X] Question, Comment, or Suggestion
- [ ] If none of the above apply, check this box.

### If this issue is a *question, comment, or suggestion*:

Identify the subject of this issue:

- [ ] The documentation of how to use Lightspark, including the wiki
- [ ] The build instructions to compile Lightspark from source
- [X] The project and how it is managed (people, process, and so on)
- [ ] Other subject matter not listed

---

### Description of your issue

Slowly, Linux distributions are trying to work through the various packages which don't build with the latest FFmpeg. It looks like lightspark has been fixed in git for a while but the patches are too big to easily backport and don't apply cleanly to the last release.

Would it be possible to have a new release with these fixes? Thanks!

**Comment by eiglow** [comment]
Last release was in 04 Jul 2021, I think it's time for a new release anyway.

I'll try to do some testing on Windows to avoid needing something like the [0.8.4.1](https://github.com/lightspark/lightspark/releases/tag/0.8.4.1) hotfix release.

**Comment by dbluelle** [comment]
Yeah, there are still a lot of unfixed issues, but I think we should make a release anyway.
I propose to do it in two weeks and until then no big new features will be added, just small bugfixes.

**Comment by dbluelle** [comment]
Release 0.8.6 is online.

**Comment by thesamesam** [comment]
Thank you!
