### ISSUE TITLE
In lightspark, when clicking on Ruffle, the noise ear-rape emits...

### ISSUE THREAD

**Issue by TheAmazingAladdin** [lightspark/lightspark#990]
### Description of your issue

Everytime i click on ruffle, it plays an noise ear-rape which is caused by lightspark sound emulation...

https://user-images.githubusercontent.com/108961061/186047268-31ce9093-2381-40eb-8444-325c8e25d4b1.mp4

## Excpected Behaviour

https://user-images.githubusercontent.com/108961061/186047325-bbea351c-dc9b-43b8-92e9-bda7b8f18ea3.mp4

## Log

[log.zip](https://github.com/lightspark/lightspark/files/9398617/log.zip)

**Comment by huwdp** [comment]
There's a whole conversation on this issue here (https://github.com/lightspark/lightspark/discussions/932). Btw, it's only happening on Windows, Linux works fine
