### ISSUE TITLE
Segmentation fault or abort occurs when EventDispatcher methods are called with null this

### ISSUE THREAD

**Issue by jchv** [lightspark/lightspark#998]
Simple enough, there's no checks to ensure that the `obj` atom is actually an `EventDispatcher`. This can lead to an assertion failure abort (in Debug mode) or a segfault (in Release mode) instead of throwing an exception.

**Comment by dbluelle** [comment]
IMHO this should not happen and indicates a bug elsewhere in lightspark.
Can you provide an swf file that triggers this?

**Comment by jchv** [comment]
Sorry, I forgot where I found this. I think it occurred when a MovieClip variable became null.

**Comment by dbluelle** [comment]
I've closed the PR for now as I wasn't able to find a test swf that triggers this error.
I keep this issue open in case you (or somebody else) finds  one.
